### ISSUE TITLE
Rename mdk to origo

### ISSUE THREAD

**Issue by afogelberg** [origo-map/origo#1]
All instances of mdk need to be renamed to origo. Should we use the namespace origo? Or should we just use the letter o?

**Comment by markus659** [comment]
I think we should just use 'o'. Using 'origo' would probably decrease the readability of the code even though it's longer. Just like OpenLayers uses the more abbreviated way of referencing the library (ol), I think we also can go with the shorter version.

**Comment by afogelberg** [comment]
I agree, I think we should use the shorter o.

**Comment by jokd** [comment]
Go with the o!

Från: Andreas Fogelberg [mailto:notifications@github.com]
Skickat: den 4 maj 2016 08:17
Till: origo-map/origo <origo@noreply.github.com>
Ämne: Re: [origo-map/origo] Rename mdk to origo (#1)


I agree, I think we should use the shorter o.

**Comment by afogelberg** [comment]
An origo map is now created like this:
```
<script src="js/origo.js"></script>
<script type="text/javascript">
	//Init origo
    origo.map.init('index.json');
</script>
```
See #38 and #40

**Comment by afogelberg** [comment]
Closing this issue. Replaced by issue  #103
