### ISSUE TITLE
Elevate the precision of certain touch interactions

### ISSUE THREAD

**Issue by jokd** [origo-map/origo#1016]
**Is your feature request related to a problem? Please describe.**
When using touch devices it can be useful or even critical to be able to add nodes more accurately when editing or measuring.

**Describe the solution you'd like**
Something similar to the crosshair used to pick coordinates can be used along with a button to elevate the precision of touch interactions.

Comments on this?

**Comment by daRasmussen** [comment]
Sounds like a good feature, with a static crosshair and a button. I would suggest as an option that enables this feature for all screen sizes, to start.

**Comment by jokd** [comment]
How about something like this:
https://gi.karlstad.se/jk/measure/

**Comment by daRasmussen** [comment]
@jokd looks good and works very well if I only use keyboard with arrows and enter. Snapping to crosshair on mouse interaction would be a nice feature. Not sure if icon for add new point is adequate enough. Would this feature be optional in the config or always enabled, both are fine by me?

**Comment by jokd** [comment]
@daRasmussen I just picked a icon for testing, agree its not optimal. 

IMO, using keyboard navigation requires better tabbing to activate the tool and panning in smaller steps (perhaps by using the arrows along with another button).

In what situations would snapping the crosshair be useful instead of adding nodes with the button? Or du you mean the crosshair should snap to features in the map? Still not sure how useful that is though and the crosshair is no map element as it is now so it would have to be reworked a bit.

One issue Ive discovered is undoing nodes added with the button sometimes doesn't update the geometry until you move the mouse. I also feel the crosshair can be a bit bigger and less opaque to make it easier to use.

Perhaps configurable (or able to activate as a user), I guess some users will find the crosshair showing up in the map annoying.

**Comment by jokd** [comment]
We could have a crosshair button ao activate the tool (which does exactly the same as the crosshair in the position control) and then another button to add breakpoints. But the toolbar will quickly be filled up:
![image](https://user-images.githubusercontent.com/6848075/98646499-c2985700-2333-11eb-9187-ed0de44ac561.png)

**Comment by daRasmussen** [comment]
@jokd Yeah snapping maybe is a bit out there, It was just a crazy idea. Snapping is not a requirement I guess, maybe that type of use case could possibliy arise in the future, but that code reworking could potentially be done in a plugin or custom build.  

I think activate as use works fine, I guess this is a usability case that if implemented enhances the meaurement control so to disable it in the config defeats the purpose of high usability a bit. 

Overall this feature would be a nice addition to Origo.
