### ISSUE TITLE
Legend max height problems in ie11

### ISSUE THREAD

**Issue by asemoller** [origo-map/origo#1017]
**Describe the bug**
When the legend reaches the maximum height, the scroll bar, background maps and the 'turn-off-layers' button disappear and the legend gets unscrollable. This only occurs in ie11.

**To Reproduce**
1. Create a map with latest origo
2. Click on 'legend'
3. Make the legend reach max height (either by changing the height of the browser or expand multiple groups)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Internet explorer 11

**Screenshots**
![image](https://user-images.githubusercontent.com/17123002/98513749-a976a400-2268-11eb-8c22-7d7edeb51131.png)

**Additional context**
Does we still support ie11?

**Comment by jokd** [comment]
Probably due to this change: #958
and mentioned in #955
