### ISSUE TITLE
Alternative styles for layers

### ISSUE THREAD

**Issue by asemoller** [origo-map/origo#1020]
**Is your feature request related to a problem? Please describe.**
Sometimes a user wants to be able to change a style for a layer.

**Describe the solution you'd like**
It would be a nice feature if a user can choose between several different styles on a layer. For example, if a layer have a black style as standard, you should be able to choose a yellow style if you change the background map to orthophoto. Another application could be to show thematic styles from different attributes for a layer in the map.

**Comment by Grammostola** [comment]
We are currently looking at adding functionality like this via one of our existing plugins. It's intended only for WMS but would partially share bits with equal functionality for client-based styles.

**Comment by asemoller** [comment]
We have a solution for this BUT it´s only for client styling (WFS, geojson). I'm not sure it should belong to the core since it isn't working for server based layers (WMS).

Our solution looks like this:

![stylepicker-issue](https://user-images.githubusercontent.com/17123002/156168403-e2e705bb-bbcb-4fe6-845e-04e19a7e3f3f.gif)

Let us know if this is something that should be in the core. If not, I'll close this issue.

**Comment by jokd** [comment]
This is definitely something for the core. WMS support can be added later on.
