### ISSUE TITLE
Layer swipe and spy

### ISSUE THREAD

**Issue by asemoller** [origo-map/origo#1029]
**Is your feature request related to a problem? Please describe.**
We are planning to develop a tool to compare two different map views. 

**Describe the solution you'd like**
I have made a prototype that shows a possible solution. Comments and ideas are welcome at this early stage.

![swipe_control](https://user-images.githubusercontent.com/17123002/99291395-0b727300-2840-11eb-81d7-a6875acd635b.gif)

**Comment by daRasmussen** [comment]
This looks awesome!

**Comment by jokd** [comment]
Awesome indeed!

**Comment by jokd** [comment]
Consider
https://viglino.github.io/ol-ext/examples/control/map.control.swipe.html
and
https://viglino.github.io/ol-ext/examples/interaction/map.interaction.clip.html

for easier way to implement this. Available through npm. I built the elevation plugin around such an extension, looking at that code may help you.

**Comment by asemoller** [comment]
Thank you @jokd!

We will look into that!

**Comment by asemoller** [comment]
Swiper plugin published at https://github.com/SigtunaGIS/swiper-plugin.
