### ISSUE TITLE
Feature info templates

### ISSUE THREAD

**Issue by jokd** [origo-map/origo#1031]
**Is your feature request related to a problem? Please describe.**
It can be useful to be ale to create a custom template to present the information from the objects. The html-attribute option can get you quite far but for instance when selecting multiple objects that may not be enough.

**Describe the solution you'd like**
Some sort of template system or functionality that can take the information from the selected objects and do something with it. Present some graphs in a modal, summarize data, make an animation, play a song or whatever.

Any ideas how to do this? Does it sound useful or is an external page the way to go?

**Comment by tonnyandersson** [comment]
How about using the feature info template function already implemented since, like, forever?

**Comment by jokd** [comment]
Sounds useful. Documented?

**Comment by tonnyandersson** [comment]
LOL

**Comment by jokd** [comment]
Yeah looking at it right now. Need some rewriting to take multiple features and make something cool with it but that shouldnt be impossible.

**Comment by tonnyandersson** [comment]
Archived and closed due to inactivity.
