### ISSUE TITLE
Follow me option in geoposition control

### ISSUE THREAD

**Issue by johnnyblasta** [origo-map/origo#1036]
**Is your feature request related to a problem? Please describe.**
It would be nice to have a "follow me" option in geoposition control.

**Describe the solution you'd like**
When turning on the geoposition and "pan to" is on the map is centered at current position, but then the map don't continue following the further moving. There should be a way to enable a "follow me" function so that the map is always centered at current position.

**Describe alternatives you've considered**
There should also be configurable so that "follow me" is active at start.

**Additional context**
This is a function that mostly makes sense for mobile devices, so it should perhaps not be turned/visible on desktop computers if that can be determined.

**Comment by jokd** [comment]
This is a nice improvement. I experience the geoposition to fall asleep when the screen is locked and is not reactivated when lit up again, perhaps this can also solve that issue. That is when using the geoposition on an iPhone.
