### ISSUE TITLE
First layer assigned to the root group isn't visible

### ISSUE THREAD

**Issue by Grammostola** [origo-map/origo#1042]
**Describe the bug**
There's no obvious way to turn off the one active layer in the default map configuration

**To Reproduce**

1. Download and run the latest Origo main
2. Check the map and legend in your favourite compatible browser

**Expected behavior**
The active layer should be visible in the legend

**Screenshots**
The initial view
![initial_view](https://user-images.githubusercontent.com/5138906/102376807-4c3ae480-3fc4-11eb-9c93-07c6c8b8a230.PNG)
With two layers in the root group
![two_things_in_root](https://user-images.githubusercontent.com/5138906/102376803-4ba24e00-3fc4-11eb-9a3c-2b5921edbc19.PNG)
With no layer in the root group
![nothing_in_root](https://user-images.githubusercontent.com/5138906/102376806-4c3ae480-3fc4-11eb-825b-7785b3108c09.PNG)

**Additional context**
The issue seems introduced at the "Handle overflow in settings window" commit. 

The relevant bit therein appears to be
`  &.expanded {
    height: calc(100% - 2rem);
  }` of scss/_collapse,scss

**Comment by Grammostola** [comment]
If that bit is excluded from scss/ui/_collapse.scss then the print panel doesn't get a scrollbar on popular iOS devices at the very least. The origo legend looks okay from start though. Can the print panel perhaps be given its own style rule instead of altering the collapse component's style?

**Comment by johnnyblasta** [comment]
> If that bit is excluded from scss/ui/_collapse.scss then the print panel doesn't get a scrollbar on popular iOS devices at the very least. The origo legend looks okay from start though. Can the print panel perhaps be given its own style rule instead of altering the collapse component's style?

Yes it's probably best to give print panel separate style rules since it can be difficult to reconcile the different usage. I can take a look at it next week.
