### ISSUE TITLE
JS documentation

### ISSUE THREAD

**Issue by daRasmussen** [origo-map/origo#1081]
**Is your feature request related to a problem? Please describe.**
It would be nice if it was possible to reuse some of the Origo JS functionallity in other projects like for instance when developing plugins or other applications. 

**Describe the solution you'd like**
Auto generated documentation similar to jsdocs. Would be helpful for developers. 

**Describe alternatives you've considered**
Alternative solution would be to create a repo for this solution, like origo-documentation. Or extend the origo-documentation to multiple pages. 

**Additional context**
Same goes for CSS code as well (seperate issue).

**Comment by jokd** [comment]
Closed due to inactivity
