### ISSUE TITLE
Modal height

### ISSUE THREAD

**Issue by mulfvik** [origo-map/origo#1085]
**Describe the bug**
Modal does not adjust height after viewport

**To Reproduce**
Create a modal with a lot of content

**Expected behavior**
Modal should adjust its height after viewport

**Screenshots**
![modal](https://user-images.githubusercontent.com/24228538/104178320-6a043980-540a-11eb-98e4-bcfab6cd78b6.jpg)

**Smartphone (please complete the following information):**
Galaxy S10e
Android version 10

**Comment by jokd** [comment]
Similar to #1000 (which is solved)?

**Comment by mulfvik** [comment]
Yes, the `o-modal-content` class adjusts the modal height with `max-height: calc(100vh - 60px); ` but maybe that should be set on the `o-modal` class instead?

**Comment by jokd** [comment]
If it works, it works =)

**Comment by mulfvik** [comment]
It doesnt =(
