### ISSUE TITLE
Option to not show Splash when embedded

### ISSUE THREAD

**Issue by MattiasSp** [origo-map/origo#1092]
When embedding a map with the Splash control, the splash modal may cover the entire view if small enough.

It would be very nice if there was an option in the control config to control whether the Splash screen shows when the map is embedded.

Not sure what the default behaviour should be, but I'm leaning towards not showing it unless an option, e.g. "showWhenEmbedded: true" is set.

![image](https://user-images.githubusercontent.com/2445979/104577413-c27d4600-5659-11eb-8691-8c11dc4b9082.png)

**Comment by asemoller** [comment]
Good point! 

In fact, this should be the case for all controls, not just for splash. There can easily be too many buttons when embedded. And sometimes you actually don't want the user to be able to change layer, print or use external links when the map is embedded. 

This would of course be another issue, just saying I think it's a common problem for embedded maps.

**Comment by jokd** [comment]
It would probably be easy to implement as well.

**Comment by jokd** [comment]
But I suggest hideWhenEmbedded: false is default

**Comment by MattiasSp** [comment]
PR incoming for the Splash control.

**Comment by jokd** [comment]
Nice idea @MattiasSp but how about putting that check in the addControl function in viewer.js instead and make it usable for all controls?

**Comment by MattiasSp** [comment]
Thanks, and thanks for the suggestion! Would it be preferable to make a new branch and PR or make further commits to the current one in this case?

**Comment by jokd** [comment]
I think its ok to keep it in this issue/PR!

**Comment by MattiasSp** [comment]
Updated PR is ready :)

**Comment by MattiasSp** [comment]
Another update for the PR is ready.
