### ISSUE TITLE
Open/closed group chevron rotation

### ISSUE THREAD

**Issue by mulfvik** [origo-map/origo#1099]
When a group is open in legend the chevron is not rotated to pointing downwards
![legendarrow](https://user-images.githubusercontent.com/24228538/104728426-2c1f5200-5737-11eb-83d4-a832c85b44a1.gif)

**Comment by jokd** [comment]
Anybody working on this?

**Comment by mulfvik** [comment]
Not that I know, got sick 😫

**Comment by jokd** [comment]
OK, I'll have a look
