### ISSUE TITLE
Reduce build size

### ISSUE THREAD

**Issue by jokd** [origo-map/origo#1102]
**Is your feature request related to a problem? Please describe.**
The build size is with all controls activated around 2MB, without any control 1400kB. This is far more than a while ago so I suppose there are things to do here.

**Describe the solution you'd like**
Identify what increases the build size. Dependencies, scripts etc. And of course other ways to trim the size and then take action.

**Comment by daRasmussen** [comment]
@jokd I have looked into this issue but not been able to resolve it completly jet. I've manged to reduce bundle size by removing exposure to ol. Not sure if this is the problem but maybe these dependencies could be loaded separatly like origo_createBox.min.js or something like that. I will do some more research before a PR.

**Comment by jokd** [comment]
@daRasmussen I tried that as well, stripped origo.js of basically everything just to save 500kB 2.2->1.7MB
Must be something else to do, perhaps some webpack setting

**Comment by jokd** [comment]
Running npm run build-js-analyze shows:
![image](https://user-images.githubusercontent.com/6848075/106191084-b1304f80-61aa-11eb-83f0-a696db88099e.png)

**Comment by daRasmussen** [comment]
@jokd better?
![image](https://user-images.githubusercontent.com/33061427/106203121-358ace80-61bb-11eb-9add-eb23fc3dc6c8.png)

**Comment by daRasmussen** [comment]
So I've done some more work, and manged to create a vendor-jspdf chunk, with dynamic imports and magic webpack comments: 
OLD: 
```
const pdf = new jsPDF({ ... }); 
```
NEW:
```
const pdf = await import(/* webpackChunkName: "jspdf" */ 'jspdf').then(module => {
    const jsPDF = module.default;
    return new jsPDF({
     ....
    });
  });
```
This is a way to reduce the bundle size. I can look more into this, there are other vendor dependencies that could be split into chunks ... 

![image](https://user-images.githubusercontent.com/33061427/106242375-e028de80-6207-11eb-8b8d-133801fbabc7.png)

**Comment by jokd** [comment]
Closed due to inactivity
