### ISSUE TITLE
Don't show empty attributes for geopackage source

### ISSUE THREAD

**Issue by johnnyblasta** [origo-map/origo#1103]
**Is your feature request related to a problem? Please describe.**
Some layers may have lots of attributes where only some are set on certain features and other are set on other features .

**Describe the solution you'd like**
There should be able to set on the layer that attributes which are null or empty aren't to be shown in the feaureinfowindow

Feature with lots of null values:
![image](https://user-images.githubusercontent.com/48793206/104921873-3725ec80-599a-11eb-8af6-4465392d6f63.png)
Same feature with only values that is set:
![image](https://user-images.githubusercontent.com/48793206/104922045-748a7a00-599a-11eb-8186-f389628138b8.png)

**Comment by jokd** [comment]
Surprised to see that behaviour, or differs infowindow from the overlay/sidebar? The latter I think behaves as wished.

**Comment by johnnyblasta** [comment]
> Surprised to see that behaviour, or differs infowindow from the overlay/sidebar? The latter I think behaves as wished.

No, it looks the same for me on overlay/sidebar with lots of null. Perhaps it's a difference with system setup.

**Comment by jokd** [comment]
Are you fixing it?

**Comment by johnnyblasta** [comment]
> Are you fixing it?

I have a fix that works as seen on the images above.
It seems to be related to Geopackage, since this layer is from a Geopackage surce.
