### ISSUE TITLE
Layer can't be turned off

### ISSUE THREAD

**Issue by johnnyblasta** [origo-map/origo#1117]
**Describe the bug**
When clicking on button to turn off layer nothing happens

**To Reproduce**
![BugLegend](https://user-images.githubusercontent.com/48793206/105342207-6332af00-5be0-11eb-82f0-ada34d68beab.gif)

Bug possible introduced in #1086

**Comment by tonnyandersson** [comment]
I think this only affects layers in the legend root, not layers in a group.

**Comment by johnnyblasta** [comment]
> I think this only affects layers in the legend root, not layers in a group.

Yes, it works on layers in group.

**Comment by jokd** [comment]
That can't be right!
