### ISSUE TITLE
Click does not register on SVG-icons in Edge

### ISSUE THREAD

**Issue by Lund-gren** [origo-map/origo#112]
For example when clicking a SVG-icon it doesn't register as a click (nothing happens), however clicking the button works. I've only noticed this problem in Edge.

**Comment by afogelberg** [comment]
I think #102 have solved this. Can you verify this @Lund-gren ?

**Comment by Lund-gren** [comment]
No #102 did not solve this

**Comment by afogelberg** [comment]
It seem to be related the problem as reported here: https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/7998724/

**Comment by afogelberg** [comment]
@Lund-gren the problem should be fixed by #120 . Can you verify that it works?

**Comment by Lund-gren** [comment]
Yes #120 fixed it
