### ISSUE TITLE
Ghost lables in measure control

### ISSUE THREAD

**Issue by johnnyblasta** [origo-map/origo#1120]
**Describe the bug**
When clearing the measures made the labels of segments isn't cleared and left on map. The labels disappears when closing control.

**To Reproduce**
![GhostLabels](https://user-images.githubusercontent.com/48793206/105364397-6a1bea80-5bfd-11eb-9b1d-0749cc63cbe0.gif)

**Expected behavior**
The labels should also be cleared.

**Comment by jokd** [comment]
Looks like the ghost labels are still there according to comments in #1122
