### ISSUE TITLE
Configurable to not use hectare in measuring areas

### ISSUE THREAD

**Issue by johnnyblasta** [origo-map/origo#1123]
**Is your feature request related to a problem? Please describe.**
The area measure tool switches to hectare when the area is above 10000 m2 and below 1000000 m2. There should be a config option to be able to use square meters, since this is dependent on what is used in the business.

**Describe the solution you'd like**
In options for the measure control there should be a alternative
`"useHectare": false`

**Comment by jokd** [comment]
I suggest we also add soccer fields as unit of measure. Seems to be the most commonly used unit. Not sure how accurate it is though.

**Comment by johnnyblasta** [comment]
> I suggest we also add soccer fields as unit of measure. Seems to be the most commonly used unit. Not sure how accurate it is though.

Since soccer fields don't have a officially determined size and therefore varies I take this as joke although no smile in the comment :)

**Comment by jokd** [comment]
You are right, but if we use the measurement of the iconic Stora Valla in Degerfors we would probably be as average as possible.

**Comment by johnnyblasta** [comment]
Better to do it selectable, since I want to use Idrottparken in Sundsvall as reference.

**Comment by tonnyandersson** [comment]
Perhaps a better idea would be to add the option to set breakpoints and units manually? That way everyone can use their own preferred units, may it be soccer fields, American football fields, aircraft carriers or whatever.

**Comment by jokd** [comment]
I can go either way. Feel that soccer fields would be an USP for Origo though.
