### ISSUE TITLE
Infowindow diffuse text and bullets lag

### ISSUE THREAD

**Issue by mulfvik** [origo-map/origo#1136]
**Describe the bug**
- Infowindows content and bullets is diffuse, content has an undefined class. 
- When click next/prev new bullet lags after content text.
![bullets](https://user-images.githubusercontent.com/24228538/105948952-2e08df80-606c-11eb-9757-98c680796822.gif)

**Expected behavior**
Text and bullets should be crisp and no lag on shifting bullet. 

**Desktop (please complete the following information):**
The diffuse style is only in Chrom.
The lagging bullets in Chrome, Edge, Firefox, IE

**Comment by jokd** [comment]
You are short on time, mr Ulfvik
