### ISSUE TITLE
Error message sass class changed during clean up 

### ISSUE THREAD

**Issue by mulfvik** [origo-map/origo#1138]
_Originally posted by @mulfvik in https://github.com/origo-map/origo/issues/1079#issuecomment-760927920_

**Comment by mulfvik** [comment]
Validate editform does not work as espected due to searchList

**Comment by daRasmussen** [comment]
@mulfvik I worked on validation in editform when I did the searchList, maybe this error is due to a too fast clean up. More info will come soon.
