### ISSUE TITLE
Measure control requires position control to work in touch mode

### ISSUE THREAD

**Issue by jokd** [origo-map/origo#1144]
**Describe the bug**
When measuring on touch devices, the position control is used. However if this control is not activated, and added before the measure control in the config, measuring on touch devices is a no-go.

**To Reproduce**
1. Remove the position control or place it after the measure in the config
2. Try measuring on a touch device
3. The crosshair and the plus-button will not appear

**Expected behavior**
Either add the position control as a dependency or fall back to the old behaviour (opinions on that?)

**Smartphone (please complete the following information):**
 - OS: iOS
 - Browser Safari

**Comment by tonnyandersson** [comment]
I think the touch mode feature is quite nice, so I don't think it would be a good idea to go back to the ways of yore.

Please correct me if I'm wrong here, but I don't think the measure actually _needs_ the position control. It looks like the measure control only uses the position control to add the crosshairs to the center of the map. I believe the measure control could be perfectly capable of finding the center of the map on its own.

So, if the position contol is _not_ available, the crosshairs could be added from the measure control. But if the position control _is_ available, the measure control could use its properties to add the crosshairs and take advantage of the center point coordinates shown by the position control. Or something.
