### ISSUE TITLE
Print - Highest scales cannot be printed in high resolution

### ISSUE THREAD

**Issue by MattiasSp** [origo-map/origo#1167]
When selecting to print in high resolution (300 dpi) and using the highest (most zoomed in) scale, the map does not change to the correct scale.

**To Reproduce**
1. Open the print control
2. Open the print settings
3. Choose high resolution (300 dpi)
4. Select the most zoomed in scale
5. The map scale is not what was just selected

Another path could be to provide a print scale in the print control's `scales` option that is below the minimum resolution in the maps `resolutions` config option.

**Expected behavior**
Any selectable scale should be possible to use for printing.

**Screenshots**
![image](https://user-images.githubusercontent.com/2445979/108229403-150dbe80-7140-11eb-810b-d9d2047ae927.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Version 87

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy S6
 - OS: Android 7.0
 - Browser: Chrome
 - Version: 88

**Additional context**

After going down the rabbit hole, I have concluded that when an OpenLayers map view object is initialized, it creates a [`resolutionConstraint`](https://github.com/openlayers/openlayers/blob/65df12068b47d6dcf1c43813f9ceb219bd5c5710/src/ol/View.js#L1862) which restricts the map's resolution (pixels per map units) to the minimum and maximum resolution that is was initalized with.

These resolutions are [converted to map scales in origo](https://github.com/haninge-geodata/origo/blob/994e72bb3ccca71728de686916afd2bd62ff1b94/src/maputils.js#L109), assuming a DPI of approx. 90.7.

When the DPI is increased, the effective _resolution_ will decrease proportionately (as each pixel will now represent a smaller map distance).

This means that increasing the DPI from e.g. 150 to 300 DPI cuts the requested map resolution value in half, which for the most zoomed in scale(s) means that the requested resolution will be lower than what is allowed by the above mentioned resolution constraints.

I believe there might be ways to deactivate/ignore the map view's resolution constraints, but I'm not sure how yet. That's as far as I've gotten for now.

**Comment by Grammostola** [comment]
Well investigated. I'm not sure how to disable a View's resolution constraint either.

A tangent: if constrainResolution: true is set for the map (to zoom-snap to its defined resolutions) it becomes very hard to use any selectable scale for printing.

**Comment by MattiasSp** [comment]
I have an idea on how to fix this without meddling with the view and constraints. I'm thinking that might introduce more complexity and lead to difficult-to-guess behavior down the line.

Instead, maybe we could let the print control calculate which resolutions would be required to print all available scales at the available DPI:s? And temporarily replace the map's `resolutions` with those? Then, when closing the print control, the `resolutions` could be re-read from the config.

This would, I think, have the least impact on general map behavior and be limited to the print control. It would also fix both this specific issue and the related bug described in [Grammostola's comment](https://github.com/origo-map/origo/issues/1167#issuecomment-780704310).

One drawback I see is that this would allow users to, in effect, zoom past the lowest resolution specified in the config, which might not always be expected or desired.

Feedback would be much appreciated!

**Comment by johnnyblasta** [comment]
Sounds like a reasonable solution.
A config variable could be added specifying that no recalculation should be done in the case that the map owner wants to forbid it for some reason.

**Comment by steff-o** [comment]
Any progress on this one?

**Comment by steff-o** [comment]
I believe that this is closed by #1327, but I don't have the powers to close it.

**Comment by jokd** [comment]
@MattiasSp Can we close this?

**Comment by jokd** [comment]
This issue seems to be no more, closed!
