### ISSUE TITLE
Layer check-icon on backgroundmaps is not removed

### ISSUE THREAD

**Issue by Lund-gren** [origo-map/origo#117]
The check-icon is not removed on background-layer that has been turn off once it have been turned on. 

![image](https://cloud.githubusercontent.com/assets/15904460/19634663/35cf0b2e-99bd-11e6-8778-cf9069981b27.png)

**Comment by afogelberg** [comment]
Fixed with 7e2b678c50892d2d9c37b2fc94dbeb0e13fba59e
