### ISSUE TITLE
Bookmarks control

### ISSUE THREAD

**Issue by tonnyandersson** [origo-map/origo#1171]
A bookmarks control could be useful. Essentially a list of pre-configured named "views", i.e. a list of preset center coordinates.

A dropdown list with presets is probably what first comes to mind. This is, however, not really an optimal solution since the UI has become quite crowded, especially on smartphones.

Instead, I suggest a different approach, with a detached, movable list element. Neatly tucked away when not in use, but only a click away when needed.

![bookmarks](https://user-images.githubusercontent.com/15725608/109144747-dab8a880-7761-11eb-95e2-cb02ee41236d.gif)

**Comment by jokd** [comment]
Agree, really useful. Can this control be reused to do something similar with a collection of layers?
Will the draggable panel be available in ui?

**Comment by tonnyandersson** [comment]
It would take a few minor tweaks, but sure, I think it could be used with layers as well. However, that could also be accomplished with a _Zoom To Extent_ button in the legend (if that's the gist of your suggestion). But for just a few selected layers in a compact application, perhaps this approach is preferred. Depends on the "why", I guess.

The draggable panel is not available in the ui right now. But I did have an idea of making some sort of reusable context menu panel thing out of it. Not quite done with the thinking there, though. Suggestions are welcome.

**Comment by jokd** [comment]
That draggable panel is also used in the infowindow control, would be nice if theyshared code and can be reused for other stuff as well.
With layers I actually meant an action that rerenders the map/legend with a new collection of layers, some visible some not. Think of it as a kartserie if you know what I mean...

**Comment by tonnyandersson** [comment]
Oh, I know what you mean. Well, I can't see why not. It's a list of clickable items. Those items could, potentially, be configured any way you want. Now it just takes coordinates and zoom level from the configured control options and pass them to a `fit()` function. So, you could easily pass a list of layers instead and do... whatever the heck you want with them. The possibilities are endless!

I did actually steal the draggable stuff from the infowindow control. It didn't work very well, though, so I had to tweak it a bit. But I was planning on changing the `makeStuffDraggable` function into a util, available for any element to enjoy. But maybe a ready-made panel component for this purpose is the way to go.

**Comment by jokd** [comment]
I believe in your judgement regarding util vs component.
Looking forward for the PR!
