### ISSUE TITLE
Image upload in editor does not work as expected

### ISSUE THREAD

**Issue by jaha7** [origo-map/origo#1174]
**Describe the bug**
Attribute option "image" not working in editor, Ok btn get unresponsive, style not drawn etc.

**To Reproduce**
1. Use "image" in editor attributes.
2. Enable editor and draw a object.
![editor-image-probs](https://user-images.githubusercontent.com/47249045/109278394-c5eb1c00-7818-11eb-93c3-1bfe8ae0e405.gif)

**Screenshot from DevTools**
![editor-image-probs](https://user-images.githubusercontent.com/47249045/109278098-6e4cb080-7818-11eb-8efc-7f1dcaad459c.png)

**Desktop:**
 - OS: Windows 10
 - Browser Edge (Chromium)
 - Version 88.0.705.81 (Officiell version) (64 bitar)
**Smartphone:**
 - Device: Google Pixel 4a
 - OS: Android 11
 - Browser Chrome 
 - Version 88.0.4324.181

**Comment by tonnyandersson** [comment]
Thanks for the input, @jaha7. We'll look into it.
