### ISSUE TITLE
Add authorization url option as config option

### ISSUE THREAD

**Issue by afogelberg** [origo-map/origo#121]
WIth PR #119 we can add config options to map.init. I suggest we add an config option for an authorization url, authorizationUrl, that can be used for simple cases of login. The url could for example be an endpoint to GeoServer that triggers authorization. After authorization the map is initiated.

Any thoughts on this @jokd @markus659 ?

**Comment by jokd** [comment]
@fogelberg Sounds like a nice improvement. We are using the Geoserver authorization today so it is definitely useful for us.

**Comment by markus659** [comment]
Sounds like a good idea to have a simple login option available.

**Comment by jokd** [comment]
@fogelberg Sounds like a nice improvement. We are using the Geoserver authorization today so it is definitely useful for us.

**Comment by afogelberg** [comment]
Fixed with ad87641
