### ISSUE TITLE
Drawtools not working

### ISSUE THREAD

**Issue by steff-o** [origo-map/origo#1210]
In master as of 2021-03-24

After the removal of jquery dependencies drawtools does not work anymore. There are several issues. 

Drawtool.js line 66: Trying to index zero length array.

Drawtool.js line 84: Adds a body element to DOM.

Editdispatcher.js line 2: The event has no name.

Edithandler.js line 313: Shape name is in e.detail.shape, not e.shape

I can fix it in a PR.

**Comment by jokd** [comment]
Are you using latest version of the plugin as well?

**Comment by steff-o** [comment]
Not using any plugin. It's the built in edit extra tools.

**Comment by jokd** [comment]
Ok I see then a PR is very welcomed.
