### ISSUE TITLE
Carousel jumping on touch devices

### ISSUE THREAD

**Issue by jokd** [origo-map/origo#1216]
**Describe the bug**
When multiple objects are clicked and the carousel is activated, on touch devices clicking next will jump to the third, fifth etc. object. This is due to animationDuration set to 0 to solve issue #1170. Increasing it will fix this, the bug can also be seen here: https://glidejs.com/docs/options/#animationduration

**Comment by mulfvik** [comment]
This could fix the slowness of animation..
`animationTimingFunc: '0.25s cubic-bezier(0,0,1,.99)'`

**Comment by mulfvik** [comment]
Somewhat hectic comment there, sorry. I'll create an issue an pr on this. Not a big deal this but if losing oneself in that delayd animation it can bust up the mind
