### ISSUE TITLE
Need a copy tool

### ISSUE THREAD

**Issue by steff-o** [origo-map/origo#1223]
**Is your feature request related to a problem? Please describe.**
It should be easier to copy a geometry from another layer when editing. Today you have to draw it manually and use snapping. This function would be useful for drag-and-drop layers to enable users to add features to a layer from external sources. It can also be useful for creating new features in one layer from an existing feature in another layer, e.g. create a contract that covers a land parcel.

**Describe the solution you'd like**
There should be a copy tool in the editor menu that can copy a geometry from another layer, including drag-and-drop layers.

**Describe alternatives you've considered**
Create an external function that posts an event to the editstore to make a new feature, but that can't utilize a lot of the sweet attribute functions in edithandler and would not be consistent with other edit operations for the user.

Create a server side function that makes a copy in the database, but that is too application specific.

_I have written a copy tool that integrates with the edit toolbar. Soon to appear in a PR if approved_

**Comment by jokd** [comment]
This will be a great addition to the editor so you are welcome to submit a PR.
