### ISSUE TITLE
Search hits could have a choice of infowindow: type

### ISSUE THREAD

**Issue by Grammostola** [origo-map/origo#1228]
**Is your feature request related to a problem? Please describe.**
Search hits* today display an info popup 'overlay' 

**Describe the solution you'd like**
Search hit infos could be displayed in the infowindow: that the map is set to

**Describe alternatives you've considered**
Search hit infos could be displayed according to a parameter for the search control in index.json

**Additional context**
We are currently working with internal maps employing infowindow:infowindow and have received feedback noting the inconsistency between overlay when clicking search hits and iw:iw when infoclicking/selecting

*employing the standard search control

**Comment by jokd** [comment]
@Grammostola Will this be fixed this week or the next?

**Comment by Grammostola** [comment]
@jokd Last sunday?
Is it something that has seen recent interest?

**Comment by jokd** [comment]
Sunday’s fine
Jokes aside, I aim to have a go at it if you won’t. Makes sense to have this feature.
