### ISSUE TITLE
Add headers to layer requests

### ISSUE THREAD

**Issue by johnnyblasta** [origo-map/origo#1233]
**Is your feature request related to a problem? Please describe.**
When using a GeoJSON from a API as a layer there can be the case that you need to send a header for example to get the right format in the response.

**Describe the solution you'd like**
There should be possible to specifiy in the layer config headers that should be sent in the request.
Example:
`"headers": { "Accept": "application/geo+json" }`

**Describe alternatives you've considered**
Are there a need for other layer types to be able to set headers?

**Comment by jokd** [comment]
Nice enhancement. If/when needed this option can be copied to other layer types as well.
