### ISSUE TITLE
hideWhenEmbedded for plugins(?)

### ISSUE THREAD

**Issue by Grammostola** [origo-map/origo#1239]
**Is your feature request related to a problem? Please describe.**
Controls have a hideWhenEmbedded param that can be specified in index.json, I've not seen that plugins have the same possibility

**Describe the solution you'd like**
Would be good if plugins (that introduce a UI element) could have a similar property

**Describe alternatives you've considered**
There is a possibility that I've missed something

**Comment by Grammostola** [comment]
A relatively simple and effective method is one our Sweco contact thought up in a flash:
https://github.com/sweco-sefaed/EK-extern/commit/bd161be9b718b5168781bd546a06da60fc8cb364 
which is to say Let the viewer expose the isEmbedded property, this way a plugin initiated in index.html can be added to the viewer if the viewer isn't deemed to be embedded.

**Comment by jokd** [comment]
Sure thing but why negate it?
