### ISSUE TITLE
setStroke method missing from build-ol-standard and build-ol-embed

### ISSUE THREAD

**Issue by markus659** [origo-map/origo#124]
The setStroke method seems to be missing from build-ol-standard.js. I noticed this in our version of Origo. When running  

```
npm run build-ol
```
and then running 

```
npm run build
```

 I get an error in the console saying "e.text.setStroke is not a function" when loading the map.

Adding 
```json
"ol.style.Text#setStroke"
```
 to the json file solves this. I guess this should be added to the embed configuration as well.

Maybe this is just a problem with our version?

**Comment by afogelberg** [comment]
Fixed with 986c7d815ba6cc6521c1a66a841990ef9591dd5b
