### ISSUE TITLE
New style for arrows in image carousel

### ISSUE THREAD

**Issue by johnnyblasta** [origo-map/origo#1247]
**Is your feature request related to a problem? Please describe.**
The style of pagination for images in the carousel is the same as that for multiple features which can be confusing.

**Describe the solution you'd like**
The style for arrows and bullets should be changed for the image carousel.

**Describe alternatives you've considered**
The arrows should be moved up to be contained within the image and not below as it is now.

**Comment by tonnyandersson** [comment]
Got two design suggestions:

1. Rounded arrow buttons, flat bullets
2.

**Comment by tonnyandersson** [comment]
Got two design suggestions:

1. Round arrow buttons, flat bullets:
![image](https://user-images.githubusercontent.com/15725608/116680960-9d180c00-a9ac-11eb-846b-b46aa23b2df1.png)

2. Square arrow buttons with slightly rounded edges, flat bullets:
![image](https://user-images.githubusercontent.com/15725608/116681111-d3558b80-a9ac-11eb-9dd3-25808bb51024.png)

Any preferences?

**Comment by johnnyblasta** [comment]
All nice, but I prefer the round ones and can't decide if I prefer the light or dark background.

**Comment by asemoller** [comment]
I like number 4 (the last image)! It's grey and round just like the rest in Origo :).

**Comment by asemoller** [comment]
Do we really need both arrows and bullets? Why not just use arrows for images?

**Comment by tonnyandersson** [comment]
I thought about that too, but I guess some users like to know if there's one, three or hundreds of slides. We could solve that by adding a subtle _x/xxx_ label in one of the corners, but that would require some changes to the GlideJS library. Bullets are included there, labels are not, as far as I know.

Personally, however, I think I could live without the bullets.

**Comment by asemoller** [comment]
ok, good point @tonnyandersson! Let's go with bullets for now, it looks good :)!

**Comment by jokd** [comment]
+1 for no4
