### ISSUE TITLE
Page refresh by accident

### ISSUE THREAD

**Issue by mulfvik** [origo-map/origo#1252]
When a modal is open and you accidentally drag outside the modal vertically (top to bottom), the page reloads. If youre almost finished with a form and this happens cause you wants to scroll down a bit it can be a bit frustrating.

So, page refresh should not interfere with UI

**Comment by johnnyblasta** [comment]
@mulfvik I tried with a editor modal and couldn't make the page to refresh. 
Am I missing something? Is it a specific web browser that this happens?

**Comment by mulfvik** [comment]
@johnnyblasta Sorry for the lack of info, the issue-template is there for a reason apparently ;) 
I am using a Samsung Galaxy S10e.
Tested with the editor config in examples folder and the page refreshes on Chrome 90.0.4430.210, Samsungs Internet browser and DuckDuckGo. On Firefox it is all good.

I put the [overscroll-behavior-y](https://developer.mozilla.org/en-US/docs/Web/CSS/overscroll-behavior-y) on the body because I cant see any situation when we want that behavior but thats up for discussion. 
This solution does not cover Safari so anybody got an iphone?
