### ISSUE TITLE
Emit an event when features are selected in featureinfo

### ISSUE THREAD

**Issue by steff-o** [origo-map/origo#1256]
**Is your feature request related to a problem? Please describe.**
When using a table view of features linked to features in the map there must be a way of getting notified when an object is selected in the map to highlight the row in the table. Also going the other way it should be possible to programatically show the featureinfo dialog (overlay, side bar or infowindow). It is possible to acheive this today, but it relies on implemetation specific details i origo. Also there are a few bugs involved in featureinfo.

**Describe the solution you'd like**
I would like to have an event sent from featureinfo when a feature is selected, regardless of if it is selected using overlay, sidebar, infowindow or selecting in a carousel. The event should contain at least the feature id (of the original feature, not uid of a clone) and name of the layer, so the original feature and layer can be identified.

Also an api on featureinfo to create a info dialog containing a list of features.

**Describe alternatives you've considered**
For overlay and sidebar there used to be an event sent when a feature was selected, but after a rewrite it is only sent when changing feature in a carousel. To overcome that I can listen to a _change_ event on the selection layer source. Problem is that then there is no information about layer name unless the original feature has a property _name_. So I can set that when features are loaded. But when using carousel, the layerName propery is taken from the _SelectedItem.name_, which is empty when populated from map click. So combining the _toggleFeatureinfo_ event for carousel and _change_ on source fixes overlay and sidebar.

For info window it is possible to listen to _changefeature_ on each layer as Selectionmanager set and unsets the property _state_ on selection. When that event is triggered I can query the selectionmanager for selected items for those layers I am interested in. Unfortunately there is a bug in SelectionMangager that causes unset to not trigger the _changefeature_ event, so I have to listen to map _click_ to clear the selection.

When going the other way it is possible to show the featureinfo dialog by using the Render-function, but it does not seem like a stable api.

So it is possible to achive, but it's cumbersome and relies on implementation specific details that can change.

**Additional context**

**Comment by jokd** [comment]
That would be a great addition. For the selectionmanager I have done it like this:
	  viewer.getSelectionManager().createSelectionGroup('layer name', 'layer title'); // Must be a selectionGroup to add event listener
	  viewer.getSelectionManager().getUrval().get('layer name').getSourceLayer().on('change', function(){
	  doSomething(this)});
      });

Would really like to do this a bit nicer.

**Comment by jokd** [comment]
@steff-o Is #1276 useful to you and something to build upon?

**Comment by steff-o** [comment]
I'll have look at it later. It would be nice if the application can use the same event regardless of which type of infowindow (overlay, sidebar etc) is used. Maybe featureInfo can listen on selection manager and emit a uniform event.

**Comment by jokd** [comment]
I agree, it would be cool if the selection manager managed selections ;)

**Comment by jokd** [comment]
@steff-o Have you done any progress on this?

**Comment by steff-o** [comment]
@jokd No. The workaround described in the issue has worked so far. I'll have look at #1310 if @tablackmore's changes solves parts of it.

**Comment by steff-o** [comment]
#1311 seems to solve one of the problems. When that is merged I can continue with the rest without interfering.

#1276 Is not really what I am looking for, as it deals more with seleced objects than highlighted objects. But there is probably need for both in general. I depends on how the selectionmanager is used.

Also there are two bugs that probably should be fixed while at it even though they probably don't matter to anyone:
- in featureinfo: when a clone is made to the selection layer, I guess that the name of the layer should be copied to the property "layerName", but is taken from the property "name" from the feature itself. Probably a remnant from before SelectedItem was used. The result is that it is impossible to figure out which layer a feature comes from in the selection layer.
- in SelectionManager: when a feature is un-highlighted the unset() call has two argumnets, which supresses the _change_ event.
