### ISSUE TITLE
Set transparency on layer

### ISSUE THREAD

**Issue by afogelberg** [origo-map/origo#127]
Option for user to set transparency on layer.

**Comment by jokd** [comment]
I woudl like to develop this feature. Any ideas for an intuitive and mobile-friendly solution to this? Right click doesn't work well on iPhone ;-)

**Comment by afogelberg** [comment]
Great! I would say that we shouldn't add more layer buttons, besides the already existing i-button. How about extending the i-button? We could use the i-button to extend it with other layer settings and info as well: complete legend image, abstract, transparency etc.

**Comment by jokd** [comment]
Guess I will have to do it then =)
