### ISSUE TITLE
Default values for editor

### ISSUE THREAD

**Issue by johnnyblasta** [origo-map/origo#1273]
**Is your feature request related to a problem? Please describe.**
It would be useful to specify a default value for attributes, so it would take less time to fill in form if there are attributes that almost always is a certain value.

**Describe the solution you'd like**
A field in the config that contains the default value and it will be prefilled on a new feature.

**Describe alternatives you've considered**
How should the case when an existing feature thats been imported but misses the attribute be handle? If the default value is prefilled it would look like it exists already, but actually don't. Something should distinguish that it's a temporary value or don't be filled in at all.

**Comment by jokd** [comment]
Solved in #1509
