### ISSUE TITLE
The animation for the infowindow doesn't work

### ISSUE THREAD

**Issue by asemoller** [origo-map/origo#1279]
**Describe the bug**
The animation for the info window "overlay" doesn't work if it's close to the top of the browser window. It's works fine when clicking on an object close to the left or right. It has worked in previous versions.

**To Reproduce**
1. Click on an object close to the top of the window.
2. The info window hides

**Expected behavior**
The info window should be adjusted so it can be readable.

**Desktop (please complete the following information):**
 Only tested on desktop/chrome.

![animation_infowindow](https://user-images.githubusercontent.com/17123002/119782173-23e8d780-becc-11eb-9e23-7dea2e86298e.gif)

**Comment by johnnyblasta** [comment]
I know what caused this, but don't know how to fix it without introduce a new bug.

In featureinfo.js move theese 2 rows from row 296-297 to below 259
```
        const popupHeight = document.querySelector('.o-popup').offsetHeight + 10;
        popupEl.style.height = `${popupHeight}px`;
```
This fixes the animation, but introduces a bug when a carousel is present which can cause the size of the popup will be larger than it actual is and causes a area that can not be clicked above the popup.

**Comment by jokd** [comment]
What if you set it twice?

**Comment by johnnyblasta** [comment]
> What if you set it twice?

It solves the problem with the area above popup isn't clickable. 
But since the height for the overlay is the same as before the animation scrolls down too much.
