### ISSUE TITLE
Get allowed editor attribute values from service

### ISSUE THREAD

**Issue by steff-o** [origo-map/origo#1295]
**Is your feature request related to a problem? Please describe.**
Creating  configuration for allowed values on an attribute requires hard coding them in index.json, which often means copying values from a database table by hand.

**Describe the solution you'd like**
A configuration option for attribute editor types _dropdown_ and _searchList_ with an URL to a service that returns a list of allowed values.

**Describe alternatives you've considered**
Add the list of allowed values programatically to index.json server side.  But that must be implemented for each application. Even with a reusable server side library it adds complexity to a an otherwise configure driven SPA and would be harder to share with the community.

**Comment by johnnyblasta** [comment]
To be really useful there should be a easy way to edit the values I guess. Are you thinking of using existing values from tables in some map database? If it is some new table or file on a server it might not be as useful, since it only moves the config to some other place that has to be managed.

**Comment by steff-o** [comment]
The idea is to keep value codes consistent between different applications accessing the same data. The list of valid values would then be shared among all clients. Depending on the application the list of values may already exist. 

As far as I know there is no data validation in WFS, so each application developer has to provide for that. . Even if wfs has a validiation it would  be triggered too late. It would be cool if WFS describeFeatureType could provide this information (maybe it can?) so the origo application can get it from there instead of having a special endpoint for that. But then it would probably be hard to configure the WFS to fetch that information from the database, and it would still require manual configuration.

Another usage would be using a searchList that suggests already existing values to avoid misspelling and almost duplicates ('parkbänk', 'park bänk') . Then the service endpoint would just do a DISTINCT query on that attribute. But the user would still be able to add a value even if it is not present in the serachList.

I agree that if it just moves configuration to another place it is not that useful. Then the only merit would be that the application itself does not have to be configured and deployed, it could be done by just a adding a database row.

**Comment by steff-o** [comment]
This issue has not gained any attention lately. Closing for now. (Still think it's a good idea though)
