### ISSUE TITLE
Add objects with images

### ISSUE THREAD

**Issue by mulfvik** [origo-map/origo#1296]
**Describe the bug**
When, in the editor, I add an image on more than one object there is an error of undefined undefined. This is if its the same session. When reloading the page I can add one more object with an image.

**To Reproduce**
Add a editable layer that has image as one attribute. Add object with an image, save, add one more object with image and try to save.

**Expected behavior**
Adding multiple objects that has images as attributes.

**Desktop (please complete the following information):**
 - Windows10
 - Chrome, Firefox

**Smartphone (please complete the following information):**
 - Iphone, Samsung
 - Android, iOS
 - Chrome, Safari, Firefox, Samsung internal

**Backend**
 - QGIS-server, PostGIS

**Comment by mulfvik** [comment]
Please confirm this on other backend if possible, cheers

**Comment by mulfvik** [comment]
@johnnyblasta Probably the same issue but in this repo https://github.com/origo-map/dialogue-plugin/issues/5 
Up to fix this aswell?

**Comment by johnnyblasta** [comment]
> @johnnyblasta Probably the same issue but in this repo [origo-map/dialogue-plugin#5](https://github.com/origo-map/dialogue-plugin/issues/5) Up to fix this aswell?

I used code from this repo to fix the bug in dialogue-plugin so I probably introduced this bug there.

**Comment by mulfvik** [comment]
No issue no more so I close this
