### ISSUE TITLE
Close Bookmarks popup on click

### ISSUE THREAD

**Issue by MattiasSp** [origo-map/origo#1300]
On small screens, a long list of bookmarks tends to hide a large portion of the map as well as the zoom animation when clicking on a bookmarked location.

A config option to hide the bookmarks popup automatically when the user clicks on a bookmark link would be easy and elegant. If the auto-close behaviour could be dynamic so that it is only active on smaller screens would be even better.

**Alternatives considered**
- Always auto-close
  - Changes current behaviour
  - Less flexible
  - More tedious for users on big screens to step between bookmarks

**Comment by MattiasSp** [comment]
PR incoming.

**Comment by tonnyandersson** [comment]
How about making it even more flexible? I mean, what if someone actually wants it to always auto-close?

I'm thinking a handful of scenarios could be handled. Like:

1. Never auto-close, regardless of screen size (`"autoClose": false` - default)
2. Always auto-close, regardless of screen size (`"autoClose": true`)
3. Auto-close on small screens only (`"autoClose": "small"` - applies to sizes "m" and smaller)
4. Auto-close on large screens only (`"autoClose": "large"` - applies to sizes "l" or maybe "m" and larger)
5. Auto-close on custom screen size (`"autoClose": ["xs", "s", "l"]` - applies to the specified sizes)

Perhaps a bit over the top in terms of flexibility, but I think it might be worth to consider it. Pros and cons can be discussed.

**Comment by jokd** [comment]
@tonnyandersson Do you want to add this functionality or shall I merge the PR?

**Comment by tonnyandersson** [comment]
Nah, merge it and let the users decide if it's flexible enough or not.
