### ISSUE TITLE
toggleFeatureinfo event is no longer triggered correctly

### ISSUE THREAD

**Issue by tablackmore** [origo-map/origo#1310]
**Describe the bug**
When selecting a feature the toggleFeatureinfo event is not triggered unless you are on the second page of a carousel and it is then triggered after every click on the carousel div.

**To Reproduce**
1. Activate the dialog plugin example with voting
2a. Click on an object, no voting button will be displayed.

2b. Click on a stacked object, and then use the carousell button to move to the next object.
3b. The voting button will be displayed but you will be unable to trigger a click event on it.

**Expected behavior**
The voting button should be displayed with all object selections when active.
The voting button should be clickable.

**Additional context**
Fix on it's way. Based on "move" event in glidejs is the wrong event to wire upto "run.after" event is more appropriate.

**Comment by steff-o** [comment]
Also mentioned in #1256. This would probably fix part of that.
