### ISSUE TITLE
Add attachments i editor

### ISSUE THREAD

**Issue by steff-o** [origo-map/origo#1314]
**Is your feature request related to a problem? Please describe.**
Currently there is no support for uploading arbitrary attachments in the editor. FeatureInfo can however display links to attachments or emedd images from links. But creating the attribute must be done either manually as a text attribute, or using another application/custom dialogs.

**Describe the solution you'd like**
In the editor I would like to have an attribute type for attachments. When editing it would be possible to add and remove attachments. When adding an attachment a file picker should open and after selecting a file it should be uploaded to the server and stored as an attachment It should be possible to add any number of attachments of any type of file.

In featureInfo all attachments should be displayed as clickable links and make the bowser decide what to do using the mime type. If the attachment is an image it should be possible to display it as todays _img _ option.

**Describe alternatives you've considered**
For images there already is an attribute type for uplading images, but that is limited to one image per attribute and stores the image as a base64 string in the feature itself, which is very bad for WFS performance. Displaying the image in feature info would be possible using the _urlPrefix_ attribute to set src to _data_/image/jpg;base64_ or appropriate mime type. To support general attchments a more complex expression must be used to turn the embedded attachment into a clickable link. That could possibly be accomplished using the _html_ option, but that would be tedious work for application developers and error prone.

FeatureInfo has an (undocumented) option to split an attribute by a separator character to create multiple links or images from one attribute, however that still requires some way of actually uploading files and link them to the feature.

All of this could be implemented outside origo using various techniquies, e.g by using the html option for display and custom dialogs for uploading, but that's once again tedious and error prone.

**Additional context**
As WFS is not really suited for embedding large binary objects as attributes and to support any number of attachments without having to resort to use a delimeter or xml/json datatype I suggest implementing the feature using an attachments REST service. The rest endpoint should support
- GET on a collection to retreive a list of attachments for a given feature using its private key
- POST on a collection to add a new attachment
- GET on a resource to retreive the actual file
- DELETE on a resource to delete the file

To make use of the attachment service some new options must be added to featureinfo and editor attributes.

The rest endpoint could probably be implemented in origo-server, but to keep it flexible regarding access control and data storage I suggest that the feature is only implemented as an interface dependency in origo. That makes it possible for each organistaion to implement storage as files or database and using different databases and behaviour. 

To avoid out of sync problems that could arise if two services access the same data or when two transactions must be kept in sync I suggest that links are only created on the attachment by storing its parent's private key (FID), just like normal 1-to-many relations in a database. That means that featureinfo must query the attachments service as there will be no attribute on the feature itself.

**Comment by johnnyblasta** [comment]
Spliting a attribute is documented, but since there hasn't been a release since it was added it doesn't show on the documentation on Github.

**Comment by tonnyandersson** [comment]
I think this would be a great addition to Origo. It won't be as _accessible_ as the default image upload function since it would require more backend shenanigans, but it would definitely be more usable, flexible and efficient.

I think a new attribute type - `attachment` - is the way to go. That way pretty much anyone can utilize the option, given that the backend is set up properly. No need for HTML or JS skills. A specific attribute type also provides better control of the implementation, for validity checks and whatnot.

It may also be worth considering using a UUID or something as reference to the attachment, or at least provide the option to do so. Using FID (or equivalent) is great since it means you won't have to add a specific reference attribute on the feature itself. However, I'm not 100% certain FID:s will stay intact through exports/imports from/to different formats/platforms. Just a thought, though, and perhaps a bit overkill in terms of flexibility and generalization.

I also agree regarding backend flexibility. Implementing a REST endpoint in Origo Server is a good idea, but I think it would be cool, if possible, to make the interface compatible with the ArcGIS Server attachment service (and possibly others) out of the box as well.

**Comment by steff-o** [comment]
Looking at the ArcGis Server attachment service I think its pretty similar to what I had in mind. The interface does not has to specify how the relation between the attachment and feature is actually stored, but there has to be a way to indicate which feature an attachment belongs to. 

I used FID as an example as a foreign key to include in the POST request. ArcGis uses the path 
`https://services.myserver.com/ArcGIS/rest/services/SanFrancisco/311Incidents/FeatureServer/0/818654/attachments` where 0 is layer and 818654 is some sort of feature identifier. In the database it is likely that this is also the relationship, but not necessarily. 

In origo we could use the wfs FID, or make it configurable which attribute is used as foreign key when adding a or requesting an attachment. Point is that not to update anything on the feature itself, as the REST service call will be out-of-band for the feature which is updated through WFS (or some other feature server). By separating it like this the attachment itself can be stored on disk or in a database just as long the service can pick it up given a feature id (or some other unique identifier).

Regardless if using FID or any other value it must be unique and special care may have to be taken if it should be allowed to add attachments to newly created features that are not yet saved.

I think that if we're sticking to the general functionality of ArcGis it would be possible to make it configurable to use different formats of URLs and requestobjects and repsonseobjects. Or we could just implement it the ArcGis way from the beginning.

The configuration for an attribute would then be something like this:
``` 
"attributes": [
        {
          "name": "ATTACHMENTS", // Creates a pseudo attribute that contains the links as semicolon separated list
          "title": "Attachments",
          "type": "attachment",
          "foreignKey": "FID" // May be optional if it defaults to FID
          "featureClassId": "0" // May be optional if defaults to layer name
          "allowedExtensions": "jpg,gif,png", // Filter for upload file picker
          "displayAs": "image", // "image" or "link". 
          "attachmentServer": { // May be optional if layer type is arggis server, then its probably same as source
              "url": "https://coollocation.se/attchementservice/",
             "format": "arcgis"
          }
        }
```

We would need some additional configuration that ArcGis does without. As wfs has no way of knowing the actual table a feature comes from and how the attachment service is configured, we need configure both origo and the attachment service with the same featureclassId. Arcgis knows this natively as it is the source. 

The _displayAs_ config may be omitted if it can be inferred from something else, for instance using the existing _img_ and _url_ settings and use the _name_  setting to create a pseudo attribute. 

If the attachment server configuration becomes bigger and is used in many layers it may be a good idea to declare it beforehand and just reference it.

One drawback with the arcgis way is that only supports one set of attachments per table. There is no differentiation between different kinds of attachments. A custom interface could utilize the _name_ setting to group attachments in different (pseudo) attributes.

I agree that it requires pretty hefty backend before it is up and running, but I guess most organizations end up implementing one anyway and have to build some pretty hefty GUI as well. If not, origo server can implement a default service which just stashes everything in one place as the attachments and features does not have to reside in the same database as the attachments can be differentiated by unique _featureClassId_, which is set by configuration. The default implementation could even be file based using folder hierarchy as keys.
