### ISSUE TITLE
Make it more clear that legend has more information to show

### ISSUE THREAD

**Issue by johnnyblasta** [origo-map/origo#1320]
**Is your feature request related to a problem? Please describe.**
It is not obvious for all users that they can click on the layer to see the complete legend for that layer when it contains other than one symbol. It should be made more clear that there is more to see.

**Describe the solution you'd like**
Perhaps it should be some info icon to make it clear that more info is hidden.

**Describe alternatives you've considered**
A popup when hovering over the legend

**Comment by asemoller** [comment]
What about having a "More option"-button (three small points) that is very common? Either vertically or horizontally. When you click on it, it can either display a small menu where you can select things like "Läs lagerinformation", "Zooma till hela lagret", "Exportera lager" or go directly to the layer information.  

I'm not sure where the icon should be placed. Does anyone have a suggestion?

**Comment by jokd** [comment]
@asemoller Good idea. Left of the circle maybe?
![image](https://user-images.githubusercontent.com/6848075/143202341-e966d0c8-52ab-4569-b0ce-df8be293b962.png)

**Comment by jokd** [comment]
Whether to display a menu or slide to the layer information I am not sure. The easiest way is to have all stuff under layer information, but if eg zoom to layer is an often used function it would be smoother to have it in a menu. But I'm dubious about that.

**Comment by asemoller** [comment]
> @asemoller Good idea. Left of the circle maybe? ![image](https://user-images.githubusercontent.com/6848075/143202341-e966d0c8-52ab-4569-b0ce-df8be293b962.png)

Looks good!

But what does it look like if you also have a remove button there as well? And if the layer name contains many characters?

**Comment by jokd** [comment]
In case we go with the menu option the remove layer function could be put there. There's definitely a risk the text will overflow and should be handled some way but that is probably a present problem as well.

**Comment by asemoller** [comment]
Yes, of course it should be put there! 

This is how it looks now if a layer name is very long and have a remove button:

![image](https://user-images.githubusercontent.com/17123002/143208012-788df845-2a6a-4579-af43-d088043842fb.png)

So maybe it will work!

**Comment by asemoller** [comment]
Oh, one thing, the "More Options" button is usually the last button on the right. Maybe like this?

![image](https://user-images.githubusercontent.com/17123002/143213331-02cf68ae-3744-408d-93c0-e9fa1d403e43.png)



I have always found it a bit inconsistent that the arrows for groups and subgroups are on different sides. Maybe the legend needs an overhaul. But I guess that's a antoher issue.

**Comment by tonnyandersson** [comment]
I'm with Team @asemoller here. Putting the buttons on the far right works fine.

**Comment by tonnyandersson** [comment]
It has been noted that some users find it confusing that you need to click on the actual checkbox to toggle layers on/off, instead of just clicking on the layer name/icon. Perhaps that could be addressed in this issue as well, by moving the "Show layer info" function to the "More options" button and including the layer name/icon in the toggle on/off switch.

**Comment by asemoller** [comment]
We'll develop this one!

We'll leave abstract for groups as is and only deal with layers.

**Comment by asemoller** [comment]
This is what the function looks like right now. If "removable": true, a small menu will appear.
Before we send a PR, we need to know how to handle tab navigation as there are problems with the small menu.

![more-option-menu-pr](https://user-images.githubusercontent.com/17123002/149296370-317316d6-1d69-4ef8-a628-720c259bfd78.gif)
