### ISSUE TITLE
Are events a part of the API?

### ISSUE THREAD

**Issue by steff-o** [origo-map/origo#1325]
A lot of the functionality relies on events sent on the global _document_ object. Are those considered to be stable as an API and to be used by plugins and other non-origo code? Or are they just sent on _document_ because that doesn't require implementing a event emitter and should be treated as _private_?

**Comment by jokd** [comment]
Probably the latter because its the easy way. There are many lines of code that could use some rewrites and the event handling is one of those things.

**Comment by steff-o** [comment]
Closing as I got an authoritative answer.
