### ISSUE TITLE
Legend search

### ISSUE THREAD

**Issue by asemoller** [origo-map/origo#1330]
**Is your feature request related to a problem? Please describe.**
With a legend (or layer list) that contains many layers, it can be difficult for the user to find the right layer in the list. It should be possible to search for layers (and groups?) in the legend. 

**Describe the solution you'd like**
One solution is to have a search function in the legend. Another solution could be to improve the search control so that it also includes layers which, when clicked in the results list, make them visible in the map.

**Comment by asemoller** [comment]
@johnnyblasta We´re not working on that right now. Has received questions from several users about that function. I think that would be a very good improvement.

**Comment by johnnyblasta** [comment]
This is as far I had done before getting interrupted:

![SearchLayerInLegend](https://user-images.githubusercontent.com/48793206/133449535-d456bf9b-78e0-4730-859f-1ad4b747329e.gif)

**Comment by johnnyblasta** [comment]
Test with search result above input:
![LegendSearchUp](https://user-images.githubusercontent.com/48793206/135264255-6ee0ee3c-3a21-44ea-a238-2b89fcdfe779.gif)

**Comment by leafisfalling** [comment]
This is a very good and important function that we are longing for. We hope that this function can be in the core as soon as possible. How is this issue going?

**Comment by johnnyblasta** [comment]
> This is a very good and important function that we are longing for. We hope that this function can be in the core as soon as possible. How is this issue going?

I did some testing with visibility/presentation of the search hits a while ago, but didn't came to a result before I got distracted by other work.

**Comment by johnnyblasta** [comment]
This is an attempt to make search hits more visible
![LegendSearchBlack](https://user-images.githubusercontent.com/48793206/140339369-801dd89f-f964-41ed-b2b0-a46e83c1dd9f.gif)
