### ISSUE TITLE
Measure tools always shows marker

### ISSUE THREAD

**Issue by steff-o** [origo-map/origo#1367]
**Describe the bug**
Measure tool always displays the hair cross marker even if not using toucht mode when `"showSegmentLengths": true`. It does not disappear even when measure tool is closed.

**To Reproduce**
1. Configure an application using measure tool and `"showSegmentLengths": true`
2. Start measuring
3. The hair cross appears in the center of the screen
4. Click on measure tool again
5. The hair cross is still there

**Expected behavior**
The hair cross should only be visible when in touch mode. and removed when measuring is finished.

Also I would expect that the measure graphic (line, area etc) is also removed when the measure tool is closed, but that might be by design.

**Comment by jokd** [comment]
Keeping the measurements in the map when inactivating the tool is by design but the hair cross is a bug.
