### ISSUE TITLE
Add annotations/popup to the measure-control

### ISSUE THREAD

**Issue by filleg** [origo-map/origo#1378]
Is your feature request related to a problem? Please describe.
It would be useful to be able to add annotations to the lines/polygons while using the measure-control in form of a pop-up eg.

**Comment by jokd** [comment]
@filleg Can you elaborate on the use case for this? Perhaps this is a (very welcomed) feature for the draw plugin rather than the measure control.

**Comment by filleg** [comment]
You are correct that the feature is most needed in the draw plugin. I made a similiar [issue](https://github.com/origo-map/draw-plugin/issues/41) a while back. However it could/should have a wider scope then point/marker of course. 
The use case I had in mind is too narrow to justify if the draw-plugin can offer annotations.
