### ISSUE TITLE
missing methods from ol build files

### ISSUE THREAD

**Issue by markus659** [origo-map/origo#138]
The measure control is using some methods that currently are not part of the OpenLayers build files. The ones I have noticed are:
```javascript
map.addLayer()
geom.LineString.getType()
geom.LineString.getLastCoordinate()
Feature.getstyle()
geom.Polygon.getArea()
```

**Comment by afogelberg** [comment]
I think the missing methods should only be added to the standard build and not the embed version. Will you add the missing methods @markus659 ?

**Comment by markus659** [comment]
Sure, I will update the standard build file.

**Comment by markus659** [comment]
In my first post I said geom.LineString.getType() was missing, but it is not. I meant geom.LineString.getLength(), which I have added.

Fixed with https://github.com/origo-map/origo/commit/86de6d02e57fd2b07e92c9f60042dac2ec8f032e.
