### ISSUE TITLE
Allow comments in index.json

### ISSUE THREAD

**Issue by steff-o** [origo-map/origo#1380]
**Is your feature request related to a problem? Please describe.**
It really grind my gears when testing out new configurations that it is not possible to comment out lines in the configuration so I have to copy and paste in and out various parts. Also it can be useful for actually document a configuration.

**Describe the solution you'd like**
Allow standard javascript signgle line double slash comments and possibly /* */ for multiline comments.

**Describe alternatives you've considered**
Renaming configuration entries so they are ignored, but that does not work for everything and sure does not improve readability.

**Additional context**
I know that json specification explicitly forbids comments in json, but that does not prevent storing comments in a file and strip them before feeding them to JSON.parse() or similar. In fact it is commonly used and many editors supports syntax highlighting  for it.

**Comment by jokd** [comment]
It would also be nice to have a validator/cleaner along with the json-stripper so take care of the small typos that otherwise crashes the application.
