### ISSUE TITLE
Show buffer around point

### ISSUE THREAD

**Issue by johnnyblasta** [origo-map/origo#1386]
**Is your feature request related to a problem? Please describe.**
It would be useful to be able to show a buffer around a point and exactly specify the radius of the buffer.

**Describe the solution you'd like**
I'm thinking it would be a tool in measure control and click on a point and ask for a radius and the buffer is drawn.

**Describe alternatives you've considered**
A buffer around other geometries such has lines could also be useful.

**Comment by tonnyandersson** [comment]
A measure control buffer tool would only provide an extremely short-lived buffer, mainly for quick reference measurements. Useful in some cases, sure, but it won't take long before users start asking for more advanced functionality, like the ability to use the drawn buffer as selection or analysis input in various ways, or just as another drawing tool.

I do see some merit in adding a buffer tool to the measure control, but I also think this may be a good place for someone to start sketching on a more serious geographic analysis plugin.

**Comment by johnnyblasta** [comment]
I would appreciate some input on the following demo:
![BufferPrompt](https://user-images.githubusercontent.com/48793206/143853381-6dd8cd20-c29f-4fd7-bf35-79937081129d.gif)
A bit brutal to use a window.prompt() perhaps, but could be changed to something nicer if the principal of asking for buffer size should be used this way.

**Comment by tonnyandersson** [comment]
Not bad at all.

How about placing the label along the edge of the circle? Just in case the user wanna create multiple buffers at different distances from the same point. That would also prevent the label from covering the objects the buffers are created around (if such objects exists).
