### ISSUE TITLE
Option if both length and area should be active in measure control

### ISSUE THREAD

**Issue by Lund-gren** [origo-map/origo#139]
I think there should be an option to choose which type of measurements are avalible. For example if you only want to have length measurement, like http://hitta.se/kartan or https://kartor.sollentuna.se/ . It seems to be more common to only have length than have both, therefore I think the default should be only length.

**Comment by afogelberg** [comment]
It would be a nice improvement to have an option for measure methods. I'm not sure which option should be default though.

**Comment by markus659** [comment]
I agree, it would be good to have this option available. I think the default should be just length. It does seem pretty rare to have the option to measure areas in publicly accessible web mapping applications.

In my opinion the default version should be what most users would want in their maps (which means that they are not required to do any configuration to get what they want). Those who wish to change/add/remove something can take a look at the documentation to see if there is an configuration option available.
