### ISSUE TITLE
Error in attachment error message

### ISSUE THREAD

**Issue by tonnyandersson** [origo-map/origo#1391]
The error message below is displayed whenever there's a featureinfo request promise error, even if the layer in question is not configured for attachments at all.

This error message should only be triggered if the promise error is related to attachments.

![image](https://user-images.githubusercontent.com/15725608/143268717-4ba87d3d-c58e-4650-b676-053cbd3ffa48.png)

I this this is the culprit, alerting the world about attachments regardless of what the catch of the day is.

https://github.com/origo-map/origo/blob/73b4f93748e01a3d3cea3a470fb21083601439e9/src/featureinfo.js#L412-L420

Ping @steff-o :)

**Comment by steff-o** [comment]
Yeah, maybe a little sloppy error handling there. If doRender() for some reason throws something unhandled it will get caught. Must have overlooked that as previously there was no specific error handling for render(). Not sure exactly what could cause doRender() to throw though. All async operations have already been performed. doRender() only populates the dialog.

**Comment by tonnyandersson** [comment]
Perhaps doRender() won't throw anything ever, under normal circumstances. I stumbled upon this while messin' around with the featureinfo popup. A minor mistake in the popup.js module is what inspired doRender() to throw.

So, this is not a major issue in any way. But it still ain't right.

**Comment by jokd** [comment]
Yeah I ran into that yesterday and it seems that it is the image carousel that triggers the error, at least in my case, and I accidentaly added a fix for it in the webpack 5 PR.

**Comment by tonnyandersson** [comment]
The error message will be triggered if _anything_ breaks within doRender(), including popup/sidebar, carousel, selectionManager etc.

**Comment by jokd** [comment]
Yes and there are numerous ways this can happen

**Comment by steff-o** [comment]
It's an easy fix, just move up the catch before the then clause to only catch errors from the promises in the array. I haven't fixed it as I have been working on the related tables #1398 PR and didn't want to create unnecessary merge conflicts as I have rewritten that part there.

**Comment by jokd** [comment]
@tonnyandersson Is this solved?
