### ISSUE TITLE
Buttons are incorrectly highlighted

### ISSUE THREAD

**Issue by asemoller** [origo-map/origo#1394]
**Describe the bug**
There is a black circle around the buttons when you click on them. And when you close a tool, the button is marked incorrectly.

**To Reproduce**
1. Download latest Origo
2. Click on any button
3. See error

**Desktop (please complete the following information):**
 - Browser [chrome, edge]
 
![marker_icons](https://user-images.githubusercontent.com/17123002/144005225-5edeeae0-3f7f-49e3-9b39-24790b7b7e19.gif)

**Comment by johnnyblasta** [comment]
This is because the button gets focus when clicked.

**Comment by asemoller** [comment]
Ok, is it possible to have different styles for keyboards navigation and mouse/touch?

**Comment by johnnyblasta** [comment]
> Ok, is it possible to have different styles for keyboards navigation and mouse/touch?

Yes, the way to go seems to be the new `focus-visible` class, but however it's pretty new an only updated web browser will support it. (ex. Chrome released April 2021)
