### ISSUE TITLE
Several links and abouts in the config

### ISSUE THREAD

**Issue by asemoller** [origo-map/origo#1400]
**Describe the bug**
Previously, it was possible to add several link controls in the config where each link was displayed under the menu. This is no longer possible, only one of the links is displayed under the menu. This also applies to the about control.

**To Reproduce**
1. Add at least two links or abouts in your config file.
2. In Origo - Click on the menu.
4. Only one link/about appear.

**Expected behavior**
Every link/about should be displayed under the menu.

**Comment by tonnyandersson** [comment]
A feature, not a bug. :)

Probably introduced with [this one](https://github.com/origo-map/origo/pull/1115). That PR made it possible to override the settings of the default controls (like zoom, scaleline, fullscreen etc.) by replacing controls with the same name.

**Comment by asemoller** [comment]
ok, my bad!

So does that mean you said ok to this change?

I really think it should be possible to have more than one link under the menu.

**Comment by johnnyblasta** [comment]
Yeah, it should certainly be possible to have more than one link in the menu.

**Comment by tonnyandersson** [comment]
Oh, indeed I did! I didn't think _anyone_ would _ever_ need more than _one_ of each control. But there's always _someone_...

Two (actually three) ways to solve this, off the top of my head:

1. Never use the same control more than once
2. Use the _underscoreunderscore_ scheme we use for layers with the same name
3. Keep the config controls separated from the default controls until the check for duplicates is done

**Comment by johnnyblasta** [comment]
It would be reasonable to change the link control, so that there is a possibility to add several links in the configuring.

**Comment by tonnyandersson** [comment]
That would be one way to do it. Not sure it's a reasonable one, though. And you would have to do the same thing with the About control, and others that _someone_ might wanna duplicate.

**Comment by johnnyblasta** [comment]
> That would be one way to do it. Not sure it's a reasonable one, though. And you would have to do the same thing with the About control, and others that _someone_ might wanna duplicate.
> 
> However, doing it the easy way would potentially allow for duplicates of _any_ control, for better or worse.

Didn't mean as a complete fix to the problem, but that link control could support multiple links might be useful.
