### ISSUE TITLE
Tab navigation in list of layers

### ISSUE THREAD

**Issue by Maryzandi** [origo-map/origo#1402]
After using "Tab" key to navigate in list of layers, appearance of the list changes and the only way to come back to the previous appearance is to refresh the map.  

See the images:
![image](https://user-images.githubusercontent.com/29747817/145202739-f254a552-03da-4bbc-86dc-1ae99aa1f92d.png)
![image](https://user-images.githubusercontent.com/29747817/145202777-775e1be2-b842-4731-a65b-a10c875786e4.png)

**Comment by johnnyblasta** [comment]
This is something that has been around for a long time, it's a hidden button that takes focus and messes up the legend.

**Comment by johnnyblasta** [comment]
@Maryzandi Which version of code do you use? 
I tested now and didn't see this bug. 
Might have been fixed with PR #1374

**Comment by Maryzandi** [comment]
@johnnyblasta We downloaded the code last week.

**Comment by johnnyblasta** [comment]
> @johnnyblasta We downloaded the code last week.

The 2.4.0 release or the master branch? The master branch is the most current code.

**Comment by Maryzandi** [comment]
Yes, We use the master branch.

**Comment by Maryzandi** [comment]
@johnnyblasta I wonder if you could reproduce this bug? Otherwise I can add more screenshots.

**Comment by jokd** [comment]
@Maryzandi If you can provide a config or link to a map where this happens it would be easier to test/debug.

**Comment by Maryzandi** [comment]
In this video I have tried to demonstrate how the list of layer changes after tab navigation. We downloaded the code yesterday.
![tab4](https://user-images.githubusercontent.com/29747817/152365281-b031b91f-bc41-4754-ab8c-1eb301bac6b4.gif)
.

**Comment by jokd** [comment]
Is it all layers or just the ones with layer names on multiple rows?

**Comment by Maryzandi** [comment]
The appearance of the list changes for all layers and its impossible to see the full names of layers in the list any more.

**Comment by johnnyblasta** [comment]
It's some button that is hidden and should have a negative tabIndex so that it is excluded in the tab order.

**Comment by jokd** [comment]
@Maryzandi @johnnyblasta Is this solved now?

**Comment by Maryzandi** [comment]
@jokd We downloaded the latest code and it seems that it is solved now.
