### ISSUE TITLE
Geoposition does not update its position

### ISSUE THREAD

**Issue by asemoller** [origo-map/origo#141]
The Geoposition does not update its position during a session. It remains locked at its initial location. Only by reloading the page and activating Geoposition again one can achieve an updated location. A live, continuous location update does not work. This occurs in devices such as Samsung, Iphone and Windows tablets and their corresponding browsers. The site, http://karta.sigtuna.se, is secured with https.

**Comment by afogelberg** [comment]
On iPhone and iPad the position is updated as far as I can see. I haven't  tried on Samsung or Windows tablets. @asemoller  is there any difference if you use wifi or mobile data?

**Comment by mulfvik** [comment]
Can confirm the issue on Samsung Galaxy A3. Working fine on Windows tablet. 
Will test Samsung with enableHighAccuracy set to false and maybe replace ol.Geolocation for ol.DeviceOrientation later this week.

**Comment by asemoller** [comment]
When on the move, this also occurs on Samsung Galaxy S5, S6 Edge and iphone. Same problem using wifi or 4G.

**Comment by Lund-gren** [comment]
I have tested on iPad air 2, iPhone 6s, iPhone 7 and Honor 8 and they all work fine and update their position on https://karta.sigtuna.se

**Comment by mulfvik** [comment]
Have been testing different settings in the device (Samsung) and different values in geolocation.js trackingOptions with no luck. 
Browsers: native "internet" and firefox.
Google maps is updating pos.

**Comment by markus659** [comment]
I tried it on a Samsung Galaxy S2 (with Chrome), and the position did update.

**Comment by mulfvik** [comment]
@markus659 Can you give internet or/and firefox a go on that same device so we can norrow it down a little bit more?

**Comment by asemoller** [comment]
Just tried it on the iphone 5s (safari) and the iphone 5se (safari and chrome) and the position does not update.  The position updates fine using Apple Kartor and Google Maps.

**Comment by markus659** [comment]
I was able to reproduce the problem on firefox with android (tried it with both the galaxy s2 and honor 8). If I remote debug firefox I get an error message in the console saying..

```
TypeError: this is undefined origo.min.js:28:17112
	addPosition https://karta.sigtuna.se/dist/origo.min.js:28:17112
	getPositionVal https://karta.sigtuna.se/dist/origo.min.js:28:16871
	c https://karta.sigtuna.se/dist/origo.min.js:7:3664
	[24]</</</jb.prototype.b https://karta.sigtuna.se/dist/origo.min.js:12:22398
	[24]</</</l.u https://karta.sigtuna.se/dist/origo.min.js:12:22826
	[24]</</</l.ko https://karta.sigtuna.se/dist/origo.min.js:18:2456
	bound 
```	

Obviously it's difficult to debug the minified version, but the only "this" in geoposition is located here https://github.com/origo-map/origo/blob/master/src/geoposition.js#L108. I also tried debugging http://kartor.vasteras.se/sam as I figured it is also pretty close code wise to the Origo core, and I get the same error message there (looks slightly different though):

```
TypeError: this is undefined origo.min.js:15:29477
	a http://kartor.vasteras.se/sam/js/origo.min.js:15:29477
	s http://kartor.vasteras.se/sam/js/origo.min.js:15:29371
	e http://kartor.vasteras.se/sam/js/origo.min.js:4:29125
	N http://kartor.vasteras.se/sam/js/origo.min.js:4:30345
	[24]</</</O.prototype.c http://kartor.vasteras.se/sam/js/origo.min.js:8:15698
	[24]</</</Kh.bg http://kartor.vasteras.se/sam/js/origo.min.js:11:2373
	bound 
```

I was only able to reproduce this with firefox on android though, firefox on iOS works fine for me, as does both Chrome (on android and iOS) and Safari.

**Comment by afogelberg** [comment]
Thank you all for testing. I have made a PR #174  to solve the problem @markus659 spotted.

**Comment by afogelberg** [comment]
I have made a test url with the latest updates: https://kartor.vasteras.se/test-gps/. There is no content in the map but the mask. The url can be used to just test geolocation. I removed my base maps because they are in http and not https, which can cause problems with mixed content.

I just tried in on IPhone 6 plus iOS 10.2 and the position was updated as expected. When you test, please make sure that https is used and not http.

**Comment by markus659** [comment]
I tried the test url, and it did work for me on android with firefox, so #174 probably fixed this, contrary to my comment in the PR. @asemoller and @mulfvik could you try the URL with the devices/browsers you are experiencing problems with?

**Comment by mulfvik** [comment]
Snyggt, jag testar med den imorgon.

**Comment by mulfvik** [comment]
Did test on Samsung Galaxy A3. Firefox, Chrome and native browser and they all worked fine.

**Comment by afogelberg** [comment]
Can we close this @asemoller ?

**Comment by asemoller** [comment]
Tried the test url on Samsung Galaxy S5 and S6 Edge using both chrome and samsung internet and the position updates. So yes, we can close this. Thank you all for your help in solving this problem.
