### ISSUE TITLE
Improve how the search results are presented

### ISSUE THREAD

**Issue by sonjahalmstad** [origo-map/origo#1413]
We need to be able to see all hits when we do a search in Origo. One suggestion is to design the  window  for the search results in the same way as the information window. That way it is possible to get a nice overview with all results presented in bundles and we will keep a consistent look.

**Comment by steff-o** [comment]
Would it be possible to design it in a way that it actually uses the infoWindow of choice (overlay, sidebar of infoWindow) by sending the result to featureInfo instead of having to implement a similar dialog for search results?

**Comment by jokd** [comment]
Looking into it a bit more I realize lots of the functionality of the infowindow isn't useful for the searchwindow (such as adding/removing features) so I am leaning towards initially simply copy the infowindow.js and stripping it from the redundant parts and adding the functionality it is lacking (eg getfeature on click).
Downside is we get two similar modules but eventually we can tweak them to share at least some code.

**Comment by MattiasSp** [comment]
Could we, rather than duplicate the functionality of infowindow, make the infowindow more configurable, so that it can be called/loaded without those irrelevant parts when loaded by the search control?

**Comment by MattiasSp** [comment]
> My idea how to solve this is keep awesomplete as is for the autocomplete functionality but when hitting enter/submit, the (complete) search result is used to populate a new window using the (a bit customized) infowindow module and reusing the functionality and logic it has. That way search results and selection results will be presented the same way.

I like this suggestion! It would be a shame to slow down the awesomplete search. Maybe a button or helptext of some sort is needed to allow mobile users "transfer search results to infowindow"?

**Comment by jokd** [comment]
> Could we, rather than duplicate the functionality of infowindow, make the infowindow more configurable, so that it can be called/loaded without those irrelevant parts when loaded by the search control?

Hopefully that's where we end up!

**Comment by MattiasSp** [comment]
A related improvement of Origo Server would be to allow the search route to take the search result limit as a query parameter:

https://github.com/origo-map/origo-server/blob/master/handlers/search.js#L12:
> var limit = dbConfig.limit || 100;

The above could be changed to
`var limit = dbConfig.limit || req.query.limit || 100;`

So if we want the awesomplete search to still be limited to e g 10 results per layer but be able to fetch the full results for the infowindow, then we could remove the limit from Origo Server `dbconfig.js` and add the `&limit=10` parameter when searching.

We still want the Origo Server admin to be able to set a hard limit regardless of what the user requests, so I think the `dbConfig.limit` should have priority.

Should I make a new issue for this in Origo Server?

**Comment by steff-o** [comment]
This could be somewhat related to #1228 if there will be a major rewrite of the search result presentation.
