### ISSUE TITLE
Possibility to add prefix and suffix to attribute value

### ISSUE THREAD

**Issue by johnnyblasta** [origo-map/origo#1414]
**Is your feature request related to a problem? Please describe.**
When getting an attribute value f.e. a length of an exercise track. The value is a number 2.5, then I would have the possibility to add a suffix specifying that the unit is "km".

**Describe the solution you'd like**
I would like to be able to specify both a prefix and a suffix to a attribute something like this:
```
"attributes": [
  {
  	  "name":"length",
          "title": "Längd: ",
          "prefix": "ca ",
          "suffix": " km"
  }
]
```

**Comment by steff-o** [comment]
Isn't that easily solved by using the html option?

**Comment by johnnyblasta** [comment]
> Isn't that easily solved by using the html option?

Sure you can do it like that and I have done so, but get anoyed when the value is empty and is left with just the suffix. With using a attribute like this it gets automatically left out if empty value.
