### ISSUE TITLE
Create single svg sprite for non-Font Awesome icons

### ISSUE THREAD

**Issue by tonnyandersson** [origo-map/origo#142]
A single svg sprite could be used for all non-Font Awesome icons. That way, only two svg files need to be maintained. This makes general maintenance easier and facilitates implementation of occasional non-Font Awesome icons.

The non-Font Awesome icons should be named after the library they originate from, in a similar manner as the Font Awesome icons (e.g. "**fa**-home"), and also grouped accordingly.

**Comment by afogelberg** [comment]
Fixed with 92b03a7961fdb1cc4e224eb9b0c475f1930db2cf
