### ISSUE TITLE
Export selection to file

### ISSUE THREAD

**Issue by steff-o** [origo-map/origo#1429]
**Is your feature request related to a problem? Please describe.**
When a user has selected some features in one or more layers they often would want to make a thematic map to share with other people and organisations. 

**Describe the solution you'd like**
A function to export the selection as displayed in infoWindow to a local file that can be imported to other maps. The file format is not crucial as most organisations have means to transform between the most common ones, but as Origo has a _drag and drop_ function, it would of course be of interest to export to a format that can be dragged and dropped into origo.

This could be implemented client side for the text formats supported by OL (GeoJson, Gpx and such). This way it would not require a server side component like the present export which does not support geometries anyway.

**Describe alternatives you've considered**
Augmenting the server side export with support for geometries, but that would require a server side component as well.

**Additional context**
It could be implemented alongside the existing export as an alternative to the server side export.

**Comment by jokd** [comment]
This function can also be used in layerproperties to download all features in a layer. Should of course be used with caution but for example sharing draw layers it is very useful. I have this in my pipeline and aim to export in geojson format along with features styling in an import/export function.

**Comment by steff-o** [comment]
If you don't have any objections @jokd I will implement a utility function that basically exports a set of features to a given format and expose it in the api. In that way we can use it from anywhere in the code, including draw. Then I make a call to that function from infoWindow to export the selection.

**Comment by jokd** [comment]
Sounds useful for my implementation as well so go ahead!
