### ISSUE TITLE
Change transactionhandler error strings to something more generic

### ISSUE THREAD

**Issue by markus659** [origo-map/origo#144]
Currently the error strings here:
https://github.com/origo-map/origo/blob/master/src/transactionhandler.js#L147

and here:
https://github.com/origo-map/origo/blob/master/src/transactionhandler.js#L208

says 
```javascript
alert('Error saving this feature to GeoServer.<br><br>'
            + errorMsg);
```

Maybe we could change them to something more generic, e.g. "Error saving this feature to the server...".

**Comment by afogelberg** [comment]
Fixed with d56f54ea929f17dc927bcdb50180d11d8f75ada4
