### ISSUE TITLE
Print - buttons do not change to grey color when they become active

### ISSUE THREAD

**Issue by leafisfalling** [origo-map/origo#1456]
We have downloaded the latest code (2022-02-09) to test Origo map, we discovered there is a bug in the print function. When we  click the different buttons to change setting (for example A4, A3, Low resolution, etc) for printing, it seems that the buttons do not change to grey color. In order to show the active buttons in grey color again we have to click anywhere in the screen once. 

We tested this in Window 10, and  we got same behaviour in Chrome and Edge.

![utskrift](https://user-images.githubusercontent.com/36880995/153599724-f991974d-a67a-4062-8dea-15f738ff09c4.gif)

**Comment by jokd** [comment]
I think it is this commit that caused this beahviour:
https://github.com/origo-map/origo/commit/b5a5a65d5a6fe959bcc3d53d0fe551a36e345b58

Also makes the print settings button not greyed when first loading the print preview.
Will you have a look @johnnyblasta ?

**Comment by johnnyblasta** [comment]
> I think it is this commit that caused this behaviour: [b5a5a65](https://github.com/origo-map/origo/commit/b5a5a65d5a6fe959bcc3d53d0fe551a36e345b58)
> 
> Also makes the print settings button not greyed when first loading the print preview. Will you have a look @johnnyblasta ?

Some annoying competing style sheets rules. Oh the joy! 😃

**Comment by jokd** [comment]
Indeed some friday fun^^
