### ISSUE TITLE
Dragging extern files to map - sometimes it does not work

### ISSUE THREAD

**Issue by leafisfalling** [origo-map/origo#1457]
We have experienced  for some times (both in the lastest code from 2022-02-09 and earlier versions) the function that adding extern file to map is not stable. Sometimes it does not work and we do not know what the reason is. This is experienced in Chrome (not sure about other webbrowsers)

We have to refresh the map to make it work. 

![externa_filer](https://user-images.githubusercontent.com/36880995/153601068-e50d144d-a84c-42e1-9ce1-ee53f83255a4.gif)

**Comment by jokd** [comment]
It looks just like it would if the drag and drop control wasn't added to the map. Reminds me of a similar issue a couple of months ago, will have a look.

**Comment by jokd** [comment]
I am unable to reproduce this while trying some different geojsons and configs. Are you running the map on localhost or on a server?
If you hook me up with your config and geojson I can have a go with them as well.

**Comment by johnnyblasta** [comment]
> I am unable to reproduce this while trying some different geojsons and configs. Are you running the map on localhost or on a server? If you hook me up with your config and geojson I can have a go with them as well.

I also tried to reproduce it and couldn't.

**Comment by jokd** [comment]
Seems like it happens after the print control has been used so it has probably to do with elements being rearranged in the DOM
