### ISSUE TITLE
Print - the preview jumps when save map as picture or pdf

### ISSUE THREAD

**Issue by leafisfalling** [origo-map/origo#1464]
We noticed that when we save map as picture or pdf in the print function then the map preview will enlarge, after a short while then the map preview will minimise again.

This behaviour does not affect the final product png or pdf, we just wonder if this is a normal behaviour that map preview "jump" up and down during this save-map operation. Same behaviour in Chrome and Edge, in Window 10.

![utskrift_hopp](https://user-images.githubusercontent.com/36880995/154064069-1ecbf580-76a4-4073-b3cb-a1fb00743015.gif)

**Comment by jokd** [comment]
This has to do with scaling of the output and is expected. A so called funny feature.

**Comment by johnnyblasta** [comment]
This is because the preview map is scaled down a bit to fit the screen easier and when the image is saved the full size is restored for a bit.
