### ISSUE TITLE
Error when printing a drag and drop-layer

### ISSUE THREAD

**Issue by jokd** [origo-map/origo#1466]
**Describe the bug**
Trying to print a map with a drag and dropped layer results in an error.

![image](https://user-images.githubusercontent.com/6848075/154069329-9fa57b0b-2117-44f1-b129-8dbb272f9b7e.png)

**Comment by jokd** [comment]
Guess its related to the legend. Comments on this @Grammostola ?

**Comment by Grammostola** [comment]
I'll have a look asap
