### ISSUE TITLE
Grey circle for active background maps 

### ISSUE THREAD

**Issue by asemoller** [origo-map/origo#1479]
**Describe the bug**
The grey circle around the active background map disappears when changing background map. And when you change the background map, the icons gets a jump.

**To Reproduce**
2. Click on another background map.
3. See error

**Expected behavior**
The active background map should get a grey circle and without a jump.

**Screenshots**

![active-background-map-issue](https://user-images.githubusercontent.com/17123002/156142701-db1d8e46-e56d-4670-a986-1ba725e47be4.gif)

**Comment by johnnyblasta** [comment]
This is the same syndrome as #1456 so can look at a similary solve as there.
