### ISSUE TITLE
The check boxes for layers and subgroups are not aligned

### ISSUE THREAD

**Issue by asemoller** [origo-map/origo#1480]
**Is your feature request related to a problem? Please describe.**
The check box for <del>visible button (or what is it called?)</del> for layers and subgroups are not aligned and it doesn't look good. (nr 1)

**Describe the solution you'd like**
Even though there is no more-option button for subgroups the check box for subgroups and layers should be aligned. (nr 2)

**Describe alternatives you've considered**
Maybe it should be possible to have a more-option button even for groups and subgroups if there is an abstract for the group/subgroup. Currently, the abstract is displayed in a text area below the group or subgroup. It would be nice if one could choose to have a more-option button instead of the text area. (nr 3)

**Screenshots**
1. This is how it looks now with more-option button:

![image](https://user-images.githubusercontent.com/17123002/156149492-84d57a79-a48b-477e-98e1-4bedb97c2fbc.png)

2. With aligned check boxes for subgroups and layers:

![image](https://user-images.githubusercontent.com/17123002/156152967-d20f2c40-5f51-40f5-b85f-0cc993a52b86.png)

3. How it could look with more-option for subgroups and groups:

![image](https://user-images.githubusercontent.com/17123002/156150141-d157ce56-142d-4c76-b118-bba006800a00.png)

**Comment by jokd** [comment]
We agree that the boxes (circles) should align and 'more option' is useful for groups as well.
