### ISSUE TITLE
Print - Scale bar becomes small when change print setting to high resolution (300 dpi)

### ISSUE THREAD

**Issue by leafisfalling** [origo-map/origo#1483]
When we change the resolution for print the scale bar in the preview becomes smaller.

1. Go to "Print" in the menu 
2. Change the resolution to "High (300)"
3. The scale bar becomes much smaller. 

![high_low_resolution](https://user-images.githubusercontent.com/36880995/156388387-4973cf6f-00cf-47bf-b7fd-0a939c3f3ca0.gif)

Tested in Window 10, Chrome, with the kod for version 2.5

I see there is an issue 1407 about changing print resolution and not sure if this is related to that.

**Comment by Grammostola** [comment]
I can only reproduce that by using the suppressNewDPIMethod param for the print control, i.e how it used to be, WMS background maps got itty bitty labels and vector features and pieces of the layout were made smaller. Are you using master or the latest release? It doesn't seem to reproduce with the demo map for instance

**Comment by leafisfalling** [comment]
We are using the code for the latest release. 

We do not use the suppressnewDPIMethod in our config  json-file, we just define "supressResolutionsRecalculation" and we tried both true and false and both donot help.

**Comment by Grammostola** [comment]
With the latest master I defined the layer like so
```json
{
  "name": "P12_Risk_paverkan_specifikt_vatten",
  "title": "P12_Risk_paverkan_specifikt_vatten",
  "group": "WMSer",
  "queryable": true,
  "type": "WMS",
  "visible": false,
  "source": "P12",
  "opacity": 0.5
},
```

from a source like so:
```json
    "P12": {
      "url": "https://ext-geodata.lansstyrelsen.se/arcgis/services/hav/P12_Risk_paverkan_specifikt_vatten/MapServer/WmsServer"
    },
```
and then print just that layer

with a print ctrl defined like so:
```json
    {
      "name": "print",
      "options": {
        "sizes" : {
          "a4": [297, 210],
          "a3": [420, 297],
          "a2": [594, 420],
          "a1": [841, 594],
          "custom": [297, 210]
        },
        "sizeInitial" : "a4"
      }
    },
```

and that seems to work at any DPI. I only tried changing the dpi then printing. If this does not work for you I hope someone else has time to try and reproduce the issue : )

**Comment by Grammostola** [comment]
Hmm, how it is meant to work at release 2.5 is evident in the demo map and I've been unable to reproduce this issue when testing a local copy. Do you experience it with the default config.json for example?

**Comment by Grammostola** [comment]
Right, if you are using 2.5 or the current master and the demo json config, I can't currently say what causes the issue your are experiencing. It looks just like it did prior to the the recent print PR and like it does if you set suppressNewDPIMethod to true in the print controller config.

The first is how 150DPI -> 300DPI looks legendwise with suppressNewDPIMethod: false (the default)
![supnewdpi_false](https://user-images.githubusercontent.com/5138906/156752438-05c28066-6a8e-4c02-8a81-3667b4912eab.gif)

The second is how it was before and how it currently is with suppressNewDPIMethod: true
![supnewdpi_true](https://user-images.githubusercontent.com/5138906/156752447-e568fa5a-af48-4fcd-a6ae-322baf67cdf7.gif)

**Comment by leafisfalling** [comment]
Even we change our setting for print as follow we cannot make the scale bar right unfortunately. Would be nice if few more people can test it.  

      "name": "print",
      "suppressNewDPIMethod": false

**Comment by johnnyblasta** [comment]
Tested on my configs and can't see that the scale gets any smaller.

**Comment by Grammostola** [comment]
The option is in an options object in the print control def : 

```json
    {
      "name": "print",
      "options": {
        "sizes" : {
          "a4": [297, 210],
          "a3": [420, 297],
          "a2": [594, 420],
          "a1": [841, 594],
          "custom": [297, 210]
        },
        "sizeInitial" : "a4",
        "suppressNewDPIMethod": false
      }
    },
```

Though it being false should be default, but you can try the above if haven't already

**Comment by leafisfalling** [comment]
We tried put SuppressNewDPIMethod parameter in options but it still does not work. We have also copied @Grammostola 's code to our config file, but it does not work neither unfortunately.

**Comment by Grammostola** [comment]
Is the background map a wms service (as well) or merely pre-cached via a standalone gwc or wmts or something else?

**Comment by leafisfalling** [comment]
Our background map is WMTS. I tried both to use OSM as background map and to use no background for printing and we have the same problem.

**Comment by Grammostola** [comment]
It seems as if the wrong https://developer.mozilla.org/en-US/docs/Web/API/StyleSheetList is assumed by the getCSSRule() in print-resize.js if the number changes from the default, which it does when the Layermanager is used. If we assume that Layermanager (and potentially other plugins working in the same fashion) works in an ok fashion then I will probably propose a change which looks for the sheet with a 'href' property that includes 'style.css'; seems to work in preliminary testing.
