### ISSUE TITLE
Print - export to picture is not working

### ISSUE THREAD

**Issue by leafisfalling** [origo-map/origo#1484]
We use WMS in our map (both internally from our own Geoserver and externally generated by ArcGIS from authorities). When we try to export our map with one or more WMS from external authorities to a picture in Print then it does not return any file. But when we turn off the ArcGIS WMS from external authorities then the function save to picture seems work again. 

However, when we export map to pdf, then it works well no matter there is WMS from our Geoserver or WMS generated by ArcGIS from external authorities

1. Turn on a WMS layer generated by ArcGIS (or maybe other map server?)
2. Go to Print
3. Save the map to picture
4. Then it does not return any file back. 

Tested in Window 10, Chrome and Edge, with code for version 2.5

**Comment by Grammostola** [comment]
I tried printing a local ArcGIS WMS layer which worked, I tried https://ext-geodata.lansstyrelsen.se/arcgis/services/hav/P12_Risk_paverkan_specifikt_vatten/ at 300 dpi and that worked as well, as image. What service are you using, how is the layer configured and with what params are you trying to print it?

**Comment by leafisfalling** [comment]
we have the same WMS in the map and it does not work for us to export to picture

![export_ej_bild](https://user-images.githubusercontent.com/36880995/156542274-e1c447a8-5bd8-402c-8e41-1ac4b5b01189.gif)

**Comment by Grammostola** [comment]
Does the web browser console show an error? (f12) 
It looks like that for me too, with the latest master or release, and then Chrome hints at a new download in the lower left or Edge in the top right. It would be interesting to see if Origo's print threw an error for you with the same build and service and layer and if so what that error was.

**Comment by leafisfalling** [comment]
The hints for image file never come up to us. We got this error message:

![image](https://user-images.githubusercontent.com/36880995/156557963-d0128033-d90c-4ae1-9ed3-12fafb77fb28.png)

**Comment by Grammostola** [comment]
With the latest master I defined the layer like so
```json
{
  "name": "P12_Risk_paverkan_specifikt_vatten",
  "title": "P12_Risk_paverkan_specifikt_vatten",
  "group": "WMSer",
  "queryable": true,
  "type": "WMS",
  "visible": false,
  "source": "P12",
  "opacity": 0.5
},
```

from a source like so:
```json
    "P12": {
      "url": "https://ext-geodata.lansstyrelsen.se/arcgis/services/hav/P12_Risk_paverkan_specifikt_vatten/MapServer/WmsServer"
    },
```
and then print just that layer

with a print ctrl defined like so:
```json
    {
      "name": "print",
      "options": {
        "sizes" : {
          "a4": [297, 210],
          "a3": [420, 297],
          "a2": [594, 420],
          "a1": [841, 594],
          "custom": [297, 210]
        },
        "sizeInitial" : "a4"
      }
    },
```

and that seems to work at any DPI. I only tried changing the dpi then printing. If this does not work for you I hope someone else has time to try and reproduce the issue : )

**Comment by leafisfalling** [comment]
We tested a bit more, we find that your code do not have style for WMS. In our map we define style for all our WMS layers. If we remove style in our map then we can save map to image in the Print function.

But in the previous Origo version our WMS layer works well even we define style for the layers, so it is a new behaviour in the latest version. 

We have also just found we can save the map with our WMS to image if we choose not to have legend in settings. So maybe it is a bug in the legend that it cannot get the style for the WMS layer when we save the map to image? 

This is how we define style in the code:

Layer:

      "name": "P12_Risk_paverkan_specifikt_vatten",
      "title": "P12_Risk_paverkan_specifikt_vatten",
      "source": "avlopp",
      "group": "P_Fosfor",
      "style": "P12",
      "type": "WMS",
      "abstract": "<font style='font-size:0.76rem;font-style: italic'> WMS från Länsstyrelsen.<br><a href='https://ext- geodatakatalog.lansstyrelsen.se/GeodataKatalogen/GetMetaDataById?id=10bae110-c35d-4743-92ea-d2a66178fedf' target='_blank'>Se Länsstyrelsens hemsida för mer infromation här.</a></font>",
      "visible": false
		
Style:

	"P12": [
		[
		{
		"icon": {
		"src": "https://ext-geodata-nationella.lansstyrelsen.se/arcgis/services/HaV/lst_hav_sma_avlopp/MapServer/WMSServer?request=GetLegendGraphic%26version=1.3.0%26format=image/png%26layer=P12_Risk_paverkan_specifikt_vatten"
		},
              "extendedLegend": true
		}
		]

**Comment by Grammostola** [comment]
Hi, yes, it seems that way, for ArcGIS Server WMSes. Something to be fixed. 
In the meantime you can perhaps try consuming it as an AGS_MAP layer or use a local image for the legend if prefer WMS. I'm not sure how a dynamic legend is configured for an AGS_MAP, maybe someone else does : )

**Comment by Grammostola** [comment]
I think perhaps the whole getLegendGraphic for a WMS theme layer needs a discussion, i.e incorporating that kind of pre-rendered image in the print legend, as it isn't implemented currently. Geoserver theme WMS layers are currently supported* via their individual rules as that's easier to make pretty than a prerendered getLegendGraphic. 

*Incorrectly at the moment, another issue, have a potential fix that would affect this issue so that there's no crash in this scenario, there's just the title and no symbol in the legend.

**Comment by Grammostola** [comment]
With the last PR this issue can in my opinion be closed because Save image should not crash anymore whether extendedLegend is true or not. Theme legends for ArcGIS server wms services will not show in the Print legend, that however is a feature request and different issue
