### ISSUE TITLE
Legend - more-option button for groups and subgroups

### ISSUE THREAD

**Issue by asemoller** [origo-map/origo#1492]
**Is your feature request related to a problem? Please describe.**
It should be possible to have a more-option button even for groups and subgroups if there is an abstract for the group/subgroup.  

Read some more and look at images in the related issue #1480.

**Comment by asemoller** [comment]
How should this work? If you choose to have a button instead of the text area, what would be the most user-friendly behavior for the button?

1. The text area expands and collapse.

2. A page with "group info" is displayed just like layers and "layer info".

3. The abstract is displayed in the popup menu

Any other idea?

**Comment by jokd** [comment]
Let's go with #2
