### ISSUE TITLE
WMS GetFeatureInfo application/geo+json option

### ISSUE THREAD

**Issue by johnnyblasta** [origo-map/origo#1497]
**Is your feature request related to a problem? Please describe.**
When a WMS don't send FeatureInfo in the format application/json which seams to be the default and only handled in Origo, but have the format application/geo+json it would be nice to be able to specify that the FeatureInfo for this layer should be using application/geo+json

**Describe the solution you'd like**
It should be possible to specify the INFO_FORMAT for the layer like this.
`"infoFormat": "application/geo+json"`

**Describe alternatives you've considered**
The same should be possible for text/plain and text/xml format

**Comment by Grammostola** [comment]
Hi, I think it looks pretty good, well done. One bit of variability, so far isolated to one arcgis server, is:
```xml
        <Format>application/vnd.esri.wms_raw_xml</Format>
        <Format>application/vnd.esri.wms_featureinfo_xml</Format>
        <Format>application/vnd.ogc.wms_xml</Format>
        <Format>application/geojson</Format>
        <Format>text/xml</Format>
        <Format>text/html</Format>
        <Format>text/plain</Format>
```

whereas your proposed change works well when it looks like  so:

```xml
        <Format>application/vnd.esri.wms_raw_xml</Format>
        <Format>application/vnd.esri.wms_featureinfo_xml</Format>
        <Format>application/vnd.ogc.wms_xml</Format>
        <Format>application/geo+json</Format>
        <Format>text/xml</Format>
        <Format>text/html</Format>
        <Format>text/plain</Format>
```

I shall query whether the singular arcgis server has any relevant local configuration (though I can't quite see how that would be the case). Maybe your proposed change could recognize both of the above variants if both are valid.
