### ISSUE TITLE
Zoom to layer extent button

### ISSUE THREAD

**Issue by tonnyandersson** [origo-map/origo#1516]
**Is your feature request related to a problem? Please describe.**
Now with the nifty lil' _More_ button in place, it actually makes sense to add a Zoom To Layer Extent feature.

**Describe the solution you'd like**
I'm thinking that the _More_ menu would be the perfect place to put a Zoom To button. It would probably look quite similar to this:
![zoomto](https://user-images.githubusercontent.com/15725608/162185340-b0b924d4-52c7-4d40-b394-acd4b1aa0bdd.gif)

**Describe alternatives you've considered**
Another (not so refined) approach would be to add the button to the layer row in the legend, next to the on/off switch or something, totally cluttering up the legend. No good.

**Additional context**
This feature will probably not work perfectly with tile based (or similar) layer types since OL doesn't have a clue about the extent of actual _features_ in such layers.

**Comment by jokd** [comment]
Really useful so go ahead!

**Comment by johnnyblasta** [comment]
Yes, more actions to more button!
