### ISSUE TITLE
Multiple values in editorform 

### ISSUE THREAD

**Issue by David0099** [origo-map/origo#1518]
**Is your feature request related to a problem? Please describe.**
When editing a layer it would be good if there was a possibility to choose multiple values from a dropdown list or be able to tick multiple checkboxes and store in the same attribute.

**Describe the solution you'd like**
For example if the attribute is country and the options are:
•	Sweden
•	Norway
•	Denmark
•	Finland
Then being able to select one or many values. 

**Describe alternatives you've considered**
In the dialogue-plugin there is an excellent solution to the problem, with checkboxes. Here you can also add a text value if no option in the value list matches the desired value “for example Iceland”. 
This functionality in the core would be superb.  

**Additional context**
![bild](https://user-images.githubusercontent.com/52694843/162224425-29321a6d-b870-438b-ac70-50a70613ce6e.png)

**Comment by steff-o** [comment]
In most circumstances this would probably easiest be accomplished by adding one column in the database for each option and add a checkbox for each option and make the "other" checkbox control the _condition_ of the custom value input. 

But if there are many options or a more dynamic set of options that prevents altering the table each time the options are changed it would be justifiable with a new attribute control. Then the data model must support roundtripping to the database and the "other" field handling must be defined. The most simple implementation would use a comma separated list. Question is if the "other" (iceland) should be added to the list on re-read, or will it just be labeled as "other" as it will not match original configuration. To be really general, another "other" row should be opened once the first is checked.

**Comment by David0099** [comment]
Hello and thanks for the answer!

I agree that adding column to the database is an easy and smooth solution. In the example above with only five options it would have worked fine.

But as you point out when you have many options, and perhaps more than one attribute with these kind of options, another way to store might be preferred. A comma separated list as you mentioned would be great (example “Norway,Denmark,Iceland)

Didn’t think that much about the “other” field.
One easy way that already works could be to add a column to the database. (Example country_other) and use a textbox for the “other” field were the user can write (Iceland,Brazil for example)

The other suggestion where a new “other” field opens if the first is filled is sounds great, and then the values are added to the list on re-read. This way seems more user friendly, but more tricky to implement?
