### ISSUE TITLE
Configured vector layer extent not fully respected

### ISSUE THREAD

**Issue by tonnyandersson** [origo-map/origo#1523]
**Describe the bug**
Even though it seems to be working well at a glance, setting an extent (a _bbox_, essentially) on a vector layer actually fails in spectacular silence. _All_ features in the layer are loaded, but only the ones inside the extent are shown on the map. The ones outside the configured extent are still there, though. Invisible. Lurking. Scheming.

This bug affects at least WFS and GEOJSON type layers, possibly others.

**To Reproduce**
1. Configure a WFS layer with an extent that excludes some features
2. Load map and click _outside_ the configured extent, in a spot where you know an "excluded" feature is situated
3. Hear the audience gasp in disbelief as the previously invisible feature is revealed

![extentfail](https://user-images.githubusercontent.com/15725608/163365041-a0814f52-4cb5-405b-a27c-3bfaa2dfb3a1.gif)

**Expected behavior**
One would expect that setting an extent on a vector layer would actually exclude all features outside the configured extent, not just hide them.

**Additional context**
Probably not related to #1025.

**Comment by jokd** [comment]
That's not a bug, it's an easter egg.

**Comment by tonnyandersson** [comment]
Obviously.

**Comment by steff-o** [comment]
It's probably OL that does not compute the intersection of the view extent and layer extent before calling the loader function of the  layer's source. In the Wfs case the solution would then be to do what _getFeature()_ does in _Wfssource.\_loaderhelper()_. Yet another argument why _getFeature()_ should be a wrapper for Wfssource (or vice versa).

**Comment by jokd** [comment]
@tonnyandersson Will you have a look at this?

**Comment by tonnyandersson** [comment]
Custom layer extent parameter is not being passed all the way to the source creator, and some other stuff. Quite an easy fix, at least for WFS.

However.

Passing an extent to the WFS _source_ creator will return all features _intersecting_ said extent. i.e. features "crossing the border" will be included. The red box in the screenshot below represents a configured layer extent.

![image](https://user-images.githubusercontent.com/15725608/183406861-016bc68e-7b89-47ac-a1fb-d7527dfb1420.png)

That's nice and all. But if the same extent is passed to the _layer_ creator, only what's _inside_ the extent will be rendered. This means some ugly clipping will occur.

![image](https://user-images.githubusercontent.com/15725608/183407302-656b4639-8a6f-4959-9c64-bcc70b01c22c.png)

It looks even worse with the red extent box removed.

![image](https://user-images.githubusercontent.com/15725608/183407531-e4991ae2-ef5d-44cc-b984-5f884dfc9526.png)

What's the desired outcome here? A nice-looking, well rendered but slightly incorrect representation of the layer, or a clean-cut the-extent-the-whole-extent-and-nothing-but-the-extent-so-help-me-god kind of representation?

**Comment by jokd** [comment]
Either way is a bit dangerous but I'd prefer the first behaviour so there are no distorted features.
