### ISSUE TITLE
Legend - Display thematic symbology inline

### ISSUE THREAD

**Issue by steff-o** [origo-map/origo#1528]
**Is your feature request related to a problem? Please describe.**
If a layer has a thematic symbology, only an icon is displayed in the legend instead of the actual symbology:
![image](https://user-images.githubusercontent.com/33832077/165291994-3a0d068a-dcd8-454b-9186-2f53cc9ce159.png)

To see the actual symbols the user has to click the three-dot menu (or layer name in older versions) to open the layer info, which only displays that layer and hides the rest of the legend.

**Describe the solution you'd like**
By clicking the 
![image](https://user-images.githubusercontent.com/33832077/165255927-50bb8543-2a25-4f6a-a260-a837fa2e0966.png)
the symbology should be displayed in the legend in the same way a group is expanded:

![image](https://user-images.githubusercontent.com/33832077/165257032-dc8cf7ec-cffd-45dd-a7c1-25cba6ccc293.png)

The actual visual representation does not have to be exactly like in the picture, I just photo shopped some screen shots. Maybe the icon should be replaced with a chevron like groups as well.

As always there has to be a configuration that says if the layer starts expanded...

**Describe alternatives you've considered**
Put my head in the sand.

**Comment by johnnyblasta** [comment]
I like this and would be preferable before my issue #1527

**Comment by Grammostola** [comment]
I agree, it would be beneficial to be able to see theme legends at the same time as the other layers' legends

**Comment by jokd** [comment]
I think it'd be nice to be able to expand the styling as in the screenshot

**Comment by steff-o** [comment]
@jokd I put it on hold as there were no real consensus on how it would look like (and thus no PR accepted). 

But I can pick it up any time. Following the post from @tonnyandersson I would say that:
- Only thematic layer symbols can be clicked
- Clicking a thematic layer symbol expands the legend in place
- Adding a config to set if legend should be expanded on start. Defaults to false to behave like legend groups.
- No configuration if it should be possible to expand layer. It will always be possible. If you don't like it, don't click it.
- No changes to the layer info section.

If there are no objections, I will start implementing it as described above and we can make changes later if desired,
