### ISSUE TITLE
Legend groups and subgroups broken

### ISSUE THREAD

**Issue by Owemyr** [origo-map/origo#1551]
**Describe the bug**
Legend groups and subgroups broken, see behavior from gif-video below.

**To Reproduce**
Add groups and subgroups to json-config and try to expand and minimize or turn on all layers in a subgroup.

**Screenshots**
![groups_probs2](https://user-images.githubusercontent.com/47249045/171834193-4724746b-b830-4164-aa4e-8c18ca2aa237.gif)

**Desktop (please complete the following information):**
 - OS: Windows10
 - Browser Edge ( version 102.0.1245.30)

**Comment by jokd** [comment]
Thanks for the report. 
Seems to be multiple listeners on the legend items, for some reason.

**Comment by jokd** [comment]
I can backtrack this to changes to 'src/ui/component.js' in #1529 where the component is refactored. This somehow messes up the legend. 
@sweco-sedalh @Grammostola any input on this?

**Comment by Grammostola** [comment]
We shall strive to get back to you sometime next week.

**Comment by sweco-sedalh** [comment]
A fix is now available in #1552.

@Owemyr can you test it to make sure that it fixes the bug for you?

**Comment by Owemyr** [comment]
Tested #1552 with the reverted refactoring, working fine in our fork and configs.
So far we don't see any strange behavior.
