### ISSUE TITLE
Editor, adding image to multiple objects same session

### ISSUE THREAD

**Issue by mulfvik** [origo-map/origo#1568]
**Describe the bug**

When adding image to more than one object in same session there is an error of undefined. This occures even if first object i saved.

**To Reproduce**
1. Add one object and append an image to it
2. Save or not save
3. Add another object and append an image to it
4. Save

**Expected behavior**
It should be possible to do this in the same session and not be forced to update site

**Desktop (please complete the following information):**
 **This does not occure on** 
- PC
- Windows 10
- Chrome
- Version 103.0.5060.114 (Officiell version) (64 bitar)

**Smartphone (please complete the following information):**
**This does occure on** 
 - Galaxy S10e
 - Android 12
 - Chrome
 - 103.0.5060.71

**Additional context**

**Comment by jokd** [comment]
@mulfvik Are you gonna have a look at this?

**Comment by mulfvik** [comment]
@jokd Not able to make the time for this one I'm afraid

**Comment by mulfvik** [comment]
No issue on this with newer version so I close this
