### ISSUE TITLE
Support for setting tolerance

### ISSUE THREAD

**Issue by jokd** [origo-map/origo#158]
We should be able to set tolerance for interacting with features in the map. Points and lines can be hard to interact with on mobile devices.

**Comment by afogelberg** [comment]
I agree @jokd . I believe this will be supported in the next release of ol.

**Comment by afogelberg** [comment]
This feature has now landed in OL 3.20. When setting tolerance do we want the tolerance to apply to all type of geometries including polygons? My experience is that lines are hardest to hit.

**Comment by jokd** [comment]
Nice spotted @afogelberg 
Perhaps the tolerance should be able to set global as well as on layer basis. Polygon layers could be excluded by default but sometimes you might have small polygon features you would like to have a certain amount of tolerance. Lines ans points will for sure benefit from this feature.
There are other nice improvements in 3.20 making it worth upgrading, but the MVT vector tiles went broken for me.

**Comment by afogelberg** [comment]
Then I suggest we start with a featureinfo option to set a general tolerance. We can make further enhancements later if required.

**Comment by afogelberg** [comment]
@jokd I guess we can close this?

**Comment by jokd** [comment]
Yes, fixed with #234
