### ISSUE TITLE
A problem with the characters åäö in print legend but not in the map legend

### ISSUE THREAD

**Issue by Susse53** [origo-map/origo#1586]
**Description**
There is a problem in print legend when using a WMS with a SLD containing åäö in the title of the rules. It works in the map legend but not in the print legend.

**To Reproduce**
1. Select a layer in your map
2. Choose to print

**Expected behavior**
We expect the characters to work both in the map legend and the print legend

**Screenshots**
As shown on the image below the characters å, ä, ö are replaced. 
![screenshot printlegend](https://user-images.githubusercontent.com/106728628/186625028-ed806a82-7e85-4057-ab95-f1d2cdb54f4a.JPG)
But as you can see below the characters work in the map legend
![screenshot legend](https://user-images.githubusercontent.com/106728628/186624978-0e54c082-34ad-40fc-8726-87158e644986.JPG)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Microsoft Edge
 - Version 104.0.1293.63

**Comment by Grammostola** [comment]
Hi, I had a look at one of our WMS theme layers that does not experience this issue in the print legend.
The SLD in question looks like so
```xml
        <Rule>
          <Name>Samråd</Name>
          <Title>Samr&#229;d</Title>
          <ogc:Filter>
```

(and the head is : 
```xml
<?xml version='1.0' encoding='ISO-8859-1'?>
<StyledLayerDescriptor xmlns="http://www.opengis.net/sld" xmlns:ogc="http://www.opengis.net/ogc" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" version="1.0.0" xsi:schemaLocation="http://www.opengis.net/sld StyledLayerDescriptor.xsd">
```

I am wondering how your sld looks?

**Comment by johnnyblasta** [comment]
Probably something with encoding in the first xml-tag.
Our sld looks like below and åäö works fine in print.
```
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<StyledLayerDescriptor xmlns="http://www.opengis.net/sld" xmlns:ogc="http://www.opengis.net/ogc" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" version="1.1.0" xmlns:xlink="http://www.w3.org/1999/xlink" xsi:schemaLocation="http://www.opengis.net/sld http://schemas.opengis.net/sld/1.1.0/StyledLayerDescriptor.xsd" xmlns:se="http://www.opengis.net/se">
```

**Comment by jokd** [comment]
I have the same issue and neither of your solutions worked out so there may be settings elsewhere as well.

**Comment by jokd** [comment]
Opened the .sld file in Notepad++, encoded it as UTF-8 (despite ISO-8859-1 in the xml header) )and saved the file and it turns out well in the print layout. However, looking at the sld in Geoserver shows weird signs for the special chars so theres obviously a glitch in our environment. But at least a way to come around it.
The header I used:
<?xml version='1.0' encoding='ISO-8859-1'?>
<StyledLayerDescriptor xmlns="http://www.opengis.net/sld" xmlns:sld="http://www.opengis.net/sld" xmlns:ogc="http://www.opengis.net/ogc" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" version="1.0.0" xsi:schemaLocation="http://www.opengis.net/sld StyledLayerDescriptor.xsd" xmlns:se="http://www.opengis.net/se">

**Comment by Grammostola** [comment]
Seems its default encoding is somewhat locale-dependant. 
`java -XshowSettings` here gives 
`file.encoding = Cp1252` which isn't what we want, I guess, and the internets appear to agree with you that the way to cure that is explicitly setting it when initing the jvm.

**Comment by sonjahalmstad** [comment]
It works for us in Enköping now! We used @jokd 's solution.

**Comment by tonnyandersson** [comment]
Is there anything that can be done in Origo to solve this issue? If not, this issue should be closed.

**Comment by sonjahalmstad** [comment]
Go ahead and close.

**Comment by jokd** [comment]
I close this as it is not an Origo issue
