### ISSUE TITLE
Different behaviour when using FeatureInfoLayer

### ISSUE THREAD

**Issue by filleg** [origo-map/origo#1587]
**Describe the bug**
The layer config option "FeatureinfoLayer" should not be limited to the geometry of the original layer but the one assigned with the config option. The request is correct but limited to the extent of the original layer. 

**To Reproduce**
Set up a layer which points out a different layer in the config through featureInfoLayer and do a getfeatureinfo request.

**Expected behavior**
Getfeatureinfo should use the geometry of the assigned layer with "featureinfolayer" and not the original one.

**Desktop (please complete the following information):**
 - Windows 10
 - Chrome
 - Version 90.0.4430.93 (Officiell version) (64 bitar)

**Comment by jokd** [comment]
This is the expected functionality. You have been using a flaw in the OL library that is no more.
If one wants this functionality, that is to query another layer no matter if a visible layer has features or not, it has to be developed. In rare cases it can be useful, for instance when using external wms services that aren't queryable or transparent.
