### ISSUE TITLE
Update CONTRIBUTING.md with guidelines for PR subject

### ISSUE THREAD

**Issue by jokd** [origo-map/origo#1589]
Now that we use automatic changelog between versions, the PR subject should be descriptive.
Eg:
FIX: Layer lacking id
FEATURE: Measure tool in 4D

Any other relevant prefixes?

**Comment by Grammostola** [comment]
docs: (for editing md files here in this repo); perhaps refactor: but may be that refactor: would be so rare as to be best covered under fix:; exclamation mark for breaking changes is an option but may be too rare as well; i'm looking at conventional commits, speaking of, do we want capitals?

**Comment by jokd** [comment]
Suggestion:

dep: updated dependencies
docs: editing .md-files in this repo
feature: for new features
fix: bugfix or rewritten code that doesn't add new functionality

all lowercase
