### ISSUE TITLE
About control to show map information

### ISSUE THREAD

**Issue by afogelberg** [origo-map/origo#160]
It would be useful to have the possibility to show general information about the map for example contact information. Preferable the information is opened from the map menu.

**Comment by jokd** [comment]
@tonnyandersson has done exactly this, right? ;)

**Comment by tonnyandersson** [comment]
@jokd @afogelberg Pretty much, yes. But it was a quick and dirty deal. It is activated from the map menu and uses the Modal control to present a simple message (title, content). Lots of room for improvement.

**Comment by afogelberg** [comment]
Sounds like a good start @tonnyandersson . Looking forward to see a PR for this.

**Comment by afogelberg** [comment]
Fixed with 6ae3bbd42db198b48c7965062135fb37047441a0. Thank you @tonnyandersson for the contribution

**Comment by afogelberg** [comment]
@tonnyandersson we would also need some documentation for the new control.

**Comment by tonnyandersson** [comment]
@afogelberg Of course!
