### ISSUE TITLE
Enhanced search control with result list

### ISSUE THREAD

**Issue by afogelberg** [origo-map/origo#161]
Development of an enhanced search control has been started. The autocomplete function will be enhanced with a result list that will be displayed in parallell and opened as a sidebar. The result list is grouped by layer. Adding the result list will be optional and added as a separate control.

**Comment by tonnyandersson** [comment]
@jokd Would you say that this is covered by #1413? If so, this issue could probably be closed.

**Comment by jokd** [comment]
Pretty much exactly the same so I close this.
