### ISSUE TITLE
Make editor take selection from FeatureInfo or SelectionManager

### ISSUE THREAD

**Issue by steff-o** [origo-map/origo#1614]
**Is your feature request related to a problem? Please describe.**
If the user has searched or selected a feature and wants to edit it, the user has to select it again by clicking in the map after activating edit mode.

**Describe the solution you'd like**
If Selection manager (or FeatureInfo) has a feature selected it would be selected for editing when editor is activated.

**Describe alternatives you've considered**
Educate users to do it the hard way.

**Additional context**

**Comment by jokd** [comment]
@steff-o Any progress on this? I have a user that is unable to edit features covered by other features, as in #612. This could be a workaround for that issue, otherwise I might have a go fixing #612.

**Comment by steff-o** [comment]
Well, I thought I was finished, but during tests we found some strange behavior during certain circumstances and then other stuff came in the way. Hopefully next week, but I can't promise anything.
