### ISSUE TITLE
GetFeatureInfo WMS inside grouplayers

### ISSUE THREAD

**Issue by filleg** [origo-map/origo#1618]
Describe the bug
GetFeatureInfo click works to well with WMS layers inside a grouplayer.
Even though you setup a layer inside the group with "queryable": false it works.

To Reproduce
Config a WMS-layer with attributes and set it to "queryable": false inside a grouplayer "type": "GROUP"

Desktop (please complete the following information):

OS: Windows 10
Browser: Chrome
Version: Version 90.0.4430.93

**Comment by tonnyandersson** [comment]
@filleg I guess you need some layer(s) in the group layer to be queryable and some not? Otherwise, you could set `"queryable": false` on the actual group layer as a temp fix. But then no layer in the group will be queryable.

But I guess you've figured that out already.
