### ISSUE TITLE
Hide features when thematic style

### ISSUE THREAD

**Issue by johnnyblasta** [origo-map/origo#1629]
**Is your feature request related to a problem? Please describe.**
It would been nice to be able to hide some of the features in a thematic style.

**Describe the solution you'd like**
On a thematic style there could be a checkbox in front of each style and if you want to hide a certain type you just uncheck the box and the features disappears from the map.
![image](https://user-images.githubusercontent.com/48793206/199452725-bc8a1fc4-448b-41f4-badb-ab804257b964.png)

**Describe alternatives you've considered**
The function should perhaps be off by default and can be activated on a layer level.

**Comment by jokd** [comment]
I really like that feature (use it in QGIS alot) but it might be confusing for the user if you have checkboxes both to the right and left. But if it's packaged nice I'm all for it. 
Especially if it supports WMS as well (by stealing the code from the print legend)

**Comment by Grammostola** [comment]
Good ideas both! Yes @jokd I suppose that you mean we can get rule symbols for a theme layer there, to couple with them checkboxes. Some sort of filter on the getmaps would be needed as well I imagine.

**Comment by jokd** [comment]
I have worked a bit on this feature and it looks like this:
![chrome-capture-2023-4-29 (1)](https://github.com/origo-map/origo/assets/6848075/ef0aca61-02ec-4b06-8b45-62886f21532b)

However at the moment this is just filtering vector layers by turning on/off styles in the config file, it doesn't filter the wms requests.

**Comment by jokd** [comment]
To make it work with WMS we will need to rewrite how the wms legend is built; instead of an image we need to make the getlegendgraphic return a json similar to the print legend
