### ISSUE TITLE
wmsStyle not fully compatible with stylePicker for WMS layers

### ISSUE THREAD

**Issue by Grammostola** [origo-map/origo#1642]
The stylePicker is currently available for vector layers and WMS layers (documentation pending).

Specifying that a WMS layer should initiate with an alternative style can be done via the `wmsStyle` property of a `style` object as per the documentation. It should be possible to also specify a stylePicker for such a WMS layer without issues. This is not the case currently. 

The `default` style is always pre-selected in the stylePicker and combining `default` with a styleName does not work quite as expected.

**To Reproduce**
Specify a WMS layer to start with an alternative style and also a stylePicker which includes the start style

```json
    "style": "papperskorgaraltstil",
    "stylePicker": [
      { "title": "Papperskorgar standardvisning", "default": true  }, 
      { "title": "Tömningsintervall", "style": "papperskorgar_tomning", "hasThemeLegend": true }    
    ]

///
    "papperskorgaraltstil":
    [[{
      "icon": {
        "src": "https://mapserver/geoserver/workspace/wms?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetLegendGraphic&FORMAT=image%2Fpng&LAYER=sokvy_park_papperskorgar&SCALE=2132.8571428571427&STYLE=papperskorgar_tomning"
       },
       "extendedLegend": true,
      "wmsStyle": "etuna_park_papperskorgar_tomning"
    }]],
```

**Expected behavior**
The given `default` style is still treated as the default layer style on the WMS server and in Origo but the stylePicker is preset to the alternative style specified by `wmsStyle`

**Current behavior**
The given `default` style is  treated as the default layer style on the WMS server and in Origo and is also the preselected style in the stylePicker. The stylePicker appears partially non-functional (the legend graphic does not change however the layer style in the map does)

**Additional context**
```json
    "stylePicker": [
      { "title": "Papperskorgar standardvisning", "style": "etuna_park_papperskorgar"  }, 
      { "title": "Tömningsintervall", "style": "papperskorgar_tomning", "hasThemeLegend": true, "default": true }
```
appears to work until the map is shared and opened where the layerPicker does not work as expected and the configuration is perhaps a bit unintuitive.

**Comment by Grammostola** [comment]
In regards to the discussion we had at one point over this issue I was thinking and if the (slightly) related issue is accepted then everything needed for a style and a legend should be in the style pickers styles for WMS layers. It would then be possible in the case of a WMS layer with a style: property and a stylePicker to make Origo look for a "style" with that name in the stylePicker array.  The somewhat ambiguous `default` of a stylePicker style could disappear and be replaced with `defaultWMSServerStyle` and what would be shown when the map loaded in the stylePicker would be the style picker style referred to by the layer's `style`. 

As for the existing method of defining a legend for a WMS layer or an alternative layer style via the `style` property and a corresponding `style object` I fail to see a scenario where it would be beneficial to combine this with the stylePicker. Indeed doing so today won't yield a great result. So maybe force a WMS layer to specify one of the styles defined in the stylePicker array to be the default style and if that fails then just fetch the default WMS style and don't show a stylePicker?

**Comment by jokd** [comment]
>So maybe force a WMS layer to specify one of the styles defined in the stylePicker array to be the default style and if that fails then just fetch the default WMS style and don't show a stylePicker?

Sounds good

**Comment by Grammostola** [comment]
(The current) stylePicker functionality for WMS-layers was merged on dec 7 2022 https://github.com/origo-map/origo/pull/1633 and the current release of Origo is 2.6.0 from 2022-08-22. This relates to the need of backwards compatibility if changing the syntax for this functionality.

As mentioned in the issue currently `default` means both that a style is preselected in the dropdown and that the same style is the default style for the WMS layer on the server. Most successful configurations of WMS layers with the stylePicker today probably do not include a `style` property (as a specified getLegendGraphic call doesn't make much sense with a stylePicker and employing an alternative WMS style via `style` and `wmsStyle` doesn't work well.  

What I suggest above is to refer to a `style` of a stylePicker object as the `style` that a WMS layer should start with however this works less well with a `defaultWMSServerStyle` layer as it in the above suggestion doesn't require a name (same as the current `default`). I don't see an immediate issue with providing the server side names of all styles, including the default style (getmap and getlegendgraphic calls should work as well and it's present in the capabilities doc from Geoserver). This, requiring the name of default styles, would not be backwards compatible. It would look like this:

```json
            "style": "etuna_park_papperskorgar_standard",
            "stylePicker": [
              {"title": "Tömning", "style": "etuna_park_papperskorgar_tomning", "hasThemeLegend": true},
              {"title": "Standard", "style": "etuna_park_papperskorgar_standard", "defaultWMSServerStyle": true}
            ]
```

An alternative is to nevermind the `style` property of a WMS layer in the case of a stylePicker and have another property in a style object of the stylePicker for 'starting style'. This could be backwards compatible (since dec 7 2022 that is) in that encountered "default" stylePicker styles could be given the "defaultWMSServerStyle" and "startingStyle" properties.
```json
    "stylePicker": [
      { "title": "Tömningsintervall", "style": "etuna_park_papperskorgar_tomningsint", "hasThemeLegend": true, "startingStyle": true}, 
      { "title": "Standardstil", "defaultWMSServerStyle": true, "hasThemeLegend": true}
```

The third alternative is to add to a `style` object for WMS layers's capabilities and have the stylePicker refer to such a style as is done for vector layers today. There can be `title` and `style` in the stylePicker, the rest in a `style` object. It would need to look more like a stylePicker object and less like a style object does today and it touches on the question what makes the most sense long term in terms of specifying a legendGraphic with the `style` prop of WMS layers normally and occasionally using that `style` to select a different map and legend style from the WMS server. I suppose that functionality has looked the same for many years now and should not change. I'm of a mind to keep it separate for this reason.

:pill:

Input?

**Comment by jokd** [comment]
If alternative 1 better integrates with getting the styles from the getcap then I think that is the better way to go. If not then I think you can decide since you are the boss of this feature.

**Comment by Grammostola** [comment]
This is merely to illustrate my selection process. I intend to go for a solution like the second one here because the first one becomes a little weird in how a property can be named instead of the name of a style and the third one, while appearing pretty logical and most cohesive in terms of how the stylePicker looks for vector layers, also means the lengthiest config with some margin.

proposal 1 slightly reworked where the "style" layer prop is used to point to the name of a style (or the 'defaultWMSServerStyle') in the stylePicker :
```json
{
    "name": "sokvyx_skolor_sarskola",
    "title": "Särskola",
    "group": "utbildning",
    "queryable": true,
    "type": "WMS",
    "style": "defaultWMSServerStyle", // or "etuna_skolor_sarskola_sv"
    "visible": false,
    "searchable": true,
    "source": "etuna",
    "infoFormat": "text/html",
    "stylePicker": [
      { "title": "Svartvit symbol", "style": "etuna_skolor_sarskola_sv", "legendParams": {
         "legend_options": "dpi:300"
       },
     }
      { "title": "Färgsymbol", "defaultWMSServerStyle": true }
    ]
},
```
proposal 2: WMS-stylepicker is self-contained, it has nothing to do with the "style" prop or style objects, if a stylePicker is intended for a WMS layer everything including the starting style (pre-chosen in the stylePicker) is specified as part of the stylePicker:
```json
{
    "name": "sokvyx_skolor_sarskola",
    "title": "Särskola",
    "group": "utbildning",
    "queryable": true,
    "type": "WMS",
    "visible": false,
    "searchable": true,
    "source": "etuna",
    "infoFormat": "text/html",
    "stylePicker": [
      { "title": "Svartvit symbol", "style": "etuna_skolor_sarskola_sv",
      "legendParams": {
        "legend_options": "dpi:300"
    }
    },
      { "title": "Färgsymbol", "defaultWMSServerStyle": true, "startingStyle": true }
    ]
},
```

proposal 3: Mimics the stylePicker format for vector layers and integrates the "style" prop as can be used today for WMS layers. The additional properties can be in the stylePicker or added to a style object. 
```json
{
    "name": "sokvyx_skolor_sarskola",
    "title": "Särskola",
    "group": "utbildning",
    "queryable": true,
    "type": "WMS",
    "style": "farg", // should be one of the styles mentioned in the stylePicker
    "visible": false,
    "searchable": true,
    "source": "etuna",
    "infoFormat": "text/html",
    "legendParams": {
      "legend_options": "dpi:300"
    },
    "stylePicker": [
      { "title": "Svartvit symbol", "style": "sarskolor_sv" },
      { "title": "Färgsymbol", "style": "sarskolor_farg", "defaultWMSServerStyle": true, "legendParams": {
                "legend_options": "dpi:300"
            }
      }
    ]
},

      "sarskolor_sv": [
        [
            {
            "icon": {
                "src": "https://mapserver/geoserver/etunna/wms?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetLegendGraphic&FORMAT=image%2Fpng&LAYER=sokvyx_skolor_forskola&SCALE=100.00000000000001&STYLE=etuna_sv_skolor_forskola"
            },
            "wmsStyle": "etuna_skolor_sarskola_sv",
            "legendParams": {
                "legend_options": "dpi:300"
            },
            }
        ]
      ],
      "sarskolor_farg": [
        [
            {
            "icon": {
                "src": "https://mapserver/geoserver/etunna/wms?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetLegendGraphic&FORMAT=image%2Fpng&LAYER=sokvyx_skolor_forskola&SCALE=100.00000000000001"
            },
            "wmsStyle": "etuna_skolor_sarskola"
            }
        ]
      ]
```

**Comment by tonnyandersson** [comment]
I think maybe I kinda like option 2 and how the `stylePicker`, if present, takes over the role of the `style` parameter. Perhaps this could be implemented for vector layers as well, with backwards compatibility like `if (style) { startWithThat(); }, else { doItTheStylePickerWay(); }`?

Not a fan of the term `startingStyle`, though. How about `initialStyle` or something?
