### ISSUE TITLE
WMS: There ought to be a featureInfoOption for always sending getFeatureInfo-requests

### ISSUE THREAD

**Issue by Grammostola** [origo-map/origo#1651]
**Issue**

Sometimes WMS services whose style cannot easily be modified are employed in a map. If these contain polygon layers with totally transparent fillings then currently if infoclicked on the transparency nothing appears to happen (and no getFeatureInfo request is sent). This was not the case in Origo 2.4 as it seems because Openlayers and Origo worked differently then and always sent a getFeatureInfoRequest for each visible (WMS) layer in the map.

**Describe the solution you'd like**
An featureInfoOption in the settings json for always sending a getFeatureInfo request to all visible WMS layers in the map. Option because lots of requests might be less desirable than the potential for totally transparent polygon styles.

**Additional context**
https://github.com/origo-map/origo/issues/1587
https://github.com/origo-map/origo/issues/513
https://github.com/openlayers/openlayers/releases/tag/v6.13.0

**Comment by jokd** [comment]
Perhaps we should have the option to force getfeatureinfo when layer 'is visible' as well as 'always'? Might be useful in certain applications. While you are at it I mean.... ;)

**Comment by Grammostola** [comment]
I was thinking for it to send one request if there's one "turned on" WMS layer in the map, two if there are two etc, no matter where clicked, does that differ from your request?

**Comment by jokd** [comment]
I meant that in the config you can set it to either be queried when the layer is visible or always (beside the default behaviour).

**Comment by Grammostola** [comment]
Aha, as in:
- list all Image type layers that are queryable (visible or not) and send a feature info request for each
- list all Image type layers that are queryable and visible and send a feature info request for each
- (current default): list Image type layers that are queryable and send a feature info request for each layer with something visible at the clicked location
