### ISSUE TITLE
Print button not really disabled

### ISSUE THREAD

**Issue by johnnyblasta** [origo-map/origo#1661]
**Describe the bug**
The buttons in print for saving image and create pdf isn't really disabled while loading the map. The buttons looks diasbled while loading the map , but they can stil be clicked on and will create a map which isn't fully loaded.

**To Reproduce**
See animation of problem:
![Print-button-not-working](https://user-images.githubusercontent.com/48793206/215499840-0111326f-1c38-49ca-8293-276e44c82001.gif)

**Expected behavior**
The buttons should not be clickable while the map is being loaded.

**Comment by jokd** [comment]
@johnnyblasta Will you have a look at this?

**Comment by johnnyblasta** [comment]
> @johnnyblasta Will you have a look at this?

@Grammostola was a bit keen on looking at this, so he might solve it before I can get to it.

**Comment by Grammostola** [comment]
I'm having a look and can perhaps send a tentative PR later today (else I can talk about it tomorrow). There are a couple of beefs I have with what the print control is doing regardless of whether active or not.
