### ISSUE TITLE
Stylefilter on clusterlayer doesn't work

### ISSUE THREAD

**Issue by Lund-gren** [origo-map/origo#167]
Setting filter on style for a clusterlayer is not working.

**Comment by afogelberg** [comment]
@Lund-gren you need to provide more details

**Comment by Lund-gren** [comment]
Adding a layer with filter works. Adding a layer as a cluster the clusterstyle and style both works fine. 
But having a filter in the style when the layer it is added as a clusterlayer doesn't work, no individual features are drawn in the map. The clusterstyle however works fine so it seems to be somthing when filter is used in the style when a layer is added as a clusterlayer.

**Comment by afogelberg** [comment]
Fixed with #274
