### ISSUE TITLE
Add layer with button instead of drag and drop

### ISSUE THREAD

**Issue by jokd** [origo-map/origo#1678]
**Is your feature request related to a problem? Please describe.**
Drag and drop is super cool and all but not the always most intuitive way of adding a layer to the map. Therefore it would be nice to also have the possibility to add layer by clicking a button. 

**Describe the solution you'd like**
A "Add layer"-button in the drag and drop legend group that mimic a file that is dropped.

**Describe alternatives you've considered**
A stand alone solution but then we won't be able to use the bells and whistles that comes with the drag and drop interaction.

**Comment by Grammostola** [comment]
I like the idea to make the drag-and-drop func somewhat visible. Are you imagining a file selector dialog when the button (same blue plus as layerManager suggested?) or some other functionality?

**Comment by jokd** [comment]
I was initially thinking of having it on the specific group, but maybe better would be to use the same button as the layermanager. In case the map has both layermanager and drag-and-drop-file-import, the button can open a menu where you can choose between add a service(layermanager) or add file (this thing)

**Comment by Grammostola** [comment]
That's how I imagined it first too (the same cosmetics as the LM button rather then the same instance) but now that you mention it the same instance could work too. It rhymes somewhat with the layer context menu if several options.
