### ISSUE TITLE
Print legend not respecting hidden true

### ISSUE THREAD

**Issue by Owemyr** [origo-map/origo#1693]
**Describe the bug**
When using thematic styling and the `"hidden": true` setting, print legend not respecting this.

**To Reproduce**
Use thematic styling and set `"hidden": true`  on one or more rules.

Working example based on origo-logo style from index.json
`"origo-logo": [
      [
        {
          "filter": "[name] !== 'Kristianstad'",
          "label": "Thematic combined style with hidden false",
          "hidden": false,
          "circle": {
            "radius": 10,
            "stroke": {
              "color": "rgba(0,0,0,1)",
              "width": 2.5
            },
            "fill": {
              "color": "rgba(255,255,255,0.9)"
            }
          }
        },
        {
          "circle": {
            "radius": 2.5,
            "stroke": {
              "color": "rgba(0,0,0,0)",
              "width": 1
            },
            "fill": {
              "color": "rgba(37,129,196,1)"
            }
          }
        }
      ],
      [
        {
          "hidden": true,
          "filter": "[name] == 'Kristianstad'",
          "label": "Thematic style with hidden true",
          "circle": {
            "radius": 10,
            "stroke": {
              "color": "rgba(0,0,0,1)",
              "width": 2.5
            },
            "fill": {
              "color": "rgba(255,0,0,0.9)"
            }
          }
        }
      ]
    ],`

**Expected behavior**
Should hide the thematic style rules set to `"hidden": true` in print legend so it works the same as in legend.

**Screenshots**
![image](https://user-images.githubusercontent.com/47249045/221131133-2271f3ae-6445-489f-afad-16d48ebe1969.png)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Edge
 - Version: 110.0.1587.50

**Comment by jokd** [comment]
@Grammostola Sorry I missed that you had assigned yourself to this
