### ISSUE TITLE
Hidden type in infowindow

### ISSUE THREAD

**Issue by johnnyblasta** [origo-map/origo#1698]
If `"type": "hidden"` is set to a attribute it gets hidden in infowindow and editor.
In the documentation this behaviour is documented for the editor, but not for infowindow.
Is it the documentation that is correct that `"type": "hidden"` should have no effect on infowindow or the function that isn't properly documented?

**Comment by johnnyblasta** [comment]
A use case is when you have a editor attribute which should be hidden for example an update time that is set by default, but should be visible in infowindow outside the editor.

**Comment by steff-o** [comment]
In #1509 I claimed that I "fixed hidden attribute type", but that seems to be not entirely correct then. I think I never noticed that it would apply to infowindow as well. I just fixed it for the editor and it wasn't documented at all before. I just found the (defunct) code for the hidden type in the editor code and fixed that and documented it for the editor. And according to the documentation the `type` property is there to define which kind of input to use in the editor.

Facts aside, my opinion is that it would not apply to infowindow as that would be rather silly to declare an attribute to display and then hide it. Problem is when you want both a nice featureInfo presentation and editor in the same application as the attribute specification does not really differentiate between featureinfo and editor attributes and you can not define the same attribute twice. Given that the most likely reason to use a hidden field is to autopopulate it, it would also be displayed in feature info.

**Comment by johnnyblasta** [comment]
> Facts aside, my opinion is that it would not apply to infowindow as that would be rather silly to declare an attribute to display and then hide it. Problem is when you want both a nice featureInfo presentation and editor in the same application as the attribute specification does not really differentiate between featureinfo and editor attributes and you can not define the same attribute twice. Given that the most likely reason to use a hidden field is to autopopulate it, it would also be displayed in feature info.

Yes, it seems a bit weird to declare a attribute with the purpose to show it and then hide it. As it been to hide it is simply not to declare the attribute. 

If nobody has another opinion I can make a PR where the type isn't affecting feature info.
