### ISSUE TITLE
Missing about-control in origoControls

### ISSUE THREAD

**Issue by mulfvik** [origo-map/origo#170]
Added control [#169](https://github.com/origo-map/origo/pull/169/commits/1ba1d4c8ace2973688f2b0c4da34ce376a3a8c4b)

**Comment by mulfvik** [comment]
Added control [#169](https://github.com/origo-map/origo/pull/169)

**Comment by afogelberg** [comment]
Fixed with ae9a57c478fcfb7a5a829a5115f4ec1851e3e3d0
