### ISSUE TITLE
Editor control: The default value of "isActiv" is true.

### ISSUE THREAD

**Issue by alexdahlpublic** [origo-map/origo#1709]
![1](https://user-images.githubusercontent.com/116271275/223667855-2c5b3da2-be37-408b-9b46-181430a1b8c1.png)

**Comment by steff-o** [comment]
Not on my computer. How did you come to that conclusion?

**Comment by alexdahlpublic** [comment]
I don't think so, because in order to be able to select any feature from the checked layer (Origokommuner), I have to turn the editor off first.

**Comment by steff-o** [comment]
@alexdahlpublic, you are correct. I just looked for the editor toolbar. The editor is in fact default active but the toolbar is missing.

So there are two errors in one here:

1. The documentation and actual behavior mismatch. Likely solution is to change documentation as it seems like it has been like that "forever".
2. The other issue is that the toolbar is not visible. That is a bug introduced recently and looks like an easy fix.

**Comment by johnnyblasta** [comment]
Made fix for toolbar not visible issue.
Editor default active has been so "forever" as pointed out by @steff-o so will send in a change in documentation.
