### ISSUE TITLE
Style for required in editorform

### ISSUE THREAD

**Issue by Owemyr** [origo-map/origo#1710]
**Describe the bug**
Style when inputform validate empty values not working as expected in editorform for `"required": true`.

**To Reproduce**
1. Set `"required": true` for attributes in editor.json example.
2. Try to confirm/save form without values
3. See that error text working but not the styling and the inputfield border styling not working.

**Expected behavior**
Border around inputfield should indicate when values missing if  `"required": true` 
The error text should also be styled with orange according to _validate.scss

**Screenshots**
![image](https://user-images.githubusercontent.com/47249045/224295925-bfcf71ca-30cd-457b-8f94-c4eac3d64217.png)

**Desktop (please complete the following information):**
 - OS: Windows 11 22H2
 - Browser Edge
 - Version 110.0.1587.63

**Additional context**
For case/type searchlist the text (error msg) get the right css from _validate.scss but the rest of cases not working.
The orange border for input field not working for any case what i can see.

**Comment by jokd** [comment]
@Owemyr 
Are you working on a fix? We plan to make a release this week.

**Comment by Owemyr** [comment]
@jokd 
Not so big fix :) but deleted  `>` in _validate.scss
Tested on dropdown, text and textarea.
https://github.com/falkopingskommun/origo/commit/08ac0eafebec67ffa11e354fb37795b3edc923ce
