### ISSUE TITLE
Infowindow listLayout - no round export buttons

### ISSUE THREAD

**Issue by asemoller** [origo-map/origo#1711]
When using round export buttons in the infowindow with listLayout: true, the export button is not shown. When listLayout: false the round export buttons work just fine except the tooltip text has some css issues.

The first one is because infowindow_expandableList.js doesn't contain any code regarding round export buttons. We would of course have tested it before submitting a PR but unfortunately we didn't. I can give it a try.

**Comment by asemoller** [comment]
Not really, but I'll see if I can figure something out. I'll let you know by wednesday.

**Comment by asemoller** [comment]
Unfortunately, I haven't had time to look at this one yet. I'll have to try to catch up before the next patch.

**Comment by jokd** [comment]
ok, thx for the heads up. 
Maybe we should also try to join infowindow and infowindow_expandaleList since they seems to share lots of code and stuff like this will be easier to maintain.

**Comment by asemoller** [comment]
Yes, I agree!
