### ISSUE TITLE
Changing loading strategy for WFS? 

### ISSUE THREAD

**Issue by markus659** [origo-map/origo#173]
Today we use loadingstrategy tilegrid for loading WFS features. This results in a lot of requests being sent to the server, many of which return no features (depending on the layer). I don't know if there's any reasoning behind using tilegrid, but could we not use "all" instead? This would greatly decrease the number  of request that are sent, as just one is sent.

https://openlayers.org/en/latest/apidoc/ol.loadingstrategy.html

**Comment by jokd** [comment]
Or perhaps bbox since the response otherwise may hit the roof of your servers max features limit. For instance property borders. Bbox is what we use today.

**Comment by afogelberg** [comment]
I would say that the strategy depends on the data. The problem with all is that all features are always loaded even if the features are outside the current extent. This is not optimal with heavy data and as @jokd say max features limit can be reached.

I think the best solution would be to choose the strategy for source and layer. Maybe bbox should be default?

**Comment by markus659** [comment]
Bbox is probably a good compromise as the default setting.
