### ISSUE TITLE
Sharemap with popup text

### ISSUE THREAD

**Issue by Owemyr** [origo-map/origo#1744]
**Describe the bug**
When using the new draw control and sharing a map an error occur when a popup-text-bubble is active.

**To Reproduce**
1. Draw something with the new draw control and use the attribute/poptext button to attach a popup text.
2. Close the draw control and click on the feature so popup shows up.
3. Click on the sharemap button to get mapstate and copy url.
4. Paste url, results in a empty map and uncaught error in viewer.js where layerType should be declared `const layerType = layer.get('type');`

**Expected behavior**
Show the popup and the other visible features in the mapstate json.

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Edge
 - Version 112.0.1722.48

**Additional context**
Everything working fine when mapstate created without popup active.

Other than this minor bug, the new built in Draw-control is awesome with the geojson import/export, thanks to @jokd and everyone who contributed.

**Comment by jokd** [comment]
This is hopefully solved now.
