### ISSUE TITLE
SVG does not load in IE

### ISSUE THREAD

**Issue by mulfvik** [origo-map/origo#175]
Dont know if im missing some config thats been added in the last weeks/days? I get the same issue from an clean download of the repo.

**Comment by afogelberg** [comment]
@mulfvik do you get the same problem using this link https://kartor.vasteras.se/test-gps/ ?

**Comment by mulfvik** [comment]
Nopp, there is no problem with that link.

**Comment by afogelberg** [comment]
The problem is related to version of svg4everybody. Reinstall svg4everybody:
```
npm uninstall svg4everybody
npm install svg4everybody@2.1.2
```
I created a new issue for this #178

**Comment by mulfvik** [comment]
That did it :)
