### ISSUE TITLE
simpleExport for all layers

### ISSUE THREAD

**Issue by jokd** [origo-map/origo#1781]
**Is your feature request related to a problem? Please describe.**
I would like to be able to omit `layers` in the properties of the simpleExport, just like how the clientExport works. This way it can be used with every layer in the map.

**Describe the solution you'd like**
Omit `layers` property and it will kick in for every layer.

**Comment by asemoller** [comment]
@jokd That would be really nice, unfortunately there's a little but here…

Currently the three export functions cannot work together on the same layer, only one at a time with the following priority: layerSpecificExport, simpleExport and ClientExport. For example, if you omit layers in clientExport and simpleExport, only simpleExport will be available on the layers.

This is not really a preferred solution. At least clientExport should work even if simpleExport or LayerSpecificExport exists for a layer. But the best would be if all three could coexist on the same layer.

I think the export function needs an overhaul regarding buttons, coexistence, merged info windows with listLayout and so on...

**Comment by jokd** [comment]
I worked a bit on this today and pushed a PR. It works well in my environment but I have a basic setup so please test if it works for you as well.
