### ISSUE TITLE
Hide mapmenu on mobile when clicking the map

### ISSUE THREAD

**Issue by Lund-gren** [origo-map/origo#179]
When mapmenu is expanded on a mobile device and you want to hide it, you should be able to click the map to do it. Both Google maps and Eniro has that implementation. What do you think of this, is it something that we want to implement in Origo?

**Comment by afogelberg** [comment]
I remember having this discussion early in the project of Mälardalskartan. In the end we decided to go for the solution we have today but I think it would be a nice option to be able to choose. Maybe we can introduce an option like autoHide? If we have this option, should the menu always hide on map click or should it only auto hide on small screens?

**Comment by Grammostola** [comment]
We have received feedback on our instance of Origo from cellphone users that it would feel intuitive to hide the right hand menu when tapping a map area instead of scrolling up in the meny and tapping the x. No similar feedback from desktop users.

**Comment by Ssalsa** [comment]
Example to turn on function based on screensize https://github.com/Ssalsa/origo/tree/179
