### ISSUE TITLE
Update copyright text

### ISSUE THREAD

**Issue by afogelberg** [origo-map/origo#181]
We need to update copyright year. I suggest we start to use present as OL have started to do from this year.

**Comment by markus659** [comment]
Agreed. Makes sense, just set it to present and you are set.

**Comment by afogelberg** [comment]
Currently we add copyright text in each source file. Maybe that is too ambitous? I suggest we only use the license file for copyright text and then remove the copyright text in all other files.

**Comment by markus659** [comment]
I actually had the same thought when looking at the OL repo. Looks cleaner that way. I think we can adapt the same style, using the license file for the copyright text.

**Comment by markus659** [comment]
Fixed with https://github.com/origo-map/origo/commit/4d4a84a9bd91733c89b9f8e17c85affbb1a87857 and https://github.com/origo-map/origo/commit/4d2bf0a97fdee991dcb14cbc2b4ab96271a731dc.
