### ISSUE TITLE
thematicStyling wms style using åäö

### ISSUE THREAD

**Issue by David0099** [origo-map/origo#1820]
**Describe the bug**
Getting problem with åäö when using thematicStyling with a WMS style from geoserver (2.21.5). see image below, the legend works fine without thematicStyling. 
Also having problem with the filter when äåö is involved. 

**Screenshots**
"hasThemeLegend": true,
"thematicStyling": true,
![image](https://github.com/origo-map/origo/assets/52694843/a86bf503-b4f0-4f9f-85c2-9ab1234d9526)

"hasThemeLegend": true,
"thematicStyling": false,
![image](https://github.com/origo-map/origo/assets/52694843/80115925-139c-423f-85cd-bfb7cb7dfe80)

SLD style
![image](https://github.com/origo-map/origo/assets/52694843/cb514dac-4c4c-4bd4-96e7-4ed8840516e8)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Edge

**Comment by johnnyblasta** [comment]
Works for me, do you have correct encoding for style i Geoserver?

![image](https://github.com/origo-map/origo/assets/48793206/1ce700ee-b1b4-4bbf-8f11-657872303348)

**Comment by jokd** [comment]
For me simply changing the encoding in the style document wasn't enough. I had to change the startup options for Tomcat by adding this line:
`-Dfile.encoding=UTF-8`
And change encoding for the .xml-files and resave them as UTF-8 with a batch script.

If this is too cumbersome perhaps using the getlegendgraphic image in the print legend as an options could be useful?

**Comment by David0099** [comment]
Adding that line to Tomcat made it work for me!

**Comment by johnnyblasta** [comment]
Closing this as it was a configuration issue for external system.
