### ISSUE TITLE
Legend search results

### ISSUE THREAD

**Issue by filleg** [origo-map/origo#1827]
**Is your feature request related to a problem? Please describe.**
If you configure a higher number of hits for `searchLayersLimit` the search results will overflow the screen.

**Describe the solution you'd like**
A maximum height and a scrollable list could be an option. Otherwise avoid going above a certain number of hits.

**Comment by tonnyandersson** [comment]
A scrollable list seems like a good solution, IMO. Especially in situations where it's not possible to enter a more specific search term, like in tag or keyword searches.

This should probably be considered for the main search control as well, if it's not already scrollable.
