### ISSUE TITLE
Rename legend in print settings

### ISSUE THREAD

**Issue by jokd** [origo-map/origo#1828]
How about renaming it to teckenförklaring?
![image](https://github.com/origo-map/origo/assets/6848075/9f29b739-2370-4deb-9044-46c44e80ae92)

**Comment by asemoller** [comment]
Yes!

**Comment by Grammostola** [comment]
I used to think "legenden" was a pervasive minor language corruption but after I found https://svenska.se/so/?sok=legend&pz=4 (click 'Visa mer' for nr 2) I've sort of gotten used to it. For one thing it's shorter than "Teckenförklaring" which is nice sometimes, albeit not here. I want to ask if there's a particular reason "legenden" has suddenly fallen out of favor?

**Comment by johnnyblasta** [comment]
> I used to think "legenden" was a pervasive minor language corruption but after I found https://svenska.se/so/?sok=legend&pz=4 (click 'Visa mer' for nr 2) I've sort of gotten used to it. For one thing it's shorter than "Teckenförklaring" which is nice sometimes, albeit not required here. I want to ask if there's a particular reason "legenden" has suddenly fallen out of favor?

If it has been around since 1782 I have no problem keeping it. No problem with changing it to "Teckenförklaring" either.

**Comment by jokd** [comment]
> I used to think "legenden" was a pervasive minor language corruption but after I found https://svenska.se/so/?sok=legend&pz=4 (click 'Visa mer' for nr 2) I've sort of gotten used to it. For one thing it's shorter than "Teckenförklaring" which is nice sometimes, albeit not required here. I want to ask if there's a particular reason "legenden" has suddenly fallen out of favor?

It's just not that commonly known for the regular users I have been told....
Even if it's obviously a legitimate expression

**Comment by Grammostola** [comment]
> It's just not that commonly known for the regular users I have been told.... Even if it's obviously a legitimate expression

In that case I vote for changing it. I don't think any user will wonder about "Teckenförklaring".
