### ISSUE TITLE
Print legend does not play well with styleByAttribute

### ISSUE THREAD

**Issue by tonnyandersson** [origo-map/origo#1837]
**Describe the bug**
When styling a layer with `styleByAttribute`, the print legend is not able to produce a layer symbol.

**To Reproduce**
1. Style a layer with `styleByAttribute`
2. Enter print mode
3. Look at the print legend and cry a little

**Screenshots**
![image](https://github.com/origo-map/origo/assets/15725608/a4f4c1c5-7efb-440a-8122-4a5a63c27b71)

**Desktop (please complete the following information):**
 - Edge 117.0.2045.40

**Additional context**
When using `styleByAttribute`, the layer style name is automatically set to `origoStylefunction` which is not handled in print-legend.js. Perhaps this issue also affects layers with other custom style functions?

**Comment by jokd** [comment]
Yeah we should probably have a generic icon for the different dynamic styles. Or rather none.

**Comment by tonnyandersson** [comment]
Why not treat such layers as themed layers?

**Comment by jokd** [comment]
> Why not treat such layers as themed layers?

Because each feature has potentially a unique style and rendering all different styles in the legend can be messy

**Comment by tonnyandersson** [comment]
Sure, but what if the user _wants_ all of them to show up in the legend, messy or not? Or perhaps there's only a handful of features/styles that makes perfect sense to show in the legend. Not agreeing with you there.

On the other hand, I realize that _all_ features actually get a "unique" style, even if the style is exactly the same as the style for a different feature. I guess that means that _all_ features would show up in the legend individually, even if they have the exact same style attribute value. To prevent that from happening, we would have to compare every single aspect of every single style to filter out the unique ones. Technically doable, but a bit cumbersome when it comes to labelling and stuff.

So yeah, we should probably have a generic icon for the different dynamic styles.

**Comment by jokd** [comment]
@tonnyandersson Will you have a go at this?

**Comment by tonnyandersson** [comment]
@jokd The quick and dirty way would be to go without any icon at all, like in the image below. So simple it barely qualifies as a "one-liner", but at least it fixes the broken image problem.

![image](https://github.com/origo-map/origo/assets/15725608/fd440391-2453-4b89-a0a9-695beaf962b6)

Not very pretty without an icon, but I don't know what to use as a generic icon instead. I don't think the list type icon we use in the main legend would work very well in the print legend.

I would actually prefer to have an actual icon for each feature, like we discussed above. It's doesn't get _that_ messy, actually, unless you have hundreds of features with different styles. But this solution requires some extra work, so maybe we should just fix this issue quick and dirty and implement something more fancy later on?

**Comment by jokd** [comment]
I think your last suggestion is what we go for. Fix it now by removing the icon if there's none to show and later on fix it a bit more flexible
