### ISSUE TITLE
Draw legend is hiding text

### ISSUE THREAD

**Issue by teros4me** [origo-map/origo#1858]
**Describe the bug**
The text "Legend saknas" is hiding in the Draw legend

**To Reproduce**
1. Add the draw control to the map and activate it
2. Click on the 3 dots in the layer list to open the legend
3. The text "Legend saknas" is hiding

**Screenshots**
![origo_draw_ritlager_legend](https://github.com/origo-map/origo/assets/99867808/e0218e8f-4dff-4f71-803f-b40a5f54f309)

**Comment by Grammostola** [comment]
It seems to be a general "No legend" issue, I think I've interpreted where the latest state (pictured, it was merely slightly clipped before) happened and will issue a PR.
