### ISSUE TITLE
var origo=Origo(json) can't be placed inside head-tag

### ISSUE THREAD

**Issue by huggla** [origo-map/origo#1860]
This issue isn't a big one, but I found it annoying.

The following code doesn't work:
```
<html>
	<head>
		<link href='css/style.css' rel='stylesheet'>
		<script src="js/origo.min.js"></script>
		<script>
			var json={
				"projectionCode": "EPSG:3857",
				"extent": [
					-20026376.39,
					-20048966.1,
					20026376.39,
					20048966.1
				],
				"center": [
					1770000,
					8770000
				],
				"resolutions": [
					1222.99
				],
				"layers": [{
					"name": "osm",
					"title": "OpenStreetMap",
					"type": "OSM",
					"visible": true
				}]
			};
			var origo = Origo(json);
		</script>
	</head>
	<body>
		<div id="app-wrapper"></div>
	</body>
</html>
```
But if json is put in a separate file and loaded with var origo = Origo('file.json'), still inside the head-tag, it works. 

It also works if var origo = Origo(json) is moved to the body-tag.

**Comment by johnnyblasta** [comment]
It's bad practices to have script that impacts the render of the page in the head, so the `var origo = Origo(json);` should be placed in the body-tag.

**Comment by huggla** [comment]
> It's bad practices to have script that impacts the render of the page in the head, so the `var origo = Origo(json);` should be placed in the body-tag.

Makes this even less of a issue, but it is still confusing that Origo(json) and Origo('file.json') gives different results. Also, if the code needs to be placed in the body-tag, then the documentation should say so.
