### ISSUE TITLE
Print legend handles geojson layers without a title in a suboptimal way

### ISSUE THREAD

**Issue by Grammostola** [origo-map/origo#1884]
**Describe the bug**
When no style property is given a geojson layer (at least) the print legend will assume it's a WMS layer and issue two getlegendgraphic requests that ill fit a non-WMS layer. Further the print legend will look a bit funny.

**To Reproduce**
1. Start a default Origo instance
2. Remove the style tag from the origo-cities layer
3. Reload the map
4. Open the print panel

**Expected behavior**
Non-repeated title and an empty space for an icon visually, which rhymes with a recent PR for OrigoStyleFunction-layers and  keeps the structure of the print legend in terms of a hierarchy. In addition, no redundant WMS requests.

**Screenshots**
Current:
![bild](https://github.com/origo-map/origo/assets/5138906/bbef59ce-d08f-4a84-9722-0eb7297ba64f)
Suggested:
![bild](https://github.com/origo-map/origo/assets/5138906/2ca0cf2a-f6d0-4bd8-ad28-af9e27f8db89)

**Additional context**
print-legend.js:
```js
else {
        content = await getWMSJSONContent(title);
     }
```
 appears unsuitable. `else` ought to be the empty space in the shape of an icon

**Comment by tonnyandersson** [comment]
@Grammostola I completely agree! I saw this when working on the previously mentioned "recent PR", thinking that it looked suspiciously similar to a train wreck waiting to happen. But I was too lazy to figure out exactly what conditions would warrant a `getWMSJSONContent` call, so I looked the other way. :smile:
