### ISSUE TITLE
Lots of scrollbars in infowindow in Firefox 

### ISSUE THREAD

**Issue by Grammostola** [origo-map/origo#1888]
With a current Origo instance:

![bild](https://github.com/origo-map/origo/assets/5138906/da34e77e-0be7-442d-98d4-b7862b25c453)

For whatever reason the Chromiums don't show a scrollbar when `overflow-y: scroll` (at least by default it seems), however Firefox does.

**Comment by jokd** [comment]
Yeah it shouldn't be scroll but auto
