### ISSUE TITLE
Removing proj4Defs from index.json breaks the map

### ISSUE THREAD

**Issue by jokd** [origo-map/origo#189]
Removing the proj4Defs for EPSG:3010 breaks the map. proj4Defs is mandatory.

**Comment by jokd** [comment]
Fixed with 9d1e69e69b29c75d5e0806bcced4f1cab4878586

**Comment by afogelberg** [comment]
Sorry about that @jokd . I think we should make it non mandatory to provide proj4Defs if EPSG:3857 is used:
