### ISSUE TITLE
Sharemap with wfs no longer opens overlay or infowindow

### ISSUE THREAD

**Issue by filleg** [origo-map/origo#1900]
**Describe the bug**
The pop-up no longer opens when sharing a clicked feature from a WFS-layer using sharemap. Seems to be introduced since 2.8.

**Additional context**
Tested with both Geoserver and QGIS as backend. Also tested with infowindow and overlay. The sharemap link is correct with `&feature=layername.id`

**Comment by johnnyblasta** [comment]
Noticed this also, haven't investigated it yet.

**Comment by steff-o** [comment]
Looks like the events at startup have changed order so the source has not been read yet when the popup is about to be displayed. Probably is an OpenLayers issue but the solution is to use another event.

Fix coming tomorrow!
