### ISSUE TITLE
Support Geoserver CSS thematic styling in Legend

### ISSUE THREAD

**Issue by steff-o** [origo-map/origo#1921]
**Is your feature request related to a problem? Please describe.**
When using thematic styling on a wms layer that has been published with CSS styling in Geoserver the legend does not display the symbols that the layer uses. However, the styling in the map works and the different style rules can be turned on and off as expected in the legend. 

**Describe the solution you'd like**
The legend should display the symbols regardless if the styling is defined in SLD or CSS.

**Describe alternatives you've considered**
- Try to fix it in Geoserver, but it feels like the turnaround time would be much longer.
- Obviously style the layer with SLD instead of CSS, but that does not seem popular among our user base.
- Hack the generated SLD file. But eventually someone will forget to do that after an update,

**Additional context**
The problem is that when Geoserver converts the CSS style to SLD it does not create a name for the rule as there is no syntax for specifying a name for a rule in the CSS style. When Origo legend makes a request for the legend graphic it first gets the rules from getLegendGraphic as json and parses out the available rules, but as CSS rules have no name it will query for "RULE=UNDEFINED". Test indicates that the title of the rule would work in the query, so changing Origo to use title if there is no name specified would probably do the trick. The same approach would probably have to be applied to the print legend as it is a separate implementation of pretty much the same functionality.

**Comment by Grammostola** [comment]
We are currently looking at the possibility of adding a "@rule" property of css styles, and an automatic rule name in case such a property isn't supplied to the css-plugin (geotools). I asked about this some time back and A Aime replied https://gis.stackexchange.com/questions/452624/name-property-for-rules-in-css-styles-alternatives-or-how-to-contribute . He didn't indicate "just use the title" and I sure haven't been able to use the title for fetching individual rules, even if the title isn't something more suitable for human eyes than machine parsing and an url:
```xml
<ServiceExceptionReport version="1.1.1" >   <ServiceException>
      Specified style does not contains a rule named femhundra
</ServiceException></ServiceExceptionReport>
```

**Comment by steff-o** [comment]
Well, we could have messed up testing, but from what we saw it would be possible to use the title in the getLegendGraphics call. Guess we have to check again if we accidently queried the SLD version when thinking it was the CSS version of the layer configuration.
