### ISSUE TITLE
Search - contains instead of begin with

### ISSUE THREAD

**Issue by asemoller** [origo-map/origo#1926]
**Is your feature request related to a problem? Please describe.**
Right now, you can only search using "begin with...", but it would be useful if you could search with "contains...".

**Describe the solution you'd like**
I want to be able to see all streets that have "strand" in the street name, regardless of whether the name starts with "Norra strand...", "Södra strand..." or just "Strand...". Preferably without a wildcard.

**Comment by jokd** [comment]
#1918 along with changes to origo server (or whatever search endpoint you use) can fix this

**Comment by asemoller** [comment]
Completed in #1918.
