### ISSUE TITLE
Group with context menu jinxes the legend layout

### ISSUE THREAD

**Issue by Grammostola** [origo-map/origo#1928]
**Describe the bug**
If group options are given a group so that it yields a context menu, activating said menu will make the legend display with issues

**To Reproduce**
Have a group (or a subgroup) with the following options 
```json
          "opacityControl": true,
          "zoomToExtent": true,
          "extent": [
            -20026376.39,
            -20048966.10,
            20026376.39,
            20048966.10
          ]
```

**Expected behavior**
The same as when activating a layer's context menu

**Screenshots**

![bild](https://github.com/origo-map/origo/assets/5138906/68a3bbe3-bef5-489f-9fc4-3f4cf6fd88b6)

**Additional context**
The flex element that the context menu creates doesn't seem to stretch south of the item row as it does with layers ( I am not the css wizards)

A context menu requires two context menu options for a group which makes this slightly more of an edge case

**Comment by jokd** [comment]
Is it the removal of `item wrap` classes that messes things up:
https://github.com/origo-map/origo/pull/1913/files

**Comment by Grammostola** [comment]
Indeed. Is the issue that that pr fixed this? 
![bild](https://github.com/origo-map/origo/assets/5138906/0cb110fd-a44c-43cb-bc2e-c62083167959)
It seems you need pretty long group names for the menu to get pushed like that.
