### ISSUE TITLE
Drag and drop styles for more geometry types would be a boon

### ISSUE THREAD

**Issue by Grammostola** [origo-map/origo#1935]
If one enables the drag and drop control and drags and drops the data/origo-mask.geojson the app crashes because there is no default style for "MultiPolygon" for the drag and drop control. (And the documentation isn't super explicit regarding this) 

**Expected behavior**
I would expect a default style for Point, LineString, Polygon, MultiPolygon, MultiLineString and MultiPoint and maybe MultiGeometry (kml).

**Comment by jokd** [comment]
@Grammostola Wasn't this solved in https://github.com/origo-map/origo/pull/1876?
If not, maybe the drag and drop control should default to that style function

**Comment by Grammostola** [comment]
@jokd It is a present problem; what style function (in drawstyles.js)?

**Comment by jokd** [comment]
@Grammostola I was thinking about this stylefunction: https://github.com/origo-map/origo/blob/6ec0f11bb112e38599d04d3a2b0e6cfa18065bfa/src/style/stylewindow.js#L226

viewer.getStylewindow().getStyleFunction()

**Comment by Grammostola** [comment]
@jokd Cool, I shall have a look after the turn of the year.
