### ISSUE TITLE
Draw - enable rotate for objects

### ISSUE THREAD

**Issue by asemoller** [origo-map/origo#1941]
**Is your feature request related to a problem? Please describe.**
Many users have requested a rotation function for objects in the draw control, especially for texts.

**Describe the solution you'd like**
A rotate slide bar (like print) in the style window could work.

**Comment by johnnyblasta** [comment]
Got the same request from a user today. @asemoller are you doing something on this or should I have a look?

**Comment by asemoller** [comment]
@johnnyblasta We haven´t done anything, this is just a suggestion. Feel free to check this out if you want!

**Comment by johnnyblasta** [comment]
@asemoller vad tror du om det här:
![RoteraText](https://github.com/origo-map/origo/assets/48793206/2034aa51-6da7-4472-9814-b32bc893b4c0)

**Comment by asemoller** [comment]
@johnnyblasta Spot on! 👍
