### ISSUE TITLE
Sharemap zoom to feature

### ISSUE THREAD

**Issue by Owemyr** [origo-map/origo#1948]
**Describe the bug**
Sharemap zoom to feature not working.

**To Reproduce**
1. Click to select a origo-cities geojson feature in index example.
2. Create a sharemap url.
3. Open url.

**Expected behavior**
The map should zoom to feature when open sharemap-url. We have also tested on WFS source with same result. 
Worked before, but not sure when and which PR the issue occured.

**Comment by Grammostola** [comment]
What seems to be the problem? Does the map not open at the expected location and zoom level or is the feature not selected? (Or are you missing a zoom/pan animation?)

I tried sharing an origo-cities geojson feature via the default share method and opening the shared map it was set to the zoom level and extent saved with the feature selected including an overlay. Same for a wfs feature. This is what I would expect.

**Comment by Owemyr** [comment]
Problem is that the zoom to feature not trigger when open sharemape-url. 
Every other parameter seems to work just fine.

Here are two live-examples, first latest master, second from around march 2023.

[https://karta.falkoping.se/testingarea/sharemap_zoom_notworking/#layers=osm/v/1/s/0/o/100,origo-mask/v/1/s/0/o/25,origo-cities/v/1/s/0/o/100&center=1970695,8385578&zoom=7&legend=expanded&feature=origo-cities.1&map=index](url)

[https://karta.falkoping.se/testingarea/sharemap_zoom_working/#layers=osm/v/1/s/0/o/100,origo-mask/v/1/s/0/o/25,origo-cities/v/1/s/0/o/100&center=1970695,8385578&zoom=7&legend=expanded&feature=origo-cities.1&map=index](url)

**Comment by Grammostola** [comment]
I see. @steff-o wrote about it in https://github.com/origo-map/origo/pull/1904 . If `zoom` and `center` are removed from the first link then it zooms to the feature. Maybe that should be a prop of the share-ctrl?

**Comment by Owemyr** [comment]
Thanks @Grammostola for the info, that solves our use case right now.

For example, a Sharemap config opt-in `"zoomToFeature" = true` that overrides `center` and `zoom` could be an improvment.
Previously `center` and `zoom` worked as a fallback if, for example, a feature got deleted and no longer existed.

**Comment by steff-o** [comment]
Center and zoom would still work as a fallback right? The change in #1904 obeys all parameters:
1. It centers the map on the center coordinate
2. It zooms to the desired zoom level
3. It pops up the pop up if the indicated feature is found.

What it doesn't do is to zoom to the feature itself, which I admit it did before. But that would ignore center and zoom which effectively made the link not reflect how the map was composed when the link was made. The way it is now is that the link recreates how the map looked when the link was created.

#1899 proposes to select which arguments are part of the sharemap link, which would  make it possible to omit center and zoom and have the map zoom to the selected feature.

**Comment by Owemyr** [comment]
@steff-o thanks for the explanation, I understand the decisions.

The default center/zoom of the map is good enough in our use case when a object not existing.

#1899 could be a good future improvement.

**Comment by tonnyandersson** [comment]
@Owemyr As I understand it, this is no longer an actual issue that needs to be fixed, correct?

**Comment by Owemyr** [comment]
Thats correct @tonnyandersson 
Closing the issue
