### ISSUE TITLE
Image upload option in editor

### ISSUE THREAD

**Issue by tonnyandersson** [origo-map/origo#198]
An image upload option would be a nice addition to the editor.

This feature could be implemented in a number of ways. To make the feature as back-end independent as possible, I suggest a base64 string upload. This works well with WFS-T and does not require any server side scripts. This method should be compatible with most back-ends since the file is uploaded as a "simple" string.

**Comment by afogelberg** [comment]
@tonnyandersson I'm going to develop a feature for image upload in the near future for Mälardalskartan. Is this something you are planning to do as well? I agree that it should be possible to do with WFS-T but I think it will be a feature in Origo server as well.

**Comment by tonnyandersson** [comment]
@afogelberg I just implemented a simple image upload feature for an in-house project. Tried a php based solution as well, but settled with the more WFS-T friendly base64 string for various reasons. But I agree with you regarding an Origo server feature. Perhaps we should do both, with an option to choose method? For flexibility.

**Comment by markus659** [comment]
Fixed with https://github.com/origo-map/origo/pull/246.
