### ISSUE TITLE
Position control - noPositionText with empty value show false

### ISSUE THREAD

**Issue by asemoller** [origo-map/origo#2022]
**Describe the bug**
If "noPositionText" has an empty value, the text "false" is displayed in the footer.

**To Reproduce**
1. Add the position control
2. Set "noPositionText" to ""
3. Move the mouse over the map and then move it off the map
5. See error

**Expected behavior**
The last mouse position should be rendered.

**Screenshots**
![image](https://github.com/origo-map/origo/assets/17123002/a5d5ebf9-1415-4a16-8bd5-fbdbc9f91872)

**Desktop (please complete the following information):**
 - OS: windows
 - Browser: chrome

**Comment by steff-o** [comment]
I can confirm that this is a bug introduced in #1648 when OpenLayers changed the interpretation of the _placeholder_ parameter in the _MousePosition_ class to only show last known coordinate when the placeholder is `undefined`.

Currently there is no way of configuring a workaround as an omitted parameter is in code replaced with a non breaking space.
