### ISSUE TITLE
Wrong GetLegendGraphic url for layer

### ISSUE THREAD

**Issue by kristianmorin** [origo-map/origo#2024]
I want to display GetLegendGraphic for 2 different sources. Note that these has different endpoint `artskart `and `artskartfa`. However the layer _name_ is the same

https://kart.artsdatabanken.no/WMS/artskart.aspx?version=1.3.0&service=WMS&request=GetLegendGraphic&sld_version=1.1.0&layer=Artskart&format=image/png&STYLE=default

https://kart.artsdatabanken.no/WMS/artskartfa.aspx?version=1.3.0&service=WMS&request=GetLegendGraphic&sld_version=1.1.0&layer=Artskart&format=image/png&STYLE=default

[](https://kart.artsdatabanken.no/WMS/artskart.aspx?request=GetCapabilities&service=WMS)
[](https://kart.artsdatabanken.no/WMS/artskartfa.aspx?request=GetCapabilities&service=WMS)

It appears that ORIGO expect the layer name to be unique and create the GetLegendGraphic request based on it (pulling the source attribute with name as key). The issue I have found is that layer name of the service is not necessarily unique. The legend that is displayed is always the last defined WMS layer regardless of source if the name is the same.

```
{
      "name": "Artskart",
      "title": "Rødlistede arter - Artsdatabanken",
      "group": "Nasjonale datasett - Landbruk og naturforvaltning",
      "source": "rødliste_artsdatabanken",
      "type": "WMS",
      "opacity": 1.0,
      "legend": true,
      "abstract": "",
      "hasThemeLegend" : {
        "scale" : 5000,
        "legend_options" : "dpi:100"
      },
      "legendParams" : {
        "sld_version": "1.1.0"
      }
    },
    {
      "name": "Artskart",
      "title": "Artskart fremmede arter - Artsdatabanken",
      "group": "Nasjonale datasett - Landbruk og naturforvaltning",
      "source": "fremmedearter_artsdatabanken",
      "type": "WMS",
      "opacity": 0.8,
      "legend": true,
      "abstract": "",
      "hasThemeLegend" : {
        "scale" : 5000,
        "legend_options" : "dpi:100"
      },
      "legendParams" : {
        "sld_version": "1.1.0"
      }
    },
```

**Comment by johnnyblasta** [comment]
What happens if you use the suffix function in name to tell them apart.

```
{
      "name": "Artskart__rodlist",
      "title": "Rødlistede arter - Artsdatabanken",
      "group": "Nasjonale datasett - Landbruk og naturforvaltning",
      "source": "rødliste_artsdatabanken",
      "type": "WMS",
      "opacity": 1.0,
      "legend": true,
      "abstract": "",
      "hasThemeLegend" : {
        "scale" : 5000,
        "legend_options" : "dpi:100"
      },
      "legendParams" : {
        "sld_version": "1.1.0"
      }
    },
    {
      "name": "Artskart__fremmede",
      "title": "Artskart fremmede arter - Artsdatabanken",
      "group": "Nasjonale datasett - Landbruk og naturforvaltning",
      "source": "fremmedearter_artsdatabanken",
      "type": "WMS",
      "opacity": 0.8,
      "legend": true,
      "abstract": "",
      "hasThemeLegend" : {
        "scale" : 5000,
        "legend_options" : "dpi:100"
      },
      "legendParams" : {
        "sld_version": "1.1.0"
      }
    },

```

**Comment by kristianmorin** [comment]
That worked! 👍

**Comment by johnnyblasta** [comment]
Solved with configuration
