### ISSUE TITLE
AGS_FEATURE requests introduce multiple features when zooming

### ISSUE THREAD

**Issue by Owemyr** [origo-map/origo#2033]
**Describe the bug**
Test with AGS_FEATURE result in multiple features when zooming.

It only occur when zooming out to more/equal than the default extent (inital zoomlevel) or panning outside extent.

**To Reproduce**
1. Set a ArcGIS Mapserver service as source.
2. Set a layer with some transparent style.
3. Zoom out more than initial extent.
4. See how features get more and more, click to verify.

**Screenshots**
![multiple_features](https://github.com/origo-map/origo/assets/47249045/4e7ab3dd-27de-4765-a01b-334270b4b0b6)

**Expected behavior**
Should refresh like WFS bbox, so no old request is hanging around.

**Desktop:**
 - OS: Windows 11
 - Browser Edge and Chrome

**Additional context**
We have a older version of ArcGIS server so that or some settings on the server side could also be the villain.

Alternatives considered:
Not really a alternative but a workaround is to disable `strategy: loadingstrategy.bbox` and set a static big extent in `agsfeature.js` then it loads all features in one request, more like strategy: all for WFS

**Comment by steff-o** [comment]
Are your primary key properly set up on the server so that features always get the same featureId in each request? At least in WFS if the primary key is configured incorrectly the server will generate a new guid-like FID for each feature in each request, which results in OpenLayers VectorSource.addFeatures() will not recognize it as an existing feature and add it again.

**Comment by Owemyr** [comment]
Thanks @steff-o for suggestion. 
Checking with console.log for the two request on same feature i get:

**Request 1**
id = undefined
ol_uid = 232
OBJECTID (attr) = 1

**Request 2 when zooming out**
id = undefined
ol_uid = 257
attr OBJECTID (attr) = 1

**So your right that the featureID is the villain, when set the id to objectID in code it working correct (sharemap popup as well).**

I Think in AGS-standards, OBJECTID is usually the PrimaryKey and "type": "esriFieldTypeOID" in REST tells if its the PK.

So best should be that it picks up the correct PK ID here, right?

**Comment by steff-o** [comment]
I haven't access to a AGS feature server so I can't test, but maybe there is a way to configure the feature service to use the OBJECTID column as primary key. One would expect that to be the default behavior, but according to my sources it may be necessary to explicitly configure the service anyway.

Maybe @tonnyandersson has some input as an AGS user?

**Comment by tonnyandersson** [comment]
I guess we can close this. Do you agree, @Owemyr?

**Comment by Owemyr** [comment]
Close this as its probably our backend that is the problem.
