### ISSUE TITLE
Drawing disappears when show length/area or sections

### ISSUE THREAD

**Issue by mulfvik** [origo-map/origo#2065]
When choosing to show length/area or sections in a drawing the drawing disappears from the map.
![image](https://github.com/user-attachments/assets/de790ca2-2731-4912-ab35-b231607505b5)
![image](https://github.com/user-attachments/assets/0de12e0b-7878-43bd-961d-1ef632ec9b60)

**Comment by Grammostola** [comment]
Has to do with localization and the functions that measure and draw share. I will fix it
