### ISSUE TITLE
New topology utils

### ISSUE THREAD

**Issue by jokd** [origo-map/origo#2077]
**Is your feature request related to a problem? Please describe.**
It is useful to have tools which simplifies or densifies geometries, eg when rendering or sending features to external services.

**Comment by steff-o** [comment]
Yes it could be useful, but will Origo use it? Unless it is used by Origo I see no reason to implement it in Origo. It will only be dead code that will be hard to maintain.

**Comment by jokd** [comment]
Fair enough. I had an idea to maybe use the simplification algorithm along with the drag and drop tool to sanitize dropped files with a gazillion breakpoints but til then I'll put this in the plugin.

**Comment by steff-o** [comment]
Come to think of it, _OpenLayers_ already has a simplify-method in the _Geometry_ class. We use it in the editor.

**Comment by jokd** [comment]
> Come to think of it, _OpenLayers_ already has a simplify-method in the _Geometry_ class. We use it in the editor.

Yeah but it doesn't handle 3d geometries which I needed
