### ISSUE TITLE
Event when item is added to carousel

### ISSUE THREAD

**Issue by jokd** [origo-map/origo#2080]
**Is your feature request related to a problem? Please describe.**
When an item is added to the featureinfo carousel (overlay/sidebar) an event should be dispatched, similar to what happens when the selection manager adds a SelectedItem.

**Comment by steff-o** [comment]
At which point does SelectionManager dispatch an add event? Best I can find is `getSelectedItems.on('add')`, which is an OpenLayers event (yes, they are also events), but featureInfo never dispatches anything for Selectionmanager. This will lead to developers having to take care of both cases depending which infowindow is active.

**Comment by jokd** [comment]
> At which point does SelectionManager dispatch an add event? Best I can find is `getSelectedItems.on('add')`, which is an OpenLayers event (yes, they are also events), but featureInfo never dispatches anything for Selectionmanager. This will lead to developers having to take care of both cases depending which infowindow is active.

Yes you are correct. The doRender function could instead dispatch the itemadded event no matter what type of infowindow is used.
