### ISSUE TITLE
Drop support for IE9?

### ISSUE THREAD

**Issue by afogelberg** [origo-map/origo#212]
Would like to have some opinions on this. Would anybody mind if we drop support for IE9? If we want to keep support for IE9 we need to add a polyfill for requestAnimationFrame.  If we decide to drop IE9 we can also start to use flexbox.

Statistics from https://www.w3schools.com/browsers/browsers_explorer.asp show less than 0.3% users.

**Comment by markus659** [comment]
Personally, I  wouldn't mind. Any version of IE older than 11 is no longer supported by Microsoft: https://www.microsoft.com/en-us/WindowsForBusiness/End-of-IE-support

I strongly doubt any of the official members of Origo is running IE9 in their organizations, but maybe we want to make sure before dropping the support for it?

**Comment by jokd** [comment]
I agree. I run IE10 and it’s a dinosaur we shouldn’t need to care about. Even less IE9.

**Comment by afogelberg** [comment]
Thanks for feedback. It seems dropping IE9 hasn't generated a storm of protests. I have made a PR for better error handling for IE 9 users #214 . Users with browsers that don't support requestAnimationFrame or canvas will get a friendly error message.

In reality we have already dropped support for IE9 since we don't use a polyfill for requestAnimationFrame. The PR solves the error handling.

**Comment by afogelberg** [comment]
Fixed with #214
