### ISSUE TITLE
Polygon layers render multiple doubles randomly

### ISSUE THREAD

**Issue by mulfvik** [origo-map/origo#213]
Anyone recognize this issue?
[example](http://karta.strangnas.se/extern/#layers=topowebbkartan_nedtonad/v/1/s/0,mask_strangnas/v/1/s/0,vy_gallande_detaljplan/v/1/s/1&center=177717,6573970&zoom=8&map=extern)

**Comment by jokd** [comment]
Are you using views with geoserver? Then you will have to create a metadata table:
http://docs.geoserver.org/stable/en/user/data/database/primarykey.html
Otherwise it will create random IDs for the features resulting in multiples when for instance zooming out.

**Comment by mulfvik** [comment]
Thank you jokd, that did it :)
