### ISSUE TITLE
Map does not pan, mobile device/chrome

### ISSUE THREAD

**Issue by mulfvik** [origo-map/origo#224]
Map does'nt pan on touch-device using google chrome if openlayers build is full (ol-build-full) without closure-compiler.

**Comment by jokd** [comment]
I tried to reproduce this but I had no issues running a full build in Chrome on iOS (iPhone 7+). I guess you were using Android? Can't try that setup right now unfortunately.

**Comment by mulfvik** [comment]
Ok, good. Yes, I used Android. Will try to reproduce on other devices when I get hold of one. For now, using the closure-compiler fixed it for me. Reopening this if needed in the feature. Thank you jokd.
