### ISSUE TITLE
Remove css/style.css

### ISSUE THREAD

**Issue by Lund-gren** [origo-map/origo#228]
Should we remove the css/style.css file now that we have scss instead that builds the dist/css/style.css?

**Comment by afogelberg** [comment]
css/style.css is still used in development mode, We can't remove it without changing that.

**Comment by Lund-gren** [comment]
Ok, I didn´t think it was necessary to have the file on GigHub since it´s created when you run ```npm start```, also it´s included in the .gitignore file?

**Comment by afogelberg** [comment]
Sorry about that, of course style.css should be removed. As you say that was the intention when the build was added in npm start.

**Comment by afogelberg** [comment]
Fixed with 2ec07d84c4311304e60d8ea6d75c6e8fb025c4f4
