### ISSUE TITLE
Submenu could open when activating all layers in submenu.

### ISSUE THREAD

**Issue by mulfvik** [origo-map/origo#245]

**Comment by jokd** [comment]
Is this supposed to be the default behaviour or configurable? I may misremember, but I think we agreed on the latter?

**Comment by afogelberg** [comment]
The latter as I remember too.

**Comment by mulfvik** [comment]
Yes, configurable. I wish to suggest that it should open submenu as default though.

**Comment by afogelberg** [comment]
I don't mind default.
