### ISSUE TITLE
Remove console.log?

### ISSUE THREAD

**Issue by markus659** [origo-map/origo#261]
Should we not remove all the rows with console.log? I think it's more of a debugger/developer tool rather than something that should be included in the production code. Any thoughts?

**Comment by afogelberg** [comment]
I agree that we in some cases may remove unnecessary console.log. But I would also say that in some cases it's good to get some information on what's going on without having to rely on a debugger tool other than the browser. For example if your'e not a developer and are creating an Origo map this can be helpful information regarding problems with map configuration.

**Comment by markus659** [comment]
Fair point. It might still be a big ask of Origo map creators to open the developer tools and look for log messages. Maybe we could utilize the console in the footer for some messages, and perhaps increase the use of alert for some error messages?

**Comment by afogelberg** [comment]
>  Maybe we could utilize the console in the footer for some messages, and perhaps increase the use of alert for some error messages?

Good idea. A mix of the two will certainly be useful.

**Comment by markus659** [comment]
I will close this for now as I don't think any work needs to be done, but maybe we can try to keep this in mind when coding.
