### ISSUE TITLE
crossOrigin for WMS

### ISSUE THREAD

**Issue by markus659** [origo-map/origo#267]
What is the purpose of the crossOrigin property in the WMS configuration? We noticed some problems when working on our login functionality (the WMS layers would not load), removing the crossOrigin configuration we got it to work. We are using sessions through Apache and the built-in GeoServer security options.

Can we remove this configuration option?

https://github.com/origo-map/origo/blob/master/src/layer/wms.js#L33

**Comment by afogelberg** [comment]
This property can't be removed. It's used to allow cross origin requests. An alternative is to to add an optional crossOrigin option for the source, but with crossOrigin: 'anonymous' as the default.

**Comment by markus659** [comment]
Ok, I didn't notice any difference when removing it (WMS layers works fine on localhost when using an external geoserver). In our environment we had to allow cross-origin requests on the web server, but the WMS configuration does not seem to make any difference. 

Do you have an example of an use-case where it is needed? Maybe an option to set it is the way to go, but it might be to specific? If it is needed I think we can leave it as is.

**Comment by afogelberg** [comment]
The problem appears when using getFeatureInfo.

**Comment by markus659** [comment]
Ok, thanks for clarifying. I think we can leave it then, I will close the issue.

**Comment by afogelberg** [comment]
How about crossOrigin as an option? Would that be useful?

**Comment by markus659** [comment]
I think for most everyone the way it is currently configured is the best solution. We can simply remove/comment that line for our own use, as the getFeatureInfo functionally work fine for us when running it from the server (the web server and GeoServer is on the same server, I'm guessing that's why it's working?). Debugging Origo locally getFeatureInfo doesn't work, but that's no big concern for us as it's easy to re-add the configuration when needed when you are debugging/developing. 

So I think we should leave it like it is, as I don't think many users will need to configure crossOrigin.
