### ISSUE TITLE
Allow for custom attribute templates in editor

### ISSUE THREAD

**Issue by afogelberg** [origo-map/origo#269]
In some situations it can be useful to being able to add a custom template for some special kind of attribute editing. For example I have made a template that will trigger edits in another layer. It's a very specific use case and is not suited to include in the Origo core. However the ability to add custom templates would be useful to have in Origo I think.  I was thinking something similar that as is possible to do with featureinfo templates.

**Comment by tonnyandersson** [comment]
Closed due to inactivity.
