### ISSUE TITLE
Fixed url as an attribute option

### ISSUE THREAD

**Issue by markus659** [origo-map/origo#272]
This is something we've been using in our map for a while. For some of our layers we use the same link for all features. What we used to was to populate a column with the same value for all features, but that seemed a bit unnecessary (given that the link would only be used in our web map). So what we did was to add a fixedURL attribute, that is not dependent on the values of the features, but rather only on what is  set in the configuration.

This is how it currently works for us:

https://github.com/Hallstahammarskommun/origo/blob/master/src/getattributes.js#L55-L57

https://github.com/Hallstahammarskommun/origo/blob/master/index.json#L193-L205

Do you think this is something that would be good to have as a part of the core?

**Comment by afogelberg** [comment]
Nice @markus659 . We also have the option to write custom html along with the other attributes. You could just write for example:
```
{
  "html": "<a href='http://www.hallstahammar.se/Bo-bygga/Miljo-halsa--hallbar-utveckling/eldningsforbud/'>Mer information</a>"
}
```
Do you think we need fixedUrl as well?

**Comment by markus659** [comment]
Good point, didn't think of using html. No, I don't think we need it then as it would just duplicate already available functionality and be a cause of confusion.

**Comment by afogelberg** [comment]
I will close this then.
