### ISSUE TITLE
Posibility to turn off zoom function for embeded maps

### ISSUE THREAD

**Issue by jerlob** [origo-map/origo#275]
In a webpage where you have an inbeded map you get stuck in the map zoom, instead of scrolling by in the webpage.
It would nice to be able to turn off the zooming function for embeded maps.

**Comment by jokd** [comment]
@jerlob I agree this would be a nice feature. Anybody working on a solution?

**Comment by Ssalsa** [comment]
Example to turn off mousewheelzoom function for embeded maps or for overall maps https://github.com/Ssalsa/origo/tree/275

**Comment by jokd** [comment]
I bump this. It would also be nice if you on a mobile device could scroll the page with an embedded map instead of panning the map. Maybe the way Google maps handles it with a two finger interaction.

**Comment by jokd** [comment]
I have been working a bit on this and have an ok solution, however there is nice stuff on the way to the OL library that seems to do the job:
https://github.com/openlayers/openlayers/pull/10332
I suggest we await this and see if it fulfills our demands
