### ISSUE TITLE
Legend uppside down

### ISSUE THREAD

**Issue by eriaxeba072** [origo-map/origo#278]
In the image the left legend is upside down compared to the layer order in the json-file.

![image](https://user-images.githubusercontent.com/14993796/27734593-c8a5bcde-5d9b-11e7-8096-d0e1fc046f73.png)

**Comment by jokd** [comment]
We can reorder the left legend on load by simply reversing it. But what is the expected behaviour when a layer is turned on by the user? In the bottom or on top of the left legend? Or should the left legend represent the actual draw order for the layers?

**Comment by markus659** [comment]
I like the idea of reversing it, meaning that the last layer the user made visible is at the top of the legend. I don't think it needs to follow the same order as the map menu.

**Comment by afogelberg** [comment]
> I like the idea of reversing it, meaning that the last layer the user made visible is at the top of the legend. I don't think it needs to follow the same order as the map menu.

Sounds good, lets keep it simple.
