### ISSUE TITLE
'editDispatcher' causes build to fail on case sensitive systems

### ISSUE THREAD

**Issue by Grammostola** [origo-map/origo#284]
src/editor/wfstransaction.js:7
var dispatcher = require('./editDispatcher');  (should be 'editdispatcher')
this causes issues when attempting to build with the provided script in a case sensitive environ. ("Can't find module 'editDispatcher' in editor/"). It works fine on Win. I tried it via this repo during the weekend.

**Comment by afogelberg** [comment]
fixed with 1922ff0a5ab692a7f8715c1be5dc94b53456430b
