### ISSUE TITLE
Pixel data of a cached raster

### ISSUE THREAD

**Issue by Maryzandi** [origo-map/origo#286]
When a raster layer, for example Hillshade, is cached, it becomes an image, which can be only used for visualization and the pixels information will be lost.  
The question is: Is there any way to have benefit of caching and at the same time to be able to have access to pixel data?

**Comment by afogelberg** [comment]
@Maryzandi you can define another layer that is used to request feature info from. If you have a wmts you can define a corresponding wms service for the feature info. The feature info layer is defined by adding featureinfoLayer to the wmts layer definition, for example:
```
    {
      "group": "sgu",
      "name": "jordarter",
      "source": "sgu",
      "title": "SGU jordarter",
      "type": "WMTS",
      "queryable": true,
      "style": "sgu",
     "featureinfoLayer: "reference to the wms layer"
    }
```
