### ISSUE TITLE
Pinch zoom problem in iOS 11

### ISSUE THREAD

**Issue by afogelberg** [origo-map/origo#313]
We have a really urgent problem with the latest upgrade of iOS to 11. The are big problems with pinch zoom, rotate and panning. There is a fix in the latest ol release that solves the problem, which we need to upgrade to.

**Comment by afogelberg** [comment]
I can’t verify that the problem appears on iPhone. So far I have only seen the problem on iPad.

**Comment by markus659** [comment]
I have not noticed on either the iPad or the iPhone. But it does indeed seem to be an issue with at least certain models.

**Comment by afogelberg** [comment]
At least on iPad pro and iPad mini the problem has been verified.

**Comment by markus659** [comment]
I tried it on an iPad Air 2 which seems to work.

**Comment by afogelberg** [comment]
Fixed with #316
