### ISSUE TITLE
Linear delimiter in the search result list

### ISSUE THREAD

**Issue by asemoller** [origo-map/origo#318]
When using search from multiple tables, we would like to have a linear delimiter between different sources/tables in the search result list. Something like  [Hallstakartan](https://karta.hallstahammar.se) and [Karlstadskartan](https://karta.karlstad.se).

**Comment by afogelberg** [comment]
I'm working on improving the search control, including #161 with a separate result list. Would it be sufficient to sort the result by source and enhance the search result with an icon for each cateogory/layer? This is very common, see for example hitta, Google maps and Apple maps. If the grouping is till wanted, maybe the result list in #161 can be used in combination?

**Comment by jokd** [comment]
I’d say it’s sufficient. At least for now.

**Comment by afogelberg** [comment]
Fixed with #358
