### ISSUE TITLE
Fullscreen is not loaded as a default control

### ISSUE THREAD

**Issue by markus659** [origo-map/origo#321]
Prior to renaming the fullscreen control from mapwindow, the control used to be loaded by default (in the viewer file). Currently the control is not part of the default controls, but shouldn't it be?

**Comment by afogelberg** [comment]
@markus659 yes it should

**Comment by markus659** [comment]
Alright, I figured it should. Fixed with https://github.com/origo-map/origo/commit/76cae36b8dc0354506e505dc1ba310078b6bd67d#diff-c00e44a39a22f2a081bc1c1f5dc4c289.
