### ISSUE TITLE
getFeatureInfo on vector tiles results in error

### ISSUE THREAD

**Issue by jokd** [origo-map/origo#332]
This is due to the features in a vector tiles layer are of the ol.render.Feature type and not ol.Feature and lack the clone-method. The easy solution is to make vector tiles layers not queryable.

**Comment by jokd** [comment]
The problem is the vector tiles features are clipped at the tileborders, of course, and therefore gets wrong geometries. IF we are to make vector tiles layers queryable, one solution is to query another vector source.

**Comment by tonnyandersson** [comment]
@jokd Is this still an issue?

**Comment by jokd** [comment]
No it’s not since we dropped support for vector tiles in v2.

**Comment by tonnyandersson** [comment]
Did we? Looks like it's still a valid layer type.

**Comment by jokd** [comment]
Thought so... But I might be wrong. I can have a look.

**Comment by jokd** [comment]
Vector tiles are still functioning if you add resolutions to the tileGrid option for the source. However this issue remains so we can keep it open.

**Comment by tonnyandersson** [comment]
@jokd Any progress on this?

**Comment by jokd** [comment]
No and the vector tiles handling probably needs an overhaul so we can close this for now.
