### ISSUE TITLE
Drag-and-drop control

### ISSUE THREAD

**Issue by markus659** [origo-map/origo#351]
OpenLayers has an interaction for drag-and-drop support. I think we should add this as a control to Origo. It makes it super easy to view and identify features by simply dragging the file(s) to the map. If, for instance, you want to view a file it might be easier to view it in an Origo-map than to have to open some GIS desktop software and manually load the background maps, layers etc. that you already have configured in your web map application. 

I've added a gif animation below to demonstrate how it works. Is this something that we want to add support for?

![dragandrdrop](https://user-images.githubusercontent.com/15904932/32879585-e1320e34-caaa-11e7-88f8-60dddfd12e96.gif)

**Comment by afogelberg** [comment]
Good idea @markus659 . This is something I have been considering as an enhancement for the draw control I have been working on. It would be nice to be able to drag and drop data and then make some edits and then being able to download the edits.

**Comment by markus659** [comment]
Being able to edit the data would make it extra interesting indeed. If you incorporate drag-and-drop functionality into the draw control, it would be enough to have it as a part of that control.

**Comment by afogelberg** [comment]
@markus659 I think we can have drag and drop as a separate control. I can then add a listener for drag and drop events in the draw control.

**Comment by jokd** [comment]
This looks like a great addition to Origo. Really useful.
