### ISSUE TITLE
Drag and drop on layers

### ISSUE THREAD

**Issue by daRasmussen** [origo-map/origo#359]
I would like to suggest a feature for the layer manger to be able to handle layer position with drag and drop functionallity.

**Comment by markus659** [comment]
Thanks for the issue @daRasmussen. I guess this has to do with wanting to control the draw order (maybe that's what you mean by layer position)?

**Comment by daRasmussen** [comment]
Yes. Control for draw order @markus659

**Comment by afogelberg** [comment]
@daRasmussen @markus659 are we talking about draw order within a group? Within a group the order in the menu corresponds to the draw order in the map, but not necessarily between groups. And also subgroups are always placed in top of the group, thus not the same order as drawn in the map.

**Comment by markus659** [comment]
I was thinking between groups as well, but that might be hard to configure then considering the draw order isn't the same as the order that the layers are listed in the menu. Maybe some function where you can move layers to the top of the draw order? Might not be so easy to implement in a way that's intuitive to use , but certainly I can see it being useful in some cases.

**Comment by afogelberg** [comment]
If we want to change the draw order I suggest we do it in the map legend only. That will be easier to make logical. If we have drag and drop in the menu I suggest it doesn’t change draw order.

**Comment by markus659** [comment]
That makes sense @afogelberg, What do you think about having the functionality in the map legend instead @daRasmussen?

**Comment by daRasmussen** [comment]
@markus659 that sounds good to me.

**Comment by daRasmussen** [comment]
I will close this issue since the layer handler is reworked after v2.0.0 and this feature is a bit obsolete due to that change.
