### ISSUE TITLE
Crosshair z-index

### ISSUE THREAD

**Issue by mulfvik** [origo-map/origo#368]
This is off course a subjective point of view but i think it would be prettier if the crosshair is below the modals.

**Comment by afogelberg** [comment]
Agreed. Are you up for a PR @mulfvik ?

**Comment by mulfvik** [comment]
@afogelberg Jupp

**Comment by markus659** [comment]
@mulfvik another thing you might be able to add to the same PR is adding:

```css 
pointer-events: none; 
```
to the position-marker div so that the user is able to click and and use the scroll wheel when the pointer is placed at the crosshair.

**Comment by mulfvik** [comment]
Addressed with #376
