### ISSUE TITLE
Full screen modal with iframe

### ISSUE THREAD

**Issue by jokd** [origo-map/origo#381]
It would be nice to be able to open links as iframes inside a modal, preferably full screen.
We have been using colorbox but it would be better with something in the Origo core.
Thoughts on this?

**Comment by tonnyandersson** [comment]
I'm all for it! But I think full screen mode should be optional, with an "Open in full screen"-button or something.

**Comment by afogelberg** [comment]
Does it have to be iframe? It would be nice to have it either as an iframe or js.

**Comment by jokd** [comment]
Not necessarily, but at least.
I will look into a solution soon.
