### ISSUE TITLE
Setting pixelRatio to 1 on the map?

### ISSUE THREAD

**Issue by afogelberg** [origo-map/origo#382]
Would anyone mind if we set the pixelRatio to 1 for the map? Setting the pixelRatio to 1 will help to preserver quality of the map if the browser is zoomed and when calculating the proper size of the map when the browser is zoomed.

I can only see that it would be an improvement, but maybe I'm missing something?

**Comment by tonnyandersson** [comment]
Hardcoding pixelRatio = 1 for the map will make it impossible to implement support for retina tiles in the future. It would also have a negative impact on vector feature rendering on high-DPI screens.

**Comment by afogelberg** [comment]
You're right, this is indeed undesirable. Thanks @tonnyandersson . I will solve calculating the map size in another way than with map.getSize() which isn't accurate for zoomed in browsers.
