### ISSUE TITLE
Service-based multisearch tool

### ISSUE THREAD

**Issue by tonnyandersson** [origo-map/origo#388]
A multifunctional search with autocomplete that gives you the address, area or property number using Lantmäteriets search function. It is also possible to define which municipalities the search engine should operate on.

Based on an older Origo search version and developed for the Open eMap version of Origo.

**Comment by afogelberg** [comment]
Is this server side or client side?

**Comment by tonnyandersson** [comment]
Server side. It seems to utilize a custom made server side script (SearchLM), made specifically for queries against Lantmäteriets search services. I.e. not using Origo server.

Is the Origo search/Origo server equipped for this?

**Comment by afogelberg** [comment]
This could definitely be added to Origo server.

**Comment by tonnyandersson** [comment]
So, it is not possible to utilize LM search services directly via Origo server today?

The thing is, the custom made script I mentioned is not just a script, it's apparently an entire Java based service, acting as middleman. Perhaps it would be better to write a pure Origo server solution?

**Comment by johnnyblasta** [comment]
A Origoserver solution is now done replacing the old Java solution and utilises oauth.

Left to do is a plugin for Origo that use the origoserver api.

**Comment by johnnyblasta** [comment]
This is now fixed with the implementation in Origoserver and lmsearch-plugin.
All future issues with this can be handle in respective repo.
