### ISSUE TITLE
Draw function

### ISSUE THREAD

**Issue by tonnyandersson** [origo-map/origo#389]
Lets the user draw a line, a point or area or text in the map. These objects will disappear when you hide the draw-tool.

Developed for the Open eMap version of Origo.

**Comment by afogelberg** [comment]
Duplicate of #193 ? As I understand the Open eMap control is based on https://github.com/origo-map/origo/tree/draw

**Comment by tonnyandersson** [comment]
@afogelberg You're right, it is a duplicate, with a few additions to the original code.

**Comment by afogelberg** [comment]
Can we close this then?

**Comment by tonnyandersson** [comment]
I guess so.
