### ISSUE TITLE
Default Geoserver SLD style for WMS

### ISSUE THREAD

**Issue by tonnyandersson** [origo-map/origo#397]
If a layer does not have a set style in the config file, the layer will be rendered with its default GeoServer SLD style.

Developed for the Open eMap version of Origo.

**Comment by tonnyandersson** [comment]
Closed in #611

**Comment by daRasmussen** [comment]
PR #611 I suggest to revise this pr since it alters "old" wms configurations which is not desired. I would suggest to make this setting optional.

**Comment by tonnyandersson** [comment]
Closed due to inactivity and the fact that this doesn't seem to be an issue.
