### ISSUE TITLE
Service-based on-click feature info

### ISSUE THREAD

**Issue by tonnyandersson** [origo-map/origo#398]
A service-based feature info function requesting feature info from an external service rather than a map layer.

**Comment by jokd** [comment]
I will have a look at this.

**Comment by tonnyandersson** [comment]
@jokd Still looking at this?

**Comment by jokd** [comment]
No I'm not.
Useful feature though ;)

**Comment by tonnyandersson** [comment]
Closed due to inactivity. Labeled as archived since it's still a good idea.
