### ISSUE TITLE
Readme file lacks description

### ISSUE THREAD

**Issue by afogelberg** [origo-map/origo#4]
Currently there is no project description for Origo. This needs to be added.

**Comment by markus659** [comment]
I can at least start by doing a draft/outline for the readme file, unless someone else has already started working on this issue?

**Comment by afogelberg** [comment]
Go for it!

**Comment by markus659** [comment]
I've created [a new branch](https://github.com/origo-map/origo/tree/Updated-README) for the updated readme-file. I added a few suggestions for headings. It is still missing a few things:

* There's an reference to guidelines, but there are no guidelines added yet.
* It also references a license file which also doesn't exist as of yet.
* Maybe a logo at the top?
* Might need some more text

@afogelberg @jokd could you take a look at the updated readme?

**Comment by afogelberg** [comment]
Nice work @markus659 Looks really good. We have a license file, maybe we can point to that in the meantime? I think we should make the requirements section a bit more clear, node.js is required for development but not for deployment if using release (when we have one).

Please create a pull request and merge.

**Comment by jokd** [comment]
I think it looks great. Perhaps the links that are not yet valid should be removed to avoid confusing.
@afogelberg has created a awesome logo :)

**Comment by afogelberg** [comment]
I will try to find the logo :) Agree with @jokd that it is best to remove the invalid links for now,

**Comment by markus659** [comment]
Thank you for the feedback. I removed invalid links and references. I'm not sure what you meant by pointing to the license file @afogelberg, but I added a link to it. I also removed the "requirements" section for now.

**Comment by afogelberg** [comment]
Looks good to me!

**Comment by afogelberg** [comment]
Can we merge your branch @markus659 ? It looks good to me.

**Comment by markus659** [comment]
Yes, you can go ahead and merge @afogelberg (you can remove the branch as well). I also added a link to Sigtunakartan and fixed the URL to Västerås Stads samlingskarta.
