### ISSUE TITLE
Search suggestion bug

### ISSUE THREAD

**Issue by markus659** [origo-map/origo#425]
Currently the search shows suggestions even if there are no matches. For instance, if you search for "drott" you get suggestions like "drottningatan", which is expected. However, if you write "drott1", you would still get suggestions from the previous response, so "drottninggatan" would still show up.

This becomes a problem when trying to actually zoom to the feature, I believe this is because the latest response from the server is empty (no hits for "drott1"). You will get an error in the developer console. It's possible to reproduce on any maps using the new awesomplete search, like http://kartor.vasteras.se/sam/ or https://karta.enkoping.se.

**Comment by AgatonSax** [comment]
I vote for the solution @markus659 proposed. If the user inputs a search string with no matches, the expected result is a list of search hits with no matches. I fail to see the logic in showing a list of search hits from a previous search, as discussed in #426.

Also when first doing a search with matching results, removing all of the search query with backspace (for instance) and then typing something with no matches you still get the previous list of search hits.
![image](https://user-images.githubusercontent.com/5526928/67944821-b71d3680-fbdd-11e9-87ba-b94356f73c2b.png)

Also the UI visual state after backspace-clearing the query and pressing the X-button to clear search, are (misleadingly) the same. Pressing X-button triggers clear search db, while removing query with backspace keeps the list of search hits.

**Comment by Grammostola** [comment]
Markus' suggestion (in the closed PR) appears to do the right thing; "Drott" gives hits, "DrottTheFlyingDutch,.." does not, erasing the input field and typing "TheFlyingDutch.." does not show any hits. 

I.e, in src/controls/search.js:initAutocomplete()
`
    awesomplete = new Awesomplete('.o-search-field', {
      minChars: minLength,
      autoFirst: false,
      sort: false,
      maxItems: limit,
      item: renderList,
      filter(suggestion, input) {
        if (suggestion.value.toLowerCase().includes(input.toLowerCase())) {
          return suggestion.value;
        }
      }
    });`
