### ISSUE TITLE
Awesomplete list unseen

### ISSUE THREAD

**Issue by mulfvik** [origo-map/origo#442]
On small devices there is parts of the searchlist that is unreachable if the list is too long because of virtual keyboard that cant be closed.

**Comment by mulfvik** [comment]
@daRasmussen @johnniehard @jokd @markus659 @tonnyandersson Any thoughts on this?

**Comment by daRasmussen** [comment]
@mulfvik could you provide a screenshot?

**Comment by mulfvik** [comment]
![Screenshot_2019-05-29-22-15-53](https://user-images.githubusercontent.com/24228538/58636950-b3fde180-82f1-11e9-91ab-ec4b9c13019f.png)
In this case i cant get hold of half the list. If I close the texteditor the input closes.

**Comment by daRasmussen** [comment]
Good issue! I guess this could be solved with max results options depending on viewport (dynamically). Or just enable scroll in the list (override origo css). What I would recommend is a option to choose between Fastighet or Adresser (enhance search). But the optimal solution would be to display: 

A Hamn...
F Hamn....

A, F could be icons. 

Anyway there are a lot of options, what would be the optimal entry?

**Comment by mulfvik** [comment]
@daRasmussen Creative thoughts, a enhanced search would be a good solution and configurable if options are added. Found this old issue that might be useful #161. 
Enable scroll is a quick and solid fix for most, or even, all kinds of units which I like. Could even do a customized one.
We could do that fix first and then take a survey if anyone is up for the enhanced search PR?

**Comment by daRasmussen** [comment]
@mulfvik sound good to me.

**Comment by mulfvik** [comment]
I have a new phone and this issue is handled with an option to close the texteditor without closing the search responses. 
I will close this and reopen if...
