### ISSUE TITLE
Add round2 to utilities.

### ISSUE THREAD

**Issue by daRasmussen** [origo-map/origo#443]
It would be nice with a round function in utils that handles the floating point error.

**Comment by jokd** [comment]
@daRasmussen I had to fix a couple of lines to get it working. Also this needs to be updated to ES6. 
When can the floating point error occur and you want to use this util?

**Comment by daRasmussen** [comment]
@jokd tnx for response the ES6 update is in progress. Floating point error can occur for example if the measure tool is extended to handle multiple unit sets or during multiple precision sets. I found it useful when I remastered or extended the measure tool.
