### ISSUE TITLE
Adding OpenLayers map options

### ISSUE THREAD

**Issue by afogelberg** [origo-map/origo#452]
We need to enable more OpenLayers map options to viewer, for example loadTilesWhileInteracting and loadTilesWhileAnimating,

**Comment by mulfvik** [comment]
As from release 6.0.0 

> Always load tiles while animating or interacting
> ol/PluggableMap and subclasses no longer support the loadTilesWhileAnimating and loadTilesWhileInteracting options. These options were used to enable tile loading during animations and interactions. With the new DOM composition render strategy, it is no longer necessary to postpone tile loading until after animations or interactions.
