### ISSUE TITLE
Combining Styles, Circle + Text, mapmenu problem

### ISSUE THREAD

**Issue by Flodkvist** [origo-map/origo#465]
There is a problem with the legend in mapmenu when combining circle and text styles .

Scenario 1:
Combination style, circle declared first, text second 
--> The layer is not visible in mapmenu-legend at all and get  a jQuery exception in console.

Scenario 2 (see code example at bottom):
Combination style, text declared first, circle second 
--> The layer is visible in mapmenu-legend with toggle function, but "style-part" is missing.

-------------------------------------------------------------------------------

Note: Tested using combination style with circle + circle, 
-> Worked fine. 

Note:  The code example contains "text": "{{text}}", to use feature attribute.
-> Tried using simple textstring with same result.

Note: The features are always rendered correctly in the map.

Origo version: Master 2018-07-16

Example Style
```
"cirkel_m_text": [
	[{
		"text": {
			"font": "Bold 12px Verdana",
			"textAlign": "center",
			"offsetY": -17,
			"text": "{{text}}",
			"fill": {
				"color": "rgba(0,0,0,1.0)"
			},
			"stroke": {
				"color": "rgba(255,255,255,0.7)",
				"width": 4
			}
		}
	}, {
		"circle": {
			"radius": 8,
			"stroke": {
				"color": "rgba(51,51,51,1)",
				"width": 2
			},
			"fill": {
				"color": "rgba(0,177,89,0.7)"
			}
		}
	}]
]
```

**Comment by daRasmussen** [comment]
I could reproduce both errors and resolved them with the following declaration.
```
"cirkel_m_text": [ 
  {
     "text : { ... stroke ... },
     "circle": { ... }
  }
]
```
![image](https://user-images.githubusercontent.com/33061427/42759663-108ea5e0-8908-11e8-91b0-0d13b128a086.png)

Not sure if this is the desired style.

**Comment by Flodkvist** [comment]
Nice!
Thank you, this is the desired style.

Seems like this solution differs from the example in the documentation. 
https://origo-map.github.io/api-documentation/latest/#combining-styles

Or am I reading it wrong... ?

**Comment by daRasmussen** [comment]
@Flodkvist I can agree on that the documentation does not deal with this specific issue. I also think this issue raises a greater question on:  _How should Origo handle visualizing combined styles in the legend?_ I made a PR that complies better with the documentation, but does not for fill it completely so this functionality could be extended and built on even more if needed.
