### ISSUE TITLE
mapmenu options, "isActive: true" not working

### ISSUE THREAD

**Issue by Flodkvist** [origo-map/origo#466]
The mapmenu is collapsed when map loads, regardless of value in isActive option.

Origo version: Master 180716

**Comment by daRasmussen** [comment]
@Flodkvist does PR #467 resolve this issue?

**Comment by Flodkvist** [comment]
@daRasmussen yes.
Made a build with your changes, it works good.

**Comment by MattiasSp** [comment]
This seems to be an issue again in a more current version, I looked at e.g. https://gi.karlstad.se/ where it doesn't seem to work on my screen. Not sure what version is running there.

**Comment by jokd** [comment]
I guess you are on a mobile device where it is not supposed to be working that way. You can alter the breakpoints to make it behave as on desktop if you prefer that.
