### ISSUE TITLE
Carousel problem for overlay in IE 10

### ISSUE THREAD

**Issue by afogelberg** [origo-map/origo#49]
Clicking next or previous buttons in carousel in IE 10 causes a click event in the map. The cause has been identified as a regression in OL: https://github.com/openlayers/ol3/issues/5478

**Comment by markus659** [comment]
The issue in OL is supposedly fixed (https://github.com/openlayers/openlayers/pull/6610). I tried it with IE10 in a virtual machine and it seems to work, so we should be able to close this issue..?

**Comment by afogelberg** [comment]
I can verify that it works now, thanks for noticing @markus659 .
