### ISSUE TITLE
Add additional sources

### ISSUE THREAD

**Issue by daRasmussen** [origo-map/origo#490]
It would be nice to be able to configure a layer so that it can handle additional requests and add external sources like attributes to a selected feature. 

Something like this: 

```
"sources": [{
    "url": "https://... ",
    "attributes": [{
       "title": "title",
	"name": "id"
    }]
}]

**Comment by tonnyandersson** [comment]
@daRasmussen Is this still an issue or can we close it?

**Comment by daRasmussen** [comment]
@tonnyandersson you can close.
