### ISSUE TITLE
Consistent if operations in getfeatureinfo.js

### ISSUE THREAD

**Issue by daRasmussen** [origo-map/origo#492]
getfeatureinfo.js contains an unnecessary equal to operation. For consistency it would be nice to remove it.

line 155 (comment above 'If crossOrigin is not supported and canvas not tainted'). Why? See line 138 (comment below 'If layer is tainted, then create request for layer') witch is more clean.

**Comment by tonnyandersson** [comment]
Closed due to inactivity.
