### ISSUE TITLE
Issue with build/js/origo.js

### ISSUE THREAD

**Issue by jokd** [origo-map/origo#495]
The webpackified origo.js in build/js referenced from index.html after running the build script should be omitted and instead we should use the origo.min.js

**Comment by tonnyandersson** [comment]
@jokd Is this still an issue?

**Comment by jokd** [comment]
I think so. Can look into it.

**Comment by jokd** [comment]
Seems to work, however the origo.js is not very nice to read or debug but that is maybe another issue that can ease developing. Im closing this.
