### ISSUE TITLE
Disable group visibility toggle

### ISSUE THREAD

**Issue by tonnyandersson** [origo-map/origo#502]
Today, the user can toggle all layers within a subgroup on or off simultaneously by clicking the subgroup checkbox. This non-configurable default behavior can cause serious performance issues if a user tries to switch on a subgroup filled with, for example, large raster layers.

I suggest making this behavior configurable, preferably on application level in order to maintain consistency thoughout the map menu.

**Comment by asemoller** [comment]
Maybe this can be easily fixed now that exclusive groups have that function? At least at the group level?

**Comment by tonnyandersson** [comment]
@asemoller Something like this, right?

![toggle_all_false](https://user-images.githubusercontent.com/15725608/125916117-d0823e27-e902-4ad4-92a0-8ddebefb2683.gif)

**Comment by asemoller** [comment]
Yes @tonnyandersson!
