### ISSUE TITLE
Option to group layer in the drop down editor menu

### ISSUE THREAD

**Issue by sonjahalmstad** [origo-map/origo#505]
It would be nice to be able to group editable layers in the drop down list in the editor menu. Or ever better,  make a function that can sort out and show only layers you are entitled to edit. This would be useful when having several layers with different users.

![snipimage](https://user-images.githubusercontent.com/14833158/45952289-c6a77480-c006-11e8-9e67-a3998e0cde36.JPG)

**Comment by tonnyandersson** [comment]
Closed due to inactivity. Labelled _archived_ since it's still a good idea.
