### ISSUE TITLE
FME data export plugin/module

### ISSUE THREAD

**Issue by Grammostola** [origo-map/origo#507]
An FME (server) export function for configurable data sources, where the extent to be exported is indicated on the map.

**Comment by afogelberg** [comment]
A download function seems interesting. It would also be nice if we could make this control generic, so it could be any backend of choice. I guess a request is made to FME Server with maybe layer name and extent?

**Comment by Grammostola** [comment]
Kind of. Workspace to execute and extent and email of orderer. We've put what Sweco developed in a branch: https://github.com/Eskilstuna-kommun/EK-extern/blob/feature-fme-export-module/src/export.js . Tentatively we'd like to see something like it work with Origo 2.

**Comment by Grammostola** [comment]
And now our MDH student summer-workers have developed it into a plugin (for Origo v2 as such): 
https://github.com/Eskilstuna-kommun/Geouttag

**Comment by tonnyandersson** [comment]
Exists as plugin. See PLUGINS.md (coming soon) for more information.
