### ISSUE TITLE
Integration with BlomUrbex

### ISSUE THREAD

**Issue by asemoller** [origo-map/origo#509]
A simple integration using a link to BlomUrbex using center coordinates.
Perhaps this can be a generic config so it can be linked to any other website such as google street view or Mapillary. 

Should this function be reachable under the legend or as a tool?

**Comment by afogelberg** [comment]
Do you have an example for the link?  Center coordinates are already available as a function in featureinfo and can be used to build url:s.

**Comment by asemoller** [comment]
This is an examples of a url in lat/long: "http://www.blomwebviewer.com?lat=59.61&lon=17.81&zoom=20&view=SINGLE".

**Comment by afogelberg** [comment]
If implemented as a plugin/control this could be achieved quite easy with current functionality in Origo. I agree it would be nice to make this generic and constructing the url in a similar way as for a feature, Maybe with an option to define a button icon?
