### ISSUE TITLE
Changing center coords in position tool not working

### ISSUE THREAD

**Issue by tonnyandersson** [origo-map/origo#512]
Changing center coordinates by changing the coordinates in the position tool results in an error. This is due to a logical error in the **validateCoordinate**-function in **position.js**. The condition in the if statement should be negated.

From this...
```javascript
let coords = strCoords.split(',').map(coord => parseFloat(coord))
    .filter((coord) => {
      if (Number.isNaN(coord)) {
        return coord;
      }
      return null;
    });
```
...to this...
```javascript
let coords = strCoords.split(',').map(coord => parseFloat(coord))
    .filter((coord) => {
      if (!Number.isNaN(coord)) {
        return coord;
      }
      return null;
    });
```

Or simply switch the return values.

**Comment by markus659** [comment]
I noticed this recently as well. It is fixed in the cu-branch: https://github.com/origo-map/origo/blob/cu/src/controls/position.js#L105

**Comment by tonnyandersson** [comment]
Great! I'll let this issue hang around until the cu-branch is merged.

**Comment by jokd** [comment]
Can we close this?

**Comment by markus659** [comment]
Yes, I'll close it.
