### ISSUE TITLE
WMS poly layer with transparency means no getFeatureInfo when clicked

### ISSUE THREAD

**Issue by Grammostola** [origo-map/origo#513]
Repro steps:
-Download latest master, define a WMS service source and layer, some style, npm run start,
-Show this polygon layer which has a transparent or semitransparent* fill in the Origo map and click on a transparent part of said fill to get information

-> No request is sent.
expected: request is sent regardless of style

(Please enlighten me if I've missed something :)  ) 

(*By "semitransparent" i mean for example a striped fill pattern where parts are wholly translucent, I don't mean that the whole fill is semi-translucent. A request is sent when clicking semi-translucent poly fill parts)

Edit2. It doesn't matter whether WMS service is provided by Geoserver or ArcGIS Server

**Comment by tonnyandersson** [comment]
On click, Origo (or Openlayers, to be precise) collects each layer hit _at the clicked pixel_. Now, if you click on a completely transparent part of a feature, the clicked pixel will not contain any color information and will be regarded as empty, i.e. not a layer.

One way to fix this would be to send a request to your map server of choice _for each visible layer_ everytime you click the map, asking for features at the given coordinate. That's potentially a whole lot of requests and something we try to avoid.

There is, however, a nifty little workaround. When styling the layer, do not make it _completely_ transparent. Always make sure there is at least some color information left in the pixels by setting the opacity to, say, 0.01. That way, the layer will look transparent, but it isn't.

**Comment by Grammostola** [comment]
Hi, yep, that's the workaround we are employing at the moment, i.e  semi-translucency. It works quite well. As this then is an issue (depending on how you view it) for OpenLayers, then this issue here can be closed. (Unless Origo would send one request querying several layers, which might not be entirely practical)
