### ISSUE TITLE
Extent for XYZ-layer not respected

### ISSUE THREAD

**Issue by jokd** [origo-map/origo#515]
Setting the extent for a XYZ layer is not considered in some cases hence the layer is cut to map extent. A working fix is add 
`opt.extent = source.tileGrid.extent`
in src/layer/tile.js 
Haven't looked into it much though.

**Comment by tonnyandersson** [comment]
@jokd Is this still an issue?

**Comment by jokd** [comment]
Yes. Could easily be fixed though.

**Comment by jokd** [comment]
This seems reduntant after all, closing it.
