### ISSUE TITLE
Open editor attributes in sidebar

### ISSUE THREAD

**Issue by jokd** [origo-map/origo#517]
It would be nice to be able to open the editors attribute form in the sidebar so you can move the feature and edit attributes at the same time. The sidebar could also auto-open when selecting a feature just like infoclicking.

**Comment by tonnyandersson** [comment]
@jokd Any progress on this?

**Comment by jokd** [comment]
None so far. I still think its a nice feature but haven't had a reason to fix it. But I guess we can close this since it's 4 years old.

**Comment by tonnyandersson** [comment]
Perhaps slap an _archived_ label on it and close?
