### ISSUE TITLE
Splash uses unnecessary render dispatch

### ISSUE THREAD

**Issue by markus659** [origo-map/origo#544]
Since splash is basically just an modal window which is created on load, the render dispatch seems unnecessary. When 
````js 
this.dispatch('render');
````
is run in splash, it will make onRender run again for the modal control, causing the click listener to be added twice. This causes an error when trying to click outside the modal window to close it, as it tries to remove something that was already removed.

**Comment by tonnyandersson** [comment]
LGTM
