### ISSUE TITLE
First geometry in empty layer crashes editor

### ISSUE THREAD

**Issue by daRasmussen** [origo-map/origo#546]
I think there is a bug in the editor which makes it impossible to create the first feature if the layer is empty.

**Comment by daRasmussen** [comment]
@jerlob tnx for your input! 

```
"geometryType": "Point" 
````
It would be nice if this was the default behavior though.

**Comment by tonnyandersson** [comment]
I think it's not possible to set a default value for geometry type. At least it would not be very practical.

It seems the draw interaction *requires* a geometry type. If `geometryType` is not defined in the config, Origo will get the geometry type from the first feature in the layer. But if there are no features, `geometryType` will remain undefined and the draw interaction will break.

The draw interaction will only accept one out of a limited set of geometry types ([list here](https://openlayers.org/en/latest/apidoc/module-ol_geom_GeometryType.html)), with the most "generic" one being `GeometryCollection`.

So, AFAIK, it is not possible to set a generic default value - like `geometry` - if `geometryType` is undefined. And setting `Point` or something as default value would just be wrong.

@daRasmussen, have you thought of a different solution to this, or can we close this?

**Comment by jokd** [comment]
Now that you have tracked down the issue, perhaps write some lines to alert the users why they arent able to edit?
