### ISSUE TITLE
Value 0 is interpreted as undefined

### ISSUE THREAD

**Issue by daRasmussen** [origo-map/origo#547]
If attribute value is null or a number (not string) it does not show in the popup which can be misleading.

**Comment by johnnyblasta** [comment]
I'm stil having problem when attribute value is 0 it writes out nothing instead of a zero.
I've made a fix, so it works for me, but wonders if I made something wrong when it should have been fixed before?
I also made a fix for writing out the attribute value as text, since it was missing there to.

**Comment by johnnyblasta** [comment]
I have this layer which contains a attribute that sometimes contains 0 as a value:

`  "layers": [
    {
      "name": "snowheight",
      "title": "Snödjup Sundsvall",
      "group": "iot",
      "source": "https://kartatest.sundsvall.se/origoserver/iotproxy/?q=snowHeight",
      "style": "snowflake",
      "visible": true,
      "type": "GEOJSON",
      "attributes": [
        {
          "name":"snowHeight",
          "title": "Snödjup: "
        }
      ]
    },`

With this style:
`"snowflake": [
        [
          {
			"label": "Snödjup",
			  "text": {
				"font": "Bold 12px Arial",
				"textAlign": "center",
				"offsetX": -35,
				"offsetY": 0,
				"text": "{{snowHeight}} cm",
				"fill": {
				  "color": "rgba(0,0,0,1.0)"
				},
				"stroke": {
				  "color": "rgba(255,255,255,0.7)",
				  "width": 2
				}
			  }
			}
        ]
      ]`

When the attribute is 0 there is no value written:
![image](https://user-images.githubusercontent.com/48793206/79450371-239dbd80-7fe5-11ea-9bd8-f4000dedd585.png)

And in the popup it is also missing:
![image](https://user-images.githubusercontent.com/48793206/79450551-4def7b00-7fe5-11ea-9bd5-c83bb7b61950.png)

As supposed to when the value is not 0:
![image](https://user-images.githubusercontent.com/48793206/79450729-93ac4380-7fe5-11ea-8fb3-7fe46e118634.png)

Is it something I've missed or was it not fixed the first time?
