### ISSUE TITLE
origo variable

### ISSUE THREAD

**Issue by daRasmussen** [origo-map/origo#554]
I am missing an import statement here like: 
```
import origo from '../origo';
````
https://github.com/origo-map/origo/blob/c27ba8fc91322853f7da4a921cb0b5f2fa4faca8/src/controlinitialiser.js#L1-L17

Code works without this statement but I think its better to be explicit in source.

**Comment by afogelberg** [comment]
@daRasmussen I would be careful doing this as it would cause a circular dependency. It could however be a good idea to check if there is a global origo. This would however require to disable eslint on that row.

**Comment by daRasmussen** [comment]
Closing this issue since controlinitilizer is not used anymore see #638
