### ISSUE TITLE
Authorization problem in Origo 2.0.0?

### ISSUE THREAD

**Issue by asemoller** [origo-map/origo#555]
When using authorizationUrl in index.html or just using wms/wfs services with authorization (from geoserver), Origo will not trigger a authorization window for login. It works fine in Origo 1 but not in Origo 2.0.

**Comment by jokd** [comment]
Tried this stup:
		var origo = Origo('index.json', {
		authorizationUrl: '//geoserverurl/wms?SERVICE=WMS&VERSION=1.1.1&REQUEST=GetMap&FORMAT=image%2Fpng&TRANSPARENT=true&STYLES&LAYERS=workspace:3Alayername&SRS=EPSG%3A3008&WIDTH=330&HEIGHT=768&BBOX=153210.26189480544%2C6610525.868478608%2C153210.4541248935%2C6610526.315850449'
	});
And it triggered an user/password prompt. Perhaps you are having CORS-issues? Are webserver and geoserver on same domain?

**Comment by asemoller** [comment]
It seems to be a geoserver issue.
Thanks for your help. I will closed this.

**Comment by mulfvik** [comment]
@asemoller  Having problems with the auth as well. Did you find a solution? Have not changed any config, nor environment
