### ISSUE TITLE
Only featureinfo responds to 'toggleinteraction' event

### ISSUE THREAD

**Issue by imantahriri** [origo-map/origo#572]
If a 'toggleinteraction' event is triggered all other interactions are supposed to get deactivated. And this was how it worked in the previous version, but now only featureinfo listens and reacts to this event. This means that if other modules or controls use interactions the other interactions remains active which is a strange behavior.
Measure control, Draw control, and Multiselection control are those who use ol interactions as far as I am concerned.
How do we solve this?

**Comment by jokd** [comment]
Sounds like a bug, you never want more than one interaction at a time, right?

**Comment by imantahriri** [comment]
@jokd Yes, exactly. Only one interaction at a time should be active.
