### ISSUE TITLE
Trackpad zoom not working in Edge or IE

### ISSUE THREAD

**Issue by jokd** [origo-map/origo#577]
I am unable to zoom the map with the trackpad. This occurs in both Edge and IE.

**Comment by markus659** [comment]
Trackpad zoom works for me in Edge. In IE I couldn't get it to work, but it also didn't work with a map using an earlier version than 2. Could it not working in Edge have been device specific? Some more input from other users would be interesting.

**Comment by daRasmussen** [comment]
Tested on 2 computers and it works for me in Edge but not in IE.

**Comment by jokd** [comment]
Got it working in Edge after altering some settings in Windows. So I close this issue despite not working in IE.
