### ISSUE TITLE
Low contrast between controlbuttons and some bg maps

### ISSUE THREAD

**Issue by mulfvik** [origo-map/origo#581]
It could be beneficial if there is more shadow on the controlbuttons or a border on them buttons.

**Comment by jokd** [comment]
I agree that the buttons gets a bit discrete when using for instance the topowebbkartan nedtonad background. It would be nice to have different "themes" to choose from, maybe even connect a theme to a certain background map.

**Comment by mulfvik** [comment]
Love that idea.

**Comment by tonnyandersson** [comment]
Related to #621.
