### ISSUE TITLE
Lefthand tools top-margin

### ISSUE THREAD

**Issue by mulfvik** [origo-map/origo#587]
There is a little bit of margin at the top on the zoom-buttons that makes it not aligned with search box and menu.

**Comment by jokd** [comment]
You are right, the zoom button container should have no margin-top.

**Comment by tonnyandersson** [comment]
@mulfvik, @jokd Agree with both.

Also, the gap between the measure control and the geopositioning control is wider than the gap between the other controls. In my opinion, the gap should be equally wide between all controls. Perhaps that could be addressed in this issue as well.

![image](https://user-images.githubusercontent.com/15725608/54680401-03fa4400-4b0a-11e9-895d-c3eba918326d.png)

**Comment by mulfvik** [comment]
There is a new PR for this issue  #711
