### ISSUE TITLE
Change units for lenght measurement

### ISSUE THREAD

**Issue by asemoller** [origo-map/origo#592]
We want to change the measure control for lenght to activate the switch from meters to kilometers at 1000m, not 100m.

    if (length > 1000) {
      output = `${Math.round((length / 1000) * 100) / 100} km`;
    } else {
      output = `${Math.round(length * 100) / 100} m`;
    }

**Comment by jokd** [comment]
I support that

**Comment by markus659** [comment]
Yeah, makes sense.

**Comment by tonnyandersson** [comment]
Agree. Perhaps a PRA label on this one then?
