### ISSUE TITLE
The menu appears under the legend

### ISSUE THREAD

**Issue by asemoller** [origo-map/origo#597]
If you have the legend open and then select the menu, the menu appears under the legend (in that the legend obscures the open menu). A simple solution is to have the opposite happen; ie the menu appear over the legend. Another solution could be auto-closing the legend when the menu is opened. The latter solution is to be prefered.

![image](https://user-images.githubusercontent.com/17123002/55733601-64e8ae00-5a1e-11e9-97ab-5bc84a05ec88.png)

**Comment by daRasmussen** [comment]
auto-close ftw!

**Comment by jokd** [comment]
Despite @daRasmussens enthusiasm we have decided to go for the option where the menu overlap the legend. That is because you often want the legend to be permanently visible so collapsing it with the menu button could be annoying, especially when they don't overlap at all.

**Comment by asemoller** [comment]
Is this soon to be solved with suggested solution?

**Comment by jokd** [comment]
@asemoller This can be solved by rearrange the controls in the config json. Put legend before mapmenu and it will be rendered below.
Is this solution good enough or should it be more solid?

**Comment by asemoller** [comment]
Maybe we can close this? @jokd

**Comment by jokd** [comment]
@asemoller I think so. Will you add a note in the documentation about it?

**Comment by asemoller** [comment]
Sure, I  will add a text about it! see https://github.com/origo-map/api-documentation/issues/50
