### ISSUE TITLE
Editor: To select feature covered by other feature of same layer seems impossible

### ISSUE THREAD

**Issue by Grammostola** [origo-map/origo#612]
Tested a build of today and when we're editing one layer, say of polygons, and one polygon happens to be completely covered by another polygon, the one beneath cannot be selected. I appreciate that this situation probably doesn't occur a lot (several layers would normally be employed I imagine) but as it did just now and since it was discussed in Slack prior I thought it'd make a good issue. Even if the result is "use several layers" : )

**Comment by daRasmussen** [comment]
It's a feature 😁 I think most users would regard this bahavior as expected. ESRI Web Edit tools has the same bahavior. So the issue is not in origo its in the OGC spec. Feel free to adress this issue @ogc community standard.

**Comment by Grammostola** [comment]
Aha,,right :) Thanks. I expect it doesn't come up alot(features of the same layer covering each other); when it does and you are dealing with semitransparent polygons the instinctive question in the room in this instance was, from both GIS and non-GIS-personnel, 'How do we access the small square still visible but covered by the larger area polyon'. We'll find some workaround.

**Comment by daRasmussen** [comment]
Good question! I guess it depends on demand. I see your point but I think this issue will get resvoled in the spec and will trinkel down to Origo. Ofc its possible to resolve this issue right now, question is "is it worth it" ?

**Comment by mulfvik** [comment]
If several point-features share the same coordinates it would be nice to be able to choose which to edit

**Comment by daRasmussen** [comment]
@mulfvik Nice!

**Comment by tonnyandersson** [comment]
Archived and closed.

**Comment by steff-o** [comment]
The forthcoming #1614 could be a workaround for this.
