### ISSUE TITLE
ui folder in scss

### ISSUE THREAD

**Issue by daRasmussen** [origo-map/origo#620]
I was wondering what is the purpose of ui folder in scss? For example isn't _popup.scss part of the ui?

**Comment by afogelberg** [comment]
@daRasmussen the reason for this was that a completely new component system was introduced in Origo 2.0. However there were still some old components that still had not been migrated, like for example _popup.scss. In ui the general components, not specific to Origo, was collected.

**Comment by daRasmussen** [comment]
@afogelberg aha I see 👍

**Comment by daRasmussen** [comment]
This issue highlights that there is a need to revise the scss src, this suggestion is not necessary a good first step resolve. Smaller steps towards better structure is recommended.
