### ISSUE TITLE
Data type 'date' in JSON

### ISSUE THREAD

**Issue by Maryzandi** [origo-map/origo#625]
I have a problem with a column with data type 'date' in JSON file. The table is stored in PostGIS database and dates look good there (yy-mm-dd) but JSON appends "Z" at the end of dates. (yy-mm-ddZ)
![Skärmklipp1](https://user-images.githubusercontent.com/29747817/57841703-5767d600-77cb-11e9-83af-a7f69f733927.PNG)

**Comment by daRasmussen** [comment]
> The T is just a literal to separate the date from the time, and the Z means "zero hour offset" also known as "Zulu time" (UTC). 

I think the date data type could have a format option, maybe supply a regex as string. Or the default behavior could be to follow a static format.

**Comment by markus659** [comment]
Did you find a solution to this problem?

**Comment by tonnyandersson** [comment]
Not an Origo issue, but rather a back-end issue.
