### ISSUE TITLE
Option to clear measure

### ISSUE THREAD

**Issue by jokd** [origo-map/origo#641]
It would be nice to be able to clear the measures with an interaction (eg clicking a garbage can)  instead of when deactivating the tool. This way the measures can be around while interacting with the map.

**Comment by daRasmussen** [comment]
Great suggestion! This would be useful for a future plugin like measurements list or somerhing similar.

**Comment by johnnyblasta** [comment]
This would be a nice fix, since we have users that expressed that it would be useful to work on measurements and draw simultaneously together.

**Comment by jokd** [comment]
I intend to fix this soon, or are you up for it?

**Comment by johnnyblasta** [comment]
> I intend to fix this soon, or are you up for it?

I'm working on some other more pressing issues first so that depends on your definition on soon, but since you added it to your roadmap it's yours ;)
