### ISSUE TITLE
Disable cluster when zoomed in

### ISSUE THREAD

**Issue by afogelberg** [origo-map/origo#65]
When using clustered layers clustering is always turned on. Clustering should be turned off when zoomed in and when features are identifiable. It is now possible to achieve this since a method to set cluster distance has been added to OL and will be available in the next OL release.

**Comment by jokd** [comment]
Will this be solved if you have the option to set clusterdistance for a source? Or do you want to be able to set a zoom level where features no longer should be clustered? I can see some use for the latter but maybe that can be solved by styling with filters?

**Comment by afogelberg** [comment]
> Will this be solved if you have the option to set clusterdistance for a source? 

Yes, by setting the distance to 0. But I think this should be possible to set for all sources. By default at least the last zoom level should not be clustered. Cluster level can be set now by styling but that will have now effect on the clustering it self. It will only remove the style that is used for clustering.

**Comment by jokd** [comment]
I see. Sounds like we want to listen for zoom change and then alter the cluster distance accordingly. Indeed a nice improvement for v 1.0.
