### ISSUE TITLE
Second format for scaleline

### ISSUE THREAD

**Issue by daRasmussen** [origo-map/origo#666]
It think would be useful if the scaleline would support a second format. For example:

![image](https://user-images.githubusercontent.com/33061427/59506401-5dbf9f80-8ea8-11e9-99e9-5f30fd9ce994.png)

This would useful instead of having two instances of scale control.

**Comment by johnnyblasta** [comment]
Or to enable the scale to be divided into smaller intervals, perhaps.
|_____'_____'_____'_____'_____|
           500 m (100 m)

**Comment by daRasmussen** [comment]
@johnnyblasta sure

**Comment by jokd** [comment]
Closed due to inactivity
