### ISSUE TITLE
Introduce Sass for modular CSS

### ISSUE THREAD

**Issue by afogelberg** [origo-map/origo#67]
I believe we should introduce Sass in Origo for modular CSS. That way we could have separate builds of CSS for different use cases of Origo. For example I would like to make light builds of JS and CSS for simple embedded maps. What do you think @markus659  and @jokd ?

**Comment by markus659** [comment]
Yes, modularity is often a good thing. Using Sass would also help with making the css code more compact/fewer lines, right? As of right now, the css isn't too optimized and using something like Sass would help with that. I'm not sure how much work it would involve though, but I'm guessing it's worth it.

**Comment by afogelberg** [comment]
Fixed with #156
