### ISSUE TITLE
Footer not showing img/url

### ISSUE THREAD

**Issue by Flodkvist** [origo-map/origo#670]
Use of "footer" under pageSettings in config file has no effect.

"footer": {
  "img": "img/png/logo.png",
  "url" : "https://github.com/origo-map/origo",
  "urlText": "Origo"
}

Using same config file with older version origo version works.

**Comment by daRasmussen** [comment]
See [PR](https://github.com/origo-map/origo/pull/671) I also updated logic so it is possible to have image and text, image and url as well ass img, url and urlText.

**Comment by Flodkvist** [comment]
Works, good job!
