### ISSUE TITLE
text problem for editable layer with image

### ISSUE THREAD

**Issue by leafisfalling** [origo-map/origo#678]
What we would like to do is that we want to use the editor to save an image (as an attribute in database table) for a point layer to our Postgres database through the formula:
  
![origo1](https://user-images.githubusercontent.com/36880995/65037315-ad04e880-d94d-11e9-900a-f6855a544ca2.png)

For saving images in editing mode, we define the image attribute (“foto”) for the point layer in the configuration json file like this:
		{
	"name": "foto",
	"title": "Ladda upp bild: ",
	"type": "image",
	"image": "foto",
	"maxSize": 800 
		}
The image now is saved in the database as a very long text.  Now it comes to the problem. 

In Orgio 1, when I turn off the editing mode  and click a point from this point layer, the image is not previewed in the information box, the image just appear as text: 
 
![image](https://user-images.githubusercontent.com/36880995/65037608-5c41bf80-d94e-11e9-81c7-3305357bc786.png)

In order to show preview image for the point layer in the information box, I have to create another map layer for the points and declare the attribute in another way:
	{
		"img": "foto"
		}
 
![image](https://user-images.githubusercontent.com/36880995/65037641-6b287200-d94e-11e9-87ce-a4d71d14575e.png)

That means I cannot use one single point layer in editing mode och viewing mode in the map. I need to have 2 layers for the same thing in order to show the image. 

In Origo 2, it is even more problematic. 

I want to edit attributes for some existing points while the editing mode is on. I click a point and both the editing formula and the information box in viewing mode come up in the map (this behavior does not exist in Origo 1. In Origo 1, we cannot get any information box for any layer while the editing mode is on). 
 
![image](https://user-images.githubusercontent.com/36880995/65037646-6fed2600-d94e-11e9-9cab-086925616c95.png)

At the same time, if the point has an image, the image in the information box is shown as a very very long text (unlike Origo 1 which has the text length limited in the information box). This mean that when I click a point for editing, first the information box comes up and it extends and moves the map view downwards far away from the point.
  
![image](https://user-images.githubusercontent.com/36880995/65037661-74b1da00-d94e-11e9-841d-1af61591882e.png)

To go around this problem, I have to first make the editable point layer non queryable (so that no information box comes up with a long text) and then create another queryable layer for the same points in order to fulfill the image preview purpose. 

It would be very nice if we can use only one single layer that can show the preview image in editing mode or view mode instead.

**Comment by jokd** [comment]
I'll look into this.

**Comment by jokd** [comment]
I splitted the issue in two parts, addressing the issue with featureinfo along with editor in #681

**Comment by tonnyandersson** [comment]
When in edit mode, if you first select an object and then choose to edit attributes, the featureinfo popup stays open. Perhaps the info popup should close when the attributes form is opened. Otherwise, the popup will show the old attributes, even after they have been changed and the attributes form has been closed.

**Comment by jokd** [comment]
@tonnyandersson That should be fixed with #683
