### ISSUE TITLE
Option to make a subgroup work as a "normal" group

### ISSUE THREAD

**Issue by asemoller** [origo-map/origo#690]
Ability to remove the button that makes all layers in a subgroup visible.

Sometimes one doesn't want the users to make all the layers in the subgroup visible at once.
A subgroup should have the possibility to work just like a normal group.

Maybe as an option for subgroups in the config?

**Comment by tonnyandersson** [comment]
Same as #502?

**Comment by asemoller** [comment]
Yes, you´re right @tonnyandersson!

I can close this then!
