### ISSUE TITLE
Clear button in the legend

### ISSUE THREAD

**Issue by asemoller** [origo-map/origo#692]
The ability to turn off all visible layers at once.

**Comment by Grammostola** [comment]
Hi, we have one of those buttons: https://github.com/Eskilstuna-kommun/EK-extern/commit/f69894967d8426ae04b10ad870889e4ef1577c20 , I haven't investigated how compatible it is with the core yet but it is a UI component at any rate and does not look overly complicated. Can try attaching it to a core Origo on Tuesday if no one has commented to the contrary here before then : )

**Comment by asemoller** [comment]
Nice @Grammostola! looking forward to it :+1:

**Comment by Grammostola** [comment]
It introduces a new control component and from some preliminary testing doesn't seem tied to any variations of the core that we (Eskilstuna) are using. It isn't an on/off button but merely an 'off'. The commit does alter a few core files(overlays - menu width) and legend.js (the new button) and as it currently looks doesn't turn off layers that are set to visible in the config.json / from the start. I assume what you are looking for is 'Turn off all visible layers (except backgrounds) at once' and that's not hard to change.
It currently has a paper bin icon, see the attached screenshot. 
![bin](https://user-images.githubusercontent.com/5138906/65967912-b2405800-e462-11e9-9cec-2845ad3a0342.PNG) 
which could of course also be altered. 
Further comments may advice whether this might after some possible alterations be the subject of a pr or whether a dissimilar solution is preferred.
