### ISSUE TITLE
Need a better way of getting center for search feature

### ISSUE THREAD

**Issue by markus659** [origo-map/origo#75]
Right now the code looks like this:

```javascript
map.getView().setCenter([coord[0], coord[1]]);
```

But this will not work with different types of geometries (only for points). We need a better way of getting the center point of the search feature.

**Comment by afogelberg** [comment]
How about using ol.extent.boundingExtent http://openlayers.org/en/latest/apidoc/ol.extent.html#.boundingExtent and then using fit for the extent? We can also use the minResolution to make sure the map is not zoomed in too deep.

**Comment by markus659** [comment]
That sounds like it could work. Using something like minResolution for the zoom is also a good idea, since it will make it more dynamic.

The overlay (popup) also uses the coord variable to set its position, so that also has to be taken into consideration when fixing this issue.
