### ISSUE TITLE
Home button should not be created if no value is set for "home"

### ISSUE THREAD

**Issue by markus659** [origo-map/origo#76]
If no value for "home" is set in the configuration file, the button should not be created. Unless we want it to be a requirement to set a value for "home"?

**Comment by afogelberg** [comment]
If we want the home button to be optional then I think we should rather make it a control that can be added or removed as desired.  Then if no extent is defined for the home control we could use the map extent as default value.

**Comment by markus659** [comment]
I think I would be in favor of this, as most of the available items/buttons are already configurable as controls. @jokd any thoughts on this?
