### ISSUE TITLE
Form "OK" button restyled

### ISSUE THREAD

**Issue by mulfvik** [origo-map/origo#768]
Something changed the style on OK button in form in the last two-three days
![image](https://user-images.githubusercontent.com/24228538/70522618-c4650380-1b41-11ea-9e6e-cb409610cce7.png)

**Comment by jokd** [comment]
Is it because of change in row 12 & 37 in scss/ui/_input.scss (input -> input[type=text])
This seems to affect the search field as well.

**Comment by mulfvik** [comment]
Change input[type=text] to plane input did the trick for the form button and restriction in rezise to vertical. In what pr is this change done? Som I can fix it, or are you familiar with this pr and up for the fix?

**Comment by jokd** [comment]
It was changed with the new print control
