### ISSUE TITLE
Scale picker problem with character limit

### ISSUE THREAD

**Issue by asemoller** [origo-map/origo#780]
When using the scale picker, the presentation of the chosen scale becomes abbreviated when string becomes too long. This becomes very clear when implementing the option "buttonPrefix": "Scale: ". I.e: 1:16000 is presented as 1:16 and the right arrow moves down a bit.

![image](https://user-images.githubusercontent.com/17123002/70803436-58d69c80-1db4-11ea-8421-015197a895e5.png)

**Comment by jokd** [comment]
It also conflicts with the position control
