### ISSUE TITLE
Zoom to feature only in popup

### ISSUE THREAD

**Issue by jokd** [origo-map/origo#795]
The zoom to feature function should consider what type of infowindow the map is set up with (popup, sidebar etc.) Now it is hardcoded as popup.

**Comment by asemoller** [comment]
This is a very good point. I think that this type of change should be done in the forthcoming "selection manager", or what do you think @imantahriri?

**Comment by jokd** [comment]
It was an easy fix but I agree that the selection manager should handle this.
