### ISSUE TITLE
Make layers in group exclusive

### ISSUE THREAD

**Issue by jokd** [origo-map/origo#796]
It would be nice to set layers in a group as exclusive, making it possible to view only one layer at a time. Similar to the way background maps work. This would for instance prevent multiple coverages on top of each other making the map (and server) faster.

In other words, radio buttons working as radio buttons.

**Comment by MattiasSp** [comment]
I second this issue, I see as the QGIS equivalent "mutually exclusive"-options for groups, which I use and like a lot :)
