### ISSUE TITLE
Scrollning mapmenu with touch

### ISSUE THREAD

**Issue by Lund-gren** [origo-map/origo#80]
When scrolling mapmenu the layer/group you start scrolling on turns on/expands when the touch end. 
Poteniell fix for this: https://github.com/Hallstahammarskommun/origo/commit/bf8e425ac0d0cde083381f224dc15d213ff7d92a

**Comment by afogelberg** [comment]
Thanks for the report and the suggestion for a fix. But I think we are now ready to remove the touchend event that are used to achieve fast click: https://developers.google.com/web/updates/2013/12/300ms-tap-delay-gone-away
It should also work on iOS from 9.3. Removing the touchend should solve the scroll problem.

**Comment by afogelberg** [comment]
Fixed with #102
