### ISSUE TITLE
Featureinfo styling control

### ISSUE THREAD

**Issue by onlyleif** [origo-map/origo#806]
Styling options should be possible for the featureinfo on a per layer basis. Some useful cases would be controlling the width, height and overflow control with scrollbars, especially when displaying extensive content.

**Comment by tonnyandersson** [comment]
The various featureinfo displays (popup, sidebar, infowindow) require a fixed width on load to function properly. Fiddling with varying widths and such for different layers will open a can of worms.

The [html attribute](https://origo-map.github.io/origo-documentation/latest/#information-window) gives you some control over how the information is displayed. Try it out!
