### ISSUE TITLE
Snap to objects with measure tool

### ISSUE THREAD

**Issue by asemoller** [origo-map/origo#811]
Would be useful if one can snap to objects when using the measure tool. Perhaps as an option in the config just like the editor.

**Comment by Grammostola** [comment]
We could see it as useful as mentioned and feel it would be a boon for the user to be able to turn on/off snapping and the map author to be able to config what layers to be snappable against. (For our maps with primarily lots of WMS layers the specified layers could be fetched as WFS or something like that)

**Comment by asemoller** [comment]
Good idea @Grammostola! We are developing the function and a first draft is now being tested. Right now there is no button. You can set specified layers or all layers. But it may not be so bad to have a button. We have made it as the editor's snap function with the addition that you can select all layers.

**Comment by asemoller** [comment]
I need some input on which symbol to use for snapping. Unfortunately, material icons have no symbol with a magnet, which is the most common symbol. Some other suggestions are:
1.
![image](https://user-images.githubusercontent.com/17123002/114561930-54531a00-9c6e-11eb-8fbc-850400e0d581.png)
2.
![image](https://user-images.githubusercontent.com/17123002/114561287-b95a4000-9c6d-11eb-98fc-6f78c65de0be.png)
3.
![image](https://user-images.githubusercontent.com/17123002/114561616-03dbbc80-9c6e-11eb-99d2-eafcc6e36c3d.png)

Other suggestions are welcome!

**Comment by jokd** [comment]
@asemoller Any progress on this issue lately? We are interested in this functionality =)

**Comment by asemoller** [comment]
@jokd Take a look: [https://github.com/SigtunaGIS/origo/tree/origo-master-feature-measure-snapping](measure snapping)

**Comment by mulfvik** [comment]
> I need some input on which symbol to use for snapping. Unfortunately, material icons have no symbol with a magnet, which is the most common symbol. Some other suggestions are:
> 1.
> ![image](https://user-images.githubusercontent.com/17123002/114561930-54531a00-9c6e-11eb-8fbc-850400e0d581.png)
> 2.
> ![image](https://user-images.githubusercontent.com/17123002/114561287-b95a4000-9c6d-11eb-98fc-6f78c65de0be.png)
> 3.
> ![image](https://user-images.githubusercontent.com/17123002/114561616-03dbbc80-9c6e-11eb-99d2-eafcc6e36c3d.png)
> 
> Other suggestions are welcome!

How about this magnet [from ](https://fontawesome.com/v5.15/icons/magnet?style=solid) fontawesome?
