### ISSUE TITLE
Layers with same name but from different source isn't shown

### ISSUE THREAD

**Issue by johnnyblasta** [origo-map/origo#818]
If two layers with the same name but from different sources are present in the config json only one of them are shown.
A use case is when one wants to compare layers which has been updated between the test and production servers and doesn't want to change the names of all the layers.

**Comment by tonnyandersson** [comment]
Try naming the layers with a **double** underscore plus a suffix to tell them apart. Example:

**Layer 1**
`"name": "mylayer__prod"`

**Layer 2**
`"name": "mylayer__test"`

**Comment by johnnyblasta** [comment]
OK, that works! A "bit" of extra work when you have 40 layers times two to change the name on though.

**Comment by jokd** [comment]
That awesome feature must be documented.

**Comment by tonnyandersson** [comment]
I assume this could be automated with a function checking for duplicates and adding suffixes when necessary. But then I would not get to enlighten the people by sharing this hidden gem.

**Comment by jokd** [comment]
;)

**Comment by jokd** [comment]
Shall we close this?

**Comment by johnnyblasta** [comment]
This issue will be addressed in origo-documentation PR 77

**Comment by johnnyblasta** [comment]
This issue is addressed in origo-documentation PR 77
