### ISSUE TITLE
agstransaction needs an update

### ISSUE THREAD

**Issue by tonnyandersson** [origo-map/origo#821]
agstransaction.js is missing a viewer parameter since just importing viewer is no longer adequate. Also, later versions of ArcGIS Server sends insert, update and delete responses as JSON objects, rather than JSON text. Because of this, the response must be handled differently depending och AGS version.

**Comment by daRasmussen** [comment]
@tonnyandersson "later versions" of ArcGIS Server which version are you referring to?

**Comment by tonnyandersson** [comment]
@daRasmussen In this case 10.7 and (probably) later. Not sure if this is something that can be configured in AGS or not. But knowing that different versions/settings will produce different response formats, I thought it would be nice to have a safeguard to prevent errors for such simple reasons.
