### ISSUE TITLE
Legend Options

### ISSUE THREAD

**Issue by daRasmussen** [origo-map/origo#827]
Review of legend options in origo reference [api-documentation](https://origo-map.github.io/api-documentation/latest/#legend-control):

**Expanded** 

``` expanded | true or false if the legend should be expanded or collapsed on load. Default is true. ``` 

It states that **Default is true** but legend is not expanded as default. 
Config: 
``` "expanded": true ```
Does not work. 

Config: 
``` "expanded": false ```
Works! 👍 

**Inline Styling Options**
``` style | contentStyle:  option to add inline HTML style properties to the legend element.``` 
```  
"style": "width:1000px;background-color:red;",
"contentStyle": "width:1000px;background-color:red;"
``` 
Does not work. I suggest that "inline HTML" should be removed, for now. Since inline HTML syntax does not work right now. Instead it could say style and contentStyle takes an JSON object with CSS rules or something like that. It would make the it a bit clearar. 

**Class references**
```
.myClass 
{
    width: 1000px;
    background-color: red;
}
``` 
Injected in head of `index.html`
``` cls | contentCls | option to add css class references to the legend element. ``` 

Test 1 
```  
"cls": ".myClass",
"contentCls": ".myClass"
``` 
Does not work! This should be added to the documentation or fixed in code.
``` 
"cls": "myClass",
"contentCls": "myClass"
``` 
Background-color property works! 👍 But not width css rule. 
**.myClass HOTFIX**
```
.myClass 
{
    width: 1000px !important;
    background-color: red;
}
```
It WORKS!!! 

**Name**
``` name | option to set the legend UI component name. Default is 'legend'. ``` 

What is the purpose of this option, multiple legends? From a config only perspective, its not possible to reference this name in any other config option... ?? From a developers point of view, could be useful in some rare case but still a bit unclear why this should be done in the config. 

**LayersControl**
``` turnOffLayersControl | true or false for whether the turn off layers button should be present in the legend or not. Default is false.```

WORKS !! 👍 But why is the icon on its own row and not on the same row as the close button?

**Comment by daRasmussen** [comment]
Regarding expanded option. Think I found a bug, since this option is only triggered in production build of Origo and not the developer builder, can someone confirm this?

**Comment by jokd** [comment]
@daRasmussen I have tested and the behaviour is the same in production/developer build. And expanded: true or omitted results in the legend being expanded on load. However, if the screen size is below some breakpoint it is always collapsed, maybe this was what you experienced?

**Comment by daRasmussen** [comment]
@jokd yeah that could be it! 

I think I was a bit unclear this review is after dependency upgrade so I think that PR needs a bit of more testing.

**Comment by jokd** [comment]
It works as expected also after dependency upgrade. Can you reproduce it?

**Comment by daRasmussen** [comment]
@jokd I did a clean install and it seems to be working now. I can't reproduce this.
