### ISSUE TITLE
Custom scrollbar

### ISSUE THREAD

**Issue by daRasmussen** [origo-map/origo#828]
It would be nice if Origo had support for a custom scrollbar, this support does not have to be in IE and Edge App from windows store (since this would require a lot of effort). Custom scrollbar would be supported in browsers like Chrome, Firefox and Edge. 

Test case would be a lot of layers in the Legend.

**Comment by jokd** [comment]
The scrollbar in http://kartor.vasteras.se/sam-beta/ looks great.
