### ISSUE TITLE
More style filter options

### ISSUE THREAD

**Issue by asemoller** [origo-map/origo#858]
It would be very useful to be able to use filters with logical operators such as “AND” and “OR” when styling layers. Either with text (AND, OR etc.) or with regex.

Or is this already possible?

**Comment by tonnyandersson** [comment]
No, this is not already possible, as far as I know. The filter function can only deal with one argument.

**Comment by asemoller** [comment]
I have seen solutions where you add support for regex in style.js, would that be an approved solution for Origo?

I have not tested it myself so I don't know how well it works. Regex is common and it is easy to find good examples and help by googling. Although a better solution is preferable, I think it's better with regex than no support at all.

**Comment by hallstaelin** [comment]
We have regex in our style.js, https://github.com/Hallstahammarskommun/origo/blob/master/src/style.js

**Comment by asemoller** [comment]
Nice @hallstaelin! Does it work well for you?

Are you ready to submit a PR if the solution is approved? :)

**Comment by hallstaelin** [comment]
It works great!

Yes I can submit a PR if it gets approved :)

**Comment by asemoller** [comment]
It works well with OR, AND and regex so I'm closing this issue. Thanks!
