### ISSUE TITLE
Cluster style render instability in embedded maps

### ISSUE THREAD

**Issue by daRasmussen** [origo-map/origo#875]
When cluster style is used in embedded maps, the cluster style fails and does not show anything. It would be nice if this issue was resolved.

**Comment by jokd** [comment]
@daRasmussen I cannot reproduce this error. I used the testconfig and limited app-wrapper in height to get the embedded behaviour.

**Comment by daRasmussen** [comment]
@jokd Yeah, I noticed this, maybe this PR can be closed?

**Comment by jokd** [comment]
Well, if you say so =)

**Comment by daRasmussen** [comment]
@jokd this issue is related to animation controller, that I've used in vasteras fork. I guess, this issue could be a feature problem if animation would be part of origo.
