### ISSUE TITLE
Multiple constraints in editor

### ISSUE THREAD

**Issue by jokd** [origo-map/origo#878]
Sometimes it is useful to be able to set multiple constraints for a field, eg two alternatives will show a certain field in the popup that is otherwise hidden. As it is now you can only set one constraint.

**Comment by mulfvik** [comment]
@jokd When using the config below the comments attribute only show if subcategory_1_2 is selected and the form is closed and then reopened. Stumbled upon this a couple of days ago..

`{
            "name": "type",
            "title": "Type: ",
            "type": "dropdown",
            "options": [
                "category_1",
                "category_2",
                "category_3"
            ]
          },
          {
            "name": "name",
            "title": "Name: ",
            "type": "dropdown",
            "constraint": "change:type:category_1",
            "options": [
                "subcategory_1_1",
                "subcategory_1_2",
                "subcategory_1_3"
            ]
          },
          {
            "name": "comments",
            "title": "Comments: ",
            "type": "dropdown",
            "constraint": "change:name:subcategory_1_2",
            "options": [
                "subcategory_2_1",
                "subcategory_2_2",
                "subcategory_2_3"
            ]
          }
`

**Comment by johnnyblasta** [comment]
I have a fix for multiple constraints coming in soon!

**Comment by johnnyblasta** [comment]
> Been waiting for that ;)

You can help by testing and approve #1257 since it is changes in the same file.
