### ISSUE TITLE
It's not possible to add custom logo in print control

### ISSUE THREAD

**Issue by johnnyblasta** [origo-map/origo#879]
**Describe the bug**
It's not possible to add custom logo in print control

**To Reproduce**
Add a logo object in config and nothing will happen. Also it is not defined how the logo object should look like.

**Expected behavior**
A well defined logo object should be able to be added in the config and the custom image should be used when printed.

![image](https://user-images.githubusercontent.com/48793206/77929363-dc57c300-72a9-11ea-85ec-2a257d308c52.png)

![image](https://user-images.githubusercontent.com/48793206/77929551-14f79c80-72aa-11ea-9738-ed9033d94448.png)

**Comment by daRasmussen** [comment]
This is a valid request, this would be a nice addition.
