### ISSUE TITLE
Decimals in measure control 

### ISSUE THREAD

**Issue by jokd** [origo-map/origo#881]
Complaints have reached me regarding the number of decimal places for the measure tools, specifically measuring areas in the high hundreds it makes no sense showing two decimal figures. 
One idea is to set the precision as a config option, eg high or low, or have a look at the breakpoints we are using. Thoughts about this?

**Comment by jokd** [comment]
Closed, no biggie

**Comment by asemoller** [comment]
I'd like to reopen this one! @jokd are on to something here!

It makes no sense to show decimals in the high hundreds but not in low meters either. It can be way to accurate to display decimals in centimeters. It would be nice if breakpoints and number of decimal places are options in the config.
