### ISSUE TITLE
MapGrid

### ISSUE THREAD

**Issue by daRasmussen** [origo-map/origo#883]
Is mapGrid, release depended, I can't get tot work on commit before release version 2?

**Comment by jokd** [comment]
It used to be pageSettings.mapGrid

**Comment by jokd** [comment]
Nevermind, it still is ;)

**Comment by daRasmussen** [comment]
@jokd thanks for tip, I tried multiple configs but no luck. I am thinking that this case would be quite easy to create a test for.

**Comment by Grammostola** [comment]
Issue identified, will issue PR shortly. One part of the problem seems somewhat deliberate; we can discuss in the PR. (We lost the stenciled paper just recently as we went from ver 1 -> 2.0.1 )

**Comment by daRasmussen** [comment]
@Grammostola great job, LGTM!
