### ISSUE TITLE
Overlay as infowindow in index.json?

### ISSUE THREAD

**Issue by asemoller** [origo-map/origo#888]
I suggest we have overlay as infowindow in the index.json-file, like this:

```
"featureinfoOptions": {
    "infowindow": "overlay"
  },
```

**Comment by jokd** [comment]
@asemoller Isn't that the way the selection manager works? Or can it be configured both ways?

**Comment by asemoller** [comment]
You select in the config which infowindow you want to show in the map, either "infowindow", "overlay" or "sidebar".

I just think that "overlay" should be default in the config, right now "infowindow" will be displayed.

**Comment by jokd** [comment]
OK, my bad. I agree overlay should be default in config since it is the default when omitted.

**Comment by mulfvik** [comment]
@asemoller Ok to close this issue?

**Comment by asemoller** [comment]
yes!
