### ISSUE TITLE
Explanation of transparency slider

### ISSUE THREAD

**Issue by johnnyblasta** [origo-map/origo#898]
**Is your feature request related to a problem? Please describe.**
There should be a some sort of explanation of what is adjusted with the slider under the layer in the legend control

**Describe the solution you'd like**
There should be a label above the slider or a tooltip if hovering over the slider

**Comment by johnnyblasta** [comment]
It would look like this with a label
![image](https://user-images.githubusercontent.com/48793206/78785622-c03ddb00-79a7-11ea-9357-32edf4d40233.png)

**Comment by mulfvik** [comment]
Origo could have an translation object where there can be a choise to have it empty aswell. In that case the user can define for himself labels, tooltips etc. for the whole framework and Origo only mangage defaults.

**Comment by johnnyblasta** [comment]
> Origo could have an translation object where there can be a choise to have it empty aswell. In that case the user can define for themself labels, tooltips etc. for the whole framework and Origo only mangage defaults.

Sounds like a great idea. Is perhaps more a separate issue of its own when it is necessary to go through what else needs to be translated.

**Comment by daRasmussen** [comment]
I agree, this is a step forward, a future issue/pr is welcome.

**Comment by CBEskilstuna** [comment]
Maybe the text should be put to center of the slide

**Comment by johnnyblasta** [comment]
> Maybe the text should be put to center of the slide

Like this?

![image](https://user-images.githubusercontent.com/48793206/79333600-1f0ed180-7f1f-11ea-9d08-37ab37719bdc.png)

**Comment by johnnyblasta** [comment]
There is also this alternative:
![image](https://user-images.githubusercontent.com/48793206/79335473-6054b080-7f22-11ea-9c0b-b6f59509a3de.png)
