### ISSUE TITLE
Abstract for groups

### ISSUE THREAD

**Issue by asemoller** [origo-map/origo#904]
**Is your feature request related to a problem? Please describe.**
Sometimes it would be useful to show information (abstract) for a group, just like with layers and background maps. This was possible in older version of Origo.

**Describe the solution you'd like**
One solution could be to get "group info" when clicking on a group. But then the behaviour for expand and collapse groups must be changed. You would actually have to click on the arrow to expand and collapse the group. I'm not sure this is the best solution though. 

**Describe alternatives you've considered**
Another symbol next to the arrow? But it doesn't seem logical since layer info doesn't work that way. Any other ideas?

**Comment by MattiasSp** [comment]
[The documentation](https://origo-map.github.io/origo-documentation/latest/#groups) still lists `abstract` as a configuration option for groups, but that doesn't seem to do anything (at least not in 2.1.0).

Perhaps the text in the `abstract` configuration option could be added as a line of text between the group heading and the first layer, and be clickable so lines that are initially hidden are expanded when clicked?

**Comment by jokd** [comment]
I added the abstract below the group header. Expand/collapse by clicking on it can be a future enhancement.
