### ISSUE TITLE
removeOverlays does not remove overlays

### ISSUE THREAD

**Issue by tonnyandersson** [origo-map/origo#91]
The removeOverlays function in viewer.js does not actually remove overlays. The overlay elements remain in the document.

Suggest changing the way the overlays variable is set from

```javascript
var overlays = map.getOverlays();
```

to

```javascript
var overlays = map.getOverlays().getArray();
```

**Comment by afogelberg** [comment]
I recall I've seen the problem. I have made a PR that fixes the problem #93 . To make it work I also had to improve Popup a litte bit. Now removeOverlays will clear all overlays in the map including the popup bound to the overlay. To remove a specific overlay the ol.map method to remove overlay can be used.
