### ISSUE TITLE
Share map link to marked object

### ISSUE THREAD

**Issue by mulfvik** [origo-map/origo#910]
**Describe the bug**
When an object is marked the share map link does not pan/zoom to that object.

**To Reproduce**
Mark an object, press share map control and open the url i new window.

**Expected behavior**
The map should pan/zoom to the object that was marked before getting the link.

**Additional context**
Dont find any documentation for this feature.

**Comment by jokd** [comment]
Another one of the hidden gems of Origo!
Anyway, it works for me. Do you get a proper feature ID in the permalink or just some temporary geoserver nonsense? The latter occurs if you for instance are using a db view and geoserver are unable to get hold of the primary key. More on that here:
https://docs.geoserver.org/stable/en/user/data/database/primarykey.html

**Comment by mulfvik** [comment]
A shiny one aswell :)
Tested some more and it seems that this occurs on layers with cluster config. Can you confirm this? The url looks good as far as I can see. `...feature=vy_gata_belysningsstolpar.6241&map=extern`

**Comment by tonnyandersson** [comment]
The share map control is documented. [Thoroughly](https://github.com/origo-map/origo-documentation/blob/master/content/controls.md#sharemap-control).

**Comment by mulfvik** [comment]
...but for the function to zoom to an marked object ;)

**Comment by jokd** [comment]
You are right, this is a cluster issue. And it should have been solved last year: https://github.com/origo-map/origo/issues/590

**Comment by mulfvik** [comment]
Thought I recognized this but did not find any in search. Now it almost looks like harassment.

**Comment by tonnyandersson** [comment]
> ...but for the function to zoom to an marked object ;)

It's there, *between* the lines.

**Comment by jokd** [comment]
Tested and the map still doesn't pan to the feature. Tested on Edge Chromium with the origo-cities geojson as cluster layer.
