### ISSUE TITLE
Position controll performance issue

### ISSUE THREAD

**Issue by jaha7** [origo-map/origo#914]
**Describe the bug**
Position controll in latest origo-master update coordinates when panning map, browser need to render more resulting in lag/stutter. The issue is also somehow related to the legend controll and how many layers/group/subgroup it contains so if you have a lot of them it the map it will adversely affects performance.

**To Reproduce**
1. Add more (>10 of each) layers/groups and subgroups to index.json example.
2. Click and pan/drag the map (see that coordinate update in footer when pan).
3. Test panning the map using legend controll on or off to see the difference.
4. Recording performance in chrome debug shows renderingtime for task ”layout” that is higher even if layers are turned off.

**Expected behavior**
Working in same way as in origo version 1 when coordinates from mousepointer locks and not update when you click/hold and drag/pan the map.
Alternative (or both solutions) have a option for position controll to only use positonmarker (sight icon) function and not the ”always on” mousepointer update coordinates.
Of course best solution should be to solve the core problem, why legend items affects performance in Origo version 2.x.x

**Desktop (please complete the following information):**
 - OS: WIN10 build 18362
 - Browser chrome
 - Version 81

**Comment by jokd** [comment]
I have tested and compared to Origo 1 and can't say I feel there is much of a difference. Neither does removing the legend and position control have much impact in my case.
But I can as well se that the Layout task when using the position control takes significantly longer in Origo 2 which could have an effect on performance. Perhaps the easiest way is to simplt inactivate the position control while panning the map.

**Comment by jaha7** [comment]
Thanks for testing.

Yes i see, the performance issue is not so clear in the test.
It seems like the issue increases with number of items i legend.

The issue also looks a bit browser dependet because i get smoother results with Firefox and also latest Edge (beta chrome based).

The solution to inactive position controll when pan sounds great in my opinion.

**Comment by jokd** [comment]
When panning the coorintaes shown are actually jumping between center and pointer coordinates, indicating that there is a bug in the position control. Perhaps fixing that solves the issue.
