### ISSUE TITLE
Custom style in legend for thematic styling

### ISSUE THREAD

**Issue by jaha7** [origo-map/origo#915]
**Is your feature request related to a problem? Please describe.**
When using thematic styling, for example filter or maxscale/minscale the ”list” icon is the default style for legend. For some situtation you may want to set a custom style instead.

**Describe the solution you'd like**
It would be useful if you can set your own style for legend, regardless thematic styling. For example use a ”legendstyle” parameter for first thematic style rule that override”list” icon.

**Additional context**
![image](https://user-images.githubusercontent.com/47249045/80180002-0af36000-8602-11ea-8c2b-e56f0fa9a49e.png)
The second layer in picture above uses thematic styling with scales, here it would be nice to set a custom legend style.

**Comment by jokd** [comment]
I agree, this has been discussed and wished for earlier but perhaps it never took off.

**Comment by tonnyandersson** [comment]
This issue may have connections to #499 and #740.

**Comment by jaha7** [comment]
I found out that this function already exits with **"header": true** config-param for thematic styling.
So this issue can be closed.
