### ISSUE TITLE
Print - Date/time for creation

### ISSUE THREAD

**Issue by johnnyblasta** [origo-map/origo#916]
**Is your feature request related to a problem? Please describe.**
It would be nice to see the date/time for creation of printed map.

**Describe the solution you'd like**
The date/time for creation could be written out in the lower right corner. It should be selectable in the control settings if it is shown or not. Default value should be assigned in the config.

**Comment by johnnyblasta** [comment]
Done some work on this issue and here is the result:
![Print](https://user-images.githubusercontent.com/48793206/80472106-93486c80-8944-11ea-96b4-57377d357bf3.gif)

**Comment by mulfvik** [comment]
Straight forward toggler. Looking good

**Comment by johnnyblasta** [comment]
> Straight forward toggler, looking good! One thing. When no boarders, the datetime could render above the map, just like the other text. With a little bit of white background.

Yes it looks a bit odd without the border. As it is now the datetime is placed outside the actual map area, so it has to be moved inside the map area then and I don't now if it should. The title and description also "lives" outside the map area and creates with borders even if margins is off.
![image](https://user-images.githubusercontent.com/48793206/80485174-386d4000-8959-11ea-933b-953dfe721d96.png)

A fix that certainly should be done is when created and margins is off it shouldn't have a with border at the bottom.

**Comment by mulfvik** [comment]
Yes, agreed, the created should be outside map area. Is it on a new line if more text ie:
![image](https://user-images.githubusercontent.com/24228538/80486345-4c19a600-895b-11ea-988c-ccafb10d6a99.png)

For me there is no boarder at the bottm when margins is off.
