### ISSUE TITLE
Triggering enableInteraction event results in error

### ISSUE THREAD

**Issue by tonnyandersson** [origo-map/origo#92]
Triggering enableInteraction event results in an error if an edit session has not been previously initiated. The event triggers the onEnableInteraction function in editortoolbar.js, which in turn calls transactionhandler.removeInteractions() if the interaction is not named 'editor'. This function will fail if the variable settings.map has not been set.

Quick fix: wrap the contents of transactionhandler.removeInteractions() in an if- statement, e.g.:

```javascript
removeInteractions: function() {
    if(settings.map) {
        settings.map.removeInteraction(settings.modify);
        settings.map.removeInteraction(settings.select);		
    }
}
```
Perhaps utilizing flags would be a more flexible solution.

**Comment by afogelberg** [comment]
Thanks for the report @tonnyandersson . I added an isActive check, see PR #94 .
