### ISSUE TITLE
When infowindow is infowindow no sharelink object zoom.

### ISSUE THREAD

**Issue by mulfvik** [origo-map/origo#928]
Found one more bug, when infowindow is infowindow the zoom to object wont work at all. No id in url is present

_Originally posted by @mulfvik in https://github.com/origo-map/origo/pull/917#issuecomment-627834451_

**Comment by jokd** [comment]
I suggest we fix this by using the selectionmanager also for the old popup/sidebar along with the new infowindow and then rewrite the share map function accordingly.

**Comment by jokd** [comment]
@asemoller Is this still an issue?

**Comment by asemoller** [comment]
Yes, it still doesn't work with infowindow!

**Comment by jokd** [comment]
I can make a quick fix for this using same approach as for overlay(popup)/sidebar. You will just share one feature and it is not obvious which one it is in case you have multiple selections.
Should it be loaded in infowindow or as an popup?

**Comment by asemoller** [comment]
I guess you want it to load in the info window set in the json-file.
