### ISSUE TITLE
"infowindow" becomes transparent after print

### ISSUE THREAD

**Issue by asemoller** [origo-map/origo#930]
**Describe the bug**
After returning from print, the "infowindow" becomes transparent.

**To Reproduce**
1. Go to ['testkarta'](https://karta.sigtuna.se/arbmat/pr_861/)
2. Click on 'Meny' and 'Skriv ut'
3. Close 'Skriv ut'
4. Click on an object
5. See error

**Expected behavior**
The "infowindow" should look normal.

**Screenshots**
![image](https://user-images.githubusercontent.com/17123002/82417423-d1d0d300-9a7b-11ea-9203-4a9e6a314e6d.png)

**Desktop (please complete the following information):**
 - Chrome and edge

**Comment by asemoller** [comment]
Sigtuna takes this.

**Comment by jokd** [comment]
Closed with #934
