### ISSUE TITLE
Information window html @center transformation

### ISSUE THREAD

**Issue by mulfvik** [origo-map/origo#932]
When using @center as part of attribute there is no transformation from maps coordinate system to coordinate system defined as a parameter in function call.

`  "projectionCode": "EPSG:3006"
`
```
{
          "html": "<p>{{@center(EPSG:4326,default)}}</p>"
}
```
I expected that the output coordinates would be in EPSG:4326

**Comment by tonnyandersson** [comment]
The `map` parameter is missing in the `html()` function in getattributes.js:

https://github.com/origo-map/origo/blob/f97bb0a4e5b72d447dc6487d52524687d9187098/src/getattributes.js#L83-L93

Look at the `name`, `url` and `image` functions just above the `html` function for example. Also, please note that the `map` parameter must be passed as the last argument to the `replacer.replace()` function.
