### ISSUE TITLE
In Edge browser the opacity slider is reduced

### ISSUE THREAD

**Issue by johnnyblasta** [origo-map/origo#936]
**Describe the bug**
In Edge browser the opacity slider is reduced.

**To Reproduce**
1. Go to https://www.malardalskartan.se/origo/v2.2.0/test.html
2. Click on a layer in legend

**Expected behavior**
It should behave as other browser and take up the full legend window.

**Screenshots**
![image](https://user-images.githubusercontent.com/48793206/83004366-df540300-a00f-11ea-9710-c5cc27d4a60a.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Edge 
 - Version 44.17763.831.0

**Comment by tonnyandersson** [comment]
Edge looks fine here:

![image](https://user-images.githubusercontent.com/15725608/83005521-2d1d3b00-a011-11ea-8599-0bdfa6519098.png)

I am, however, using the slighty more recent version 83.0.478.37.

**Comment by mulfvik** [comment]
Same problem in IE11

**Comment by jokd** [comment]
Edge is Chromium based since version 79 or something so this bug is for the "old" Edge and IE (of course)

**Comment by jokd** [comment]
Removing the transitions in slidenav.scss will solve this. However the behaviour in all browsers will be affected. Perhaps it is possible to make an IE exception in the css?
