### ISSUE TITLE
Fullscreen button is shown in Edge

### ISSUE THREAD

**Issue by johnnyblasta** [origo-map/origo#937]
**Describe the bug**
Fullscreen button is shown in Edge even if the map isn't embedded.

**To Reproduce**
1. Go to https://www.malardalskartan.se/origo/v2.2.0/test.html
2. See error in screenshot

**Expected behavior**
The button shouldn't be visible unless embedded.

**Screenshots**
![image](https://user-images.githubusercontent.com/48793206/83005662-5fc73380-a011-11ea-9bf2-906ada77a953.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Edge
 - Version 44

**Comment by tonnyandersson** [comment]
Not present in Edge version 83.

![image](https://user-images.githubusercontent.com/15725608/83007042-6060c980-a013-11ea-9b1b-4eef2a8da1d6.png)

I think we need a third opinion on these Edge issues.

**Comment by jokd** [comment]
I cannot reproduce this in any browser, however I have no old Edge. Did you have developer tools or something opened while testing that shrank the size of the browser window?

**Comment by johnnyblasta** [comment]
OK, that was it, but I had the window fairly large, at least 1800 px width, so not that small.

**Comment by johnnyblasta** [comment]
I'm closing this since it seems related to me have a 4k screen and it's relative to the screen width, so you can have a large window open and stil get fullscreen icon.
