### ISSUE TITLE
Share map AGS Map Service 

### ISSUE THREAD

**Issue by mulfvik** [origo-map/origo#938]
**Describe the bug**
When sharemap with selected object on AGS Map Service the map is blank. 
**To Reproduce**
[https://www.malardalskartan.se/origo/v2.2.0/test.html#layers=topowebbkartan_nedtonad/v/1/s/0,isbanor/v/1/s/0&center=153470,6612205&zoom=7.6155244561302435&feature=isbanor.2690&map=test](https://www.malardalskartan.se/origo/v2.2.0/test.html#layers=topowebbkartan_nedtonad/v/1/s/0,isbanor/v/1/s/0&center=153470,6612205&zoom=7.6155244561302435&feature=isbanor.2690&map=test)

**Expected behavior**
There should be a map present and init zoom to selected object.

**Comment by mulfvik** [comment]
When using sharemap with grouplayer the url gives you a map and its layers, nothing more.

**Comment by jokd** [comment]
I dont think the share map function is supposed to handle raster sources the way it is built. Perhaps we should change the share map function to omit feature when using a non-vector source?

**Comment by jokd** [comment]
WMS wont work as well.

**Comment by mulfvik** [comment]
> I dont think the share map function is supposed to handle raster sources the way it is built. Perhaps we should change the share map function to omit feature when using a non-vector source?

Agreed
