### ISSUE TITLE
Search not working in IE11

### ISSUE THREAD

**Issue by johnnyblasta** [origo-map/origo#939]
**Describe the bug**
Search not working in IE11

**To Reproduce**
1. Go to https://www.malardalskartan.se/origo/v2.2.0/test.html
2. Search for 'karl'
3. No result

**Expected behavior**
Should have returned matches.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser IE
 - Version 11

**Additional context**
Errors in console

**Comment by mulfvik** [comment]
[https://stackoverflow.com/questions/30571488/windows-resize-trigger-event-is-not-working-in-ie11](https://stackoverflow.com/questions/30571488/windows-resize-trigger-event-is-not-working-in-ie11)

**Comment by jokd** [comment]
Fixed with #940
