### ISSUE TITLE
"infowindow" - move "ExportedFileName" to "ExportUrls"

### ISSUE THREAD

**Issue by asemoller** [origo-map/origo#941]
**Is your feature request related to a problem? Please describe.**
Currently the filename for layer specific export in infowindow is set per layer which makes it impossible to set multiple exports with different file extensions within the same layer.

**Describe the solution you'd like**
Move "ExportedFileName" to "ExportUrls" for LayerSpecificExport.

**Comment by jokd** [comment]
Closed with #942
