### ISSUE TITLE
Upgrade jQuery to 2.1.4

### ISSUE THREAD

**Issue by afogelberg** [origo-map/origo#96]
I think it's a good idea to upgrade jQuery to 2.1.3. This will lead to a nice file size reduction. As far as I can see there will be no problems with the jQuery plugins used in Origo.

**Comment by afogelberg** [comment]
Anyone opposing this @jokd @markus659 ?

**Comment by jokd** [comment]
Or perhaps 2.1.4 which seems to be a bugfix for 2.1.3. 
Are the 2.2.x versions bigger or breaks some functionality?

**Comment by jokd** [comment]
Upgrade to 2.1.4 seems like a good idea then.
