### ISSUE TITLE
Print - Be able to set the scale

### ISSUE THREAD

**Issue by johnnyblasta** [origo-map/origo#960]
**Is your feature request related to a problem? Please describe.**
When printing there should be a option to set the scale of the map.

**Describe the solution you'd like**
In the settings window there should be a option for selecting scale with a dropdown list with the different scales. Use the resolutions of the map to populate the dropdown with the scales

**Describe alternatives you've considered**
Other ways of selecting the scale is probably no good since the list can be quite long, up to 10-15 scales.

**Additional context**
Once you've set the scale it's good to see on the map which scale it has, but that is a separate issue #903

**Comment by jokd** [comment]
Check this out, new in 6.4.0 release:
https://github.com/openlayers/openlayers/pull/10537
https://openlayers.org/en/latest/examples/print-to-scale.html
