### ISSUE TITLE
Print - Get higher resolution

### ISSUE THREAD

**Issue by johnnyblasta** [origo-map/origo#961]
**Is your feature request related to a problem? Please describe.**
When printing it should be possible to set the resolution to get a higher quality of the printed map.

**Describe the solution you'd like**
In the print settings there should be a option for chosing the print quality. It would probably suffice to have 3 buttons with low, mid and high as options.

**Describe alternatives you've considered**
To be able to set an arbitrarily resolution might be a option, but don't know if it's necessary.

**Additional context**
Not only the resolution of the map image should be changed, but also the map element on the map should be changed.

**Comment by jokd** [comment]
Check this out, new in 6.4.0 release:
https://github.com/openlayers/openlayers/pull/10537
https://openlayers.org/en/latest/examples/print-to-scale.html
