### ISSUE TITLE
Indication when a group has visible layers within it

### ISSUE THREAD

**Issue by Zakuto3** [origo-map/origo#970]
Whenever a group has active(visible) layers the group itself would indicate it. I think it would ease the user experience, especially if you have many groups. How the group would show that it has visible layers is up to discussion, i would suggest a slightly different background color or something similar.

**Comment by Zakuto3** [comment]
Here are some visual suggestions:

![Anteckning enhl1](https://user-images.githubusercontent.com/24722471/86931363-4d740580-c138-11ea-9749-1ff499edc48f.png)

**Comment by mulfvik** [comment]
In favor of suggestion nr 3

**Comment by Grammostola** [comment]
I like how 4.0 and .1 link the individual lit layers with the group disclosure arrow/lit layers indication via the color blue.
Am also a fan of how 3 appears just-subtle-enough. 5 looks a little like "click me" (though a combination of 4.1 and 5 can be imagined) and 1 could be seen as slightly ambiguous, at least for first time Origoers. Whatever the choice it seems a nice feature.

**Comment by tonnyandersson** [comment]
I like 3. And 5. But mostly 3. Especially if it comes with a subtle animation. Like a lightsaber. No need for sound effects - y'all can hear it in your heads anyway.
