### ISSUE TITLE
Shared map zoom level doesn't always match the shared map's

### ISSUE THREAD

**Issue by Grammostola** [origo-map/origo#984]
**Describe the bug**
When sharing a map the zoom level isn't always respected. Specifically with constrainResolution: false the opened shared map seems to interpret zoom 6.23932323 as 6.0. In terms of the OSM default background map that makes sure labels are always "crisp" even if the view isn't precisely what was shared. If constrainResolution: true then a shared zoom 18 is often interpreted as 17. This is true also if the start zoom level of the map (not shared) is set to 18.

**To Reproduce**
1. Latest Origo in debug
2. Set the map property constrainResolution to true
3. Zoom in via a scroll wheel or touch to the largest scale and share the map: 
4. Open it in another tab: it will likely show one zoom level out
2.1 Set the map property constrainResolution to false
3.1 Zoom in  or out a bit with the scroll wheel or - and + buttons, so that labels look slightly dim
4.1 Open in in another tab; labels will likely look sharp. The URL will include zoom=6.23231351341 and if that's changed to 6 and the page reloaded the map view doesn't change.

**Expected behavior**
For certain the constrainResolution: true shared map zoom level should be respected when opening
for constrainResolution: false then at least for WMS layers the current functioning can arguably be called a feature perhaps but I would personally feel better if 6.82323 was 6.82323

**Additional context**
An additional possibly related issue is that if constrainResolution is true: then zooming in and out with the plus and minus buttons enough will not respect the zoom levels given for the map, unlike when the map is zoomed via a mouse scroll wheel. In addition there seems to always be an extra zoom level out when zooming with the minus button as opposed to a scroll wheel. This level does not appear to adhere to the map resolutions. 

I have been unable to reproduce any of these issues in a release 1.x version of Origo (karta.sigtuna.se)

**Comment by jokd** [comment]
Tested a bit and the map doesn't bother the decimal places at all, zoom 6 and zoom 6.999 results in the same extent.

**Comment by Grammostola** [comment]
In regards to the map opening at a different zoom level than specified in index.json, whether a shared map or not, it seems the OL View class autocorrects as per its given constraints, with a small animation of zooming out in the case of a resolution constraint. https://openlayers.org/en/latest/apidoc/module-ol_View-View.html . I don't see an (acceptable) way of setting a resolutionDirection for endInteraction(opt_duration, opt_resolutionDirection, opt_anchor), though I may have missed it, else "in" would be preferrable for us (for scale dependant symbology that disappears at a smaller scale), . If the View isn't given the resolution constraint in (constrainResolution:true in index.json) then I've been unable to reproduce the map opening at the wrong zoom level issue, so perhaps this particular branch of this umbrella issue must be "Not to be fixed". After all the scale indicator in a map view, however nicely even, is "in the general ballpark of" at best. Worse might be wms-cached background maps at higher resolutions but I digress. "Do not fix" for this particular tangent sounds correct?

**Comment by Grammostola** [comment]
The final issue (I think), that pressing the zoom in and out buttons isn't the same as scrolling with a wheel in that constrainResolution: true scales are missed sometimes, appears to be due to clicking/pressing the zoom in/out buttons with a Nintendo finger. If constrainResolution: true and you hit that Zoom in button like there's no tomorrow the map will land at "between"scale but both the map and the scale denominator will update - snap to the nearest resolution, as soon as the map is panned. I can try to tweak the animation timing interaction in Origo a little bit but ..it could be that I'm the only one with a Nintendo finger.
