### ISSUE TITLE
Travis test fail

### ISSUE THREAD

**Issue by jokd** [origo-map/origo#986]
**Describe the bug**
Travis test fails for Node 8 & 9 due to copy-webpack-plugin version in package.json bumped from version 5 to 6. Version 6 requires Node > 10

**To Reproduce**
See the test log for latest PR.

We should either go back to version 5 or drop support (and testing) for Node < 10

**Comment by daRasmussen** [comment]
That sound about right! 

I would suggest to drop version 8 and 9. And add node version 14.

**Comment by jokd** [comment]
Agreed.
