### ISSUE TITLE
Externalurl control error

### ISSUE THREAD

**Issue by mulfvik** [origo-map/origo#987]
**Describe the bug**
When using the control "externalurl" I get this in the console:
![image](https://user-images.githubusercontent.com/24228538/92451471-09939000-f1bd-11ea-8af3-fc5b4c4a9d67.png)

**Comment by jaha7** [comment]
Get similar in console when try to use "measure-elevation" (origoserver with HöjdDirekt)
![origo_probs](https://user-images.githubusercontent.com/47249045/93213791-9b267300-f764-11ea-88f4-c00bed8d4766.JPG)

**Comment by johnnyblasta** [comment]
Closed by #998
