### ISSUE TITLE
Measurement in shared map

### ISSUE THREAD

**Issue by johnnyblasta** [origo-map/origo#999]
**Is your feature request related to a problem? Please describe.**
When you share a map and has done measurements it would be nice to have them shown.

**Describe the solution you'd like**
If there is measurements on the map when clicking share map they would be saved and when the share link is used the measurements should be added to the map.

**Comment by tonnyandersson** [comment]
I'm currently working on #391, which involves major changes to the measure control. I suggest putting this one on hold until #391 is done and merged.
